- docs/administration/upgrading/upgrading-from-octopus-2.0.md
This prevents hitting the wrong one and breaking something.
> PowerShell for registry key removal

- docs/administration/managing-users-and-teams/external-groups-and-roles.md
Line 9 added to include additional info on controlling permissions of users by adding groups to Teams.
Line 28 added to include info on Octopus automatically creating Octopus Users when they don't exist AND authenticate with AD.
> Added info under intro and Trusted Domains

- docs/deploying-applications/windows-services.md
This applies to any type of account, not necessarily just a service account.
After beating my head against my desk for a week or so being frustrated that our CI pipeline relied on somebody manually entering the credentials to grant accounts the ability to run scheduled tasks or logon as a service, I came across Carbon and after a bit of poking around figured out how to script granting  these permissions. The only "caveat" is that the account granting the permission needs to be a member of Local Administrators (I think) in order to have the "delegation" permission.
> Example Octopus script option for Service Accounts

- docs/deployment-targets/ssh-targets/configuring-ssh-connection.md
The updated command is what works on Ubuntu 16.04.  I think it's also a bit more future-proof assuming that Octopus itself isn't flexible on the format of the thumbprint.
> Update ssh-keygen command in format Octopus is looking for

- docs/deploying-applications/variables/system-variables.md
Line 191: Added disclaimer to description explaining why this variable behind a load balancer/reverse proxy may not be suitable.
Source: http://help.octopusdeploy.com/discussions/questions/10909
> Octopus.Web.BaseUrl variable description edit

- docs/guides/azure-deployments/azure-environments.md
The page https://octopus.com/docs/guides/azure-deployments/azure-environments displays '##Azure Environments' in the HTML output.
Removed redundant title.
> Removed unparsed title ##Azure Environments

- docs/administration/authentication-providers/index.md
Clarified the need for a password when creating a new user in Octopus - that it's the UsernamePassword provider password only, and that it isn't the user's AD password.
> Added info on passwords when adding new user

- docs/deploying-applications/automatic-deployment-triggers.md
Added a table listing options for events to trigger a deployment. This makes it a bit more clear what event groups do, and all of the options without having to look through the web portal.
> Added a list of event groups and included events

- README.md
- docs/deploying-applications/variables/system-variables.md
- docs/deploying-applications/variables/system-variables_packageVariables_(,3.4).partial.md
- docs/deploying-applications/variables/system-variables_packageVariables_[3.4,).partial.md
No longer named `Octopus.Action.Package.NuGet*`
> Update names for Package Feed, Id and Version vars

- docs/api-and-integration/octo.exe-command-line/index.md
4 commands were not listed: dump-deployments, list-environments, list-releases and list-tenants.
> Added missing octo.exe commands

- docs/installation/installing-tentacles/azure-virtual-machines/configuration-structure.md
From decompiling the extension I believe these are the only missing properties:
- MachinePolicy
- Tenants
- TenantTags
The values used for the example should be consistent with the rest of the documentation.
> Adding missing publicSettings properties for AzureRm VM extension

- docs/how-to/troubleshoot-polling-tentacles.md
As far as I can tell from other documentation, such as https://octopus.com/docs/installation/installing-tentacles/polling-tentacles, the default port for polling tentacles is 10943, and this was the case for my Octopus server, but this document was using 10934 (with the 3 and 4 transposed).
(Interestingly, the 10934 port is used elsewhere in the documentation, for instance, in this document: https://octopus.com/docs/administration/upgrading/upgrading-from-octopus-2.6/in-place-upgrade-install-over-2.6. There, the tentacle was a *listening* tentacle, and the 10934 port may have been chosen by incrementing the default listening tentacle port of 10933 by 1... perhaps this was the cause of the confusion?)
> Use correct default port for polling tentacles

- docs/guides/use-the-team-foundation-build-custom-task/extension-compatibility.md
looks like the version was rebuilt and 2.0.39 was what got released, but the link text didn't get updated correctly to match.
Source http://help.octopusdeploy.com/discussions/questions/11394
> fixed typo in the TFS 2015 extension version

- docs/administration/high-availability/configuring-octopus-for-high-availability.md
Updating HA documentation to clarify options when configuring Tentacles in polling configuration
- added cmd line option and switches 
- added clarification around implications of editing Tentacles.config file directly
> HA documentation update

- docs/deploying-applications/custom-installation-directory.md
Include escape sequences so slashes & square brackets show correctly in paths
> Include escape sequences

- docs/administration/upgrading/upgrading-from-octopus-3.x.md
Documentation update around offline installs.
Small tweak to wording around Server and Tentacle versions no longer being in sync
> Offline install doco update

- docs/guides/azure-deployments/web-apps/web-app-concepts.md
WebDeploy no longer supports the regex we were using in this hint. It also no longer needs to, deployment of Web Apps into virtual directories no longer interfere with each other.
E.g. deploying ComponentA to a virtual directory of a site, and using the **Remove additional files** option, will not remove files from the root site or ComponentB.
Fixes OctopusDeploy/Issues#3384
> Removed hint about PreservePaths regex

- docs/guides/multi-tenant-deployments/multi-tenant-deployment-guide/deploying-a-simple-multi-tenant-project.md
The link back to the page with the deploy script wasn't properly formatted.
The last letter wasn't part of the hyperlink, resulting in only part of a word being clickable.
> Fix hyperlink in deploying-a-simple-multi-tenant-project.md

- docs/guides/multi-tenant-deployments/index.md
Just some small typo fixes in the page `Multi-tenant deployments`
> fix small typo's in Multi-tenant deployments

- docs/api-and-integration/teamcity.md
- docs/deploying-applications/deploying-asp.net-core-web-applications/index.md
- docs/packaging-applications/creating-packages/nuget-packages/using-octo.exe.md
- docs/packaging-applications/creating-packages/nuget-packages/using-octopack/index.md
This PR updates various doco to warn users about OctoPack's incompatibility with .NET Core. Used warnings in places where I think it should stand out, and new sections where it needed to be more informative (in the hope that this will put downwards pressure on support).
> Adding information about OctoPack's incompatibility with .NET Core

- docs/administration/security/outbound-requests.md
Not sure if it's too specific/scary. We could probably ditch a lot of the specific lines with some wording like:
> We also track usage of some features (such as multi-tenancy, LetsEncrypt, guest accounts et. al.) to see what user uptake is like. These are only true/false values of whether you are using the feature, and contain no identifying information about _how_ you are using the feature.
And just use that to capture new inclusions that fall under that wording (like how adding new step types falls under the "the types of step you use and how many" wording).
> Updated usage stats and when added

- docs/credits.md
Used github link instead of website (http://bootstrapswitch.site/) based on precedent set by others, such as Font Awesome
> Fixing broken Bootstrap Switch link in credits.md

- docs/administration/authentication/authentication-providers/index.md
Detail on why we match across multiple fields, and why you shouldn't share email addresses
> more detail on AD scenario

- docs/administration/server-configuration-and-file-storage/moving-octopus-server-folders.md
The powershell provided was incorrect.  If you ran the command as is it would put a subfolder in the destination folder.  So instead of C:\YourNewHomeDir\Packages it would be C:\YourNewHomeDir\Packages\Packages.  A fun quirk with mv.
> Fixing incorrect PS examples

- docs/infrastructure/deployment-targets/windows-targets/requirements/index.md
Azure PS 5.7.0 required Powershell 5+ but more recent versions require 5.1 or newer
> Update Powershell version requirement for Azure PS modules

- docs/api-and-integration/octo.exe-command-line/create-release.md
- docs/api-and-integration/octo.exe-command-line/dump-deployments.md
- docs/api-and-integration/octo.exe-command-line/import.md
- docs/api-and-integration/octo.exe-command-line/list-deployments.md
- docs/api-and-integration/octo.exe-command-line/list-environments.md
- docs/api-and-integration/octo.exe-command-line/list-latestdeployments.md
- docs/api-and-integration/octo.exe-command-line/list-machines.md
- docs/api-and-integration/octo.exe-command-line/list-releases.md
- docs/api-and-integration/octo.exe-command-line/list-tenants.md
- docs/api-and-integration/octo.exe-command-line/push.md
- docs/api-and-integration/octo.exe-command-line/version.md
An automated update of the command line docs for octo.exe.
Created by TeamCity project 'Automated Documentation Updates::Update CLI Docs', build 34
> Updating cli docs for octo.exe

- docs/api-and-integration/compatibility.md
https://trello.com/c/jBuW0lx6/282-compatibility-matrix-in-docs-is-incorrect
> Update compability of Octopus.Client/octo.exe for versions upto and including 2018.12

- docs/administration/security/hardening-octopus.md
Configurations using named instances with the SQL Server Browser Service make outbound requests to UDP 1434.
> Add UDP 1434 to outbound rules

- docs/infrastructure/machine-policies.md
Machine policy health checks are now customisable for Bash and PowerShell instead of for Tentacle and SSH.
> Update machine policy docs to reflect model changes

- docs/api-and-integration/teamcity.md
Minor change to point people to the TeamCity plugin repo instead of our downloads page. The download page link will be going away with its upcoming redesign.
> Updated TeamCity page to point to JetBrains plugin repo.

- docs/packaging-applications/index.md
I've removed the warning about multipart file extensions, as this no loner appears to apply. Alex, I've marked you as a reviewer to confirm that's the case.
> Removed out of date warning

- docs/administration/security/outbound-requests.md
- The opt-out of sending usage statistics will be removed from the installer with https://github.com/OctopusDeploy/OctopusDeploy/pull/3813, and exposed via the Portal with https://github.com/OctopusDeploy/OctopusDeploy/pull/3799
- This PR updates the doco to direct users who want to opt-out to the new location
> Checking for updates doco now refers to Settings rather than the installer

- docs/api-and-integration/migration-api/index.md
- docs/api-and-integration/octopus.migrator.exe-command-line/partial-export.md
- Remove the `--sourceSpaceId` option from the doco for the migrator's `partial-export` command. This option doesn't exist.
- Raised [via support](https://help.octopus.com/t/partial-export-with-sourcespaceid/23182)
- Also tweaked a related option description
> Fix migrator partial-export command options

- docs/deployment-examples/azure-deployments/resource-groups/index.md
Octopus.Action[ArmTemplateStepName].Output.AzureRMOutputs[Foo]
Should be:
Octopus.Action[Arm Template Step Name].Output.AzureRmOutputs[Foo]
Two mistakes, the spaces in the step name, and the casing of the m in RM. 
@robpearson or @benPearce1, if either one of you could confirm this, that would be very helpful.
> User feedback re Accessing ARM Template Output

- docs/infrastructure/deployment-targets/linux/index.md
- We're [upgrading Calamari to netcore 2.2](https://github.com/OctopusDeploy/Calamari/pull/402) and this is [not supported](https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2-supported-os.md) by Ubuntu 14.04. Ubuntu 14.04 reached its [End of Standard Support](https://wiki.ubuntu.com/Releases) last month.
- This PR removes Ubuntu 14.04 from our list of [Supported Distributions](https://octopus.com/docs/infrastructure/deployment-targets/linux)
> Remove support for Ubuntu 14.04 LTS targets

- docs/infrastructure/machine-policies.md
Wording change to clarify that administrative rights are required for Tentacle upgrades.
> Tentacle-Permissions-Update

- docs/packaging-applications/package-repositories/index.md
I updated the links in the Azure DevOps Package Feeds section. I couldn't find a good page for alternate credentials so I linked back to the PAT page.
> Updated links to Microsoft PAT documentation

- docs/deployment-process/variables/system-variables.md
Add note to Octopus.Web.ServerUri that it was added in 2019.4.0.
> Add version to Octopus.Web.ServerUri

- docs/infrastructure/deployment-targets/machine-policies.md
I've added this to aid a customers support query regarding tentacle upgrades. 
'Logical processor count' refers to this value given by the .NET framework https://docs.microsoft.com/en-us/dotnet/api/system.environment.processorcount?view=netframework-4.8
>  Added documentation to clarify the speed limit for calamari upgrades 

- docs/infrastructure/deployment-targets/linux/tentacle/index.md
- docs/infrastructure/deployment-targets/linux/tentacle/quickstart-debian.include.md
- docs/infrastructure/deployment-targets/linux/tentacle/quickstart-fedora.include.md
- Did a rename of "Quick start scripts" -> "Automation scripts"
- Removed net core instructions, I don't think it's actually a pre-req because we bundle
- Removed blurb about the portal not having a way to add linux Tentacle
> Update apt + repo urls

- docs/deployment-process/issue-tracking/jira.md
In `2019.7.5` we made some changes to when we display work items:
1. The Jira issue tracker extension must be enabled
2. The Jira Base URL must be configured
3. Jira username and password is now required, this is so that we can verify that the issue exists in there Jira instance as we've relaxed the regular expression we use to parse work items which could mean false positives gets parsed.
This PR updates the Jira docs page to make point 3 clearer.
> Make it clear that jira username/password is required to display work items in Octopus

- docs/support/troubleshooting-failed-or-hanging-tasks.md
- docs/support/troubleshooting-hanging-tasks.md
A recent theme in support is around hanging tasks. Often this is anti-virus. A docs page explaining some common debugging steps could go a long way to deflecting these kinds of support issues, and this PR is an attempt at adding that page. At the same time, common debugging techniques for failed tasks feels like a cohesive addition to this page.
> Added some documentation around debugging failed or hanging tasks

- docs/shared-content/json-configuration-variables.include.md
There was a comma missing in the json example for the simple variable transform -- I added it here.
> Add comma in simple variable transform example

- docs/infrastructure/deployment-targets/linux/tentacle/index.md
Following the doco to set up the Linux tentacle as a service, I found that the service would not start because of the working directory didn't exist.  Changing the working directory from default to tentacle allowed my Linux tentacle to start correctly as a service.  Being a Linux noob, it is entirely possible that I did something incorrect during the installation process, which is why I'm requesting a review of the change.
> Update to unit file

- docs/octopus-rest-api/octopus.client.md
The customer who raised this [ticket](https://help.octopus.com/t/using-add-type-to-load-octopus-client-type-from-nuget-package-errors/23748) was looking for guidance on how to use OctopusClient from powershell in a portable fashion.
We determined there was an issue with dependencies, which was fixed in https://github.com/OctopusDeploy/OctopusClients/pull/454, but this PR updates docs to try and make it easier to get started.
Please try out the updated commands and make sure they work as expected
> Update OctopusClient docs to make it easier to get started

- docs/octopus-rest-api/octopus.client.md
As the netstandard version of octopus client is not (yet) ilmerged, users may need to import `newtonsoft.json.dll` and `octodiff.dll` as well.
> Update octopusclient docs for use on pwsh on linux

- docs/deployment-process/variables/variable-filters.md
- docs/deployment-process/variables/variable-substitutions.md
Adds documentation for new variable filters that were added in Octostache 2.6.0: Trim, Truncate, and Substring.
Those additions are in the last commit. The previous commits prepare for supporting more numerous and complex filters, by adjusting the sorting, linking, completeness, and formatting clarity.
> Document new variable filters: Trim, Truncate, Substring

- docs/administration/managing-infrastructure/tentacle-configuration-and-file-storage/manually-uninstall-tentacle.md
I'd originally thought that the docs on manual uninstalls weren't updated after the instance store was changed to be on the file system.
After looking closer, it did cover it, but I've expanded it a tiny bit to be clearer.
> Expand info on where instance configuration is stored

- docs/installation/automating-installation.md
- docs/octopus-rest-api/octopus.server.exe-command-line/configure.md
- docs/octopus-rest-api/octopus.server.exe-command-line/create-instance.md
Updates the automated install instructions, and also the `create-instance` and `configure` command docs.
Relates to https://github.com/OctopusDeploy/Issues/issues/5793
Pulls in some of the changes from https://github.com/OctopusDeploy/docs/pull/510, which is currently blocked.
> ServerNodeName arg has moved to create-instance

- docs/deployment-examples/custom-scripts/index.md
When I was helping a customer, I realised this is the landing page for custom scripts. Instead of telling the customer all the amazing super powers they get with scripts in Octopus, we told them about the security context and how to debug scripts in an antiquated way.
I've re-authored the page trying to put myself in the shoes of a customer arriving at Octopus for the first time.
> Telling the customer why the should care about custom scripts

- docs/deployment-process/index.md
- docs/deployment-process/operations-runbooks/index.md
This adds some basic documentation for the initial Runbooks feature that we're planning to release early next week (behind a feature toggle).
Decided to list this under the `Deployment Process` section, as this contains a lot of the shared docs and mentions Projects/Variables etc. that are all related to Runbooks. We can move this around once we get more feedback from the early-access customers.
> Introducing Runbooks

- docs/octopus-rest-api/octopus.migrator.exe-command-line/import.md
An automated update of the command line docs for octopus.migrator.exe.
Created by TeamCity project 'Automated Documentation Updates::Update CLI Docs', build 103
> Updating cli docs for octopus.migrator.exe

- docs/deployment-examples/certificates/troubleshooting.md
Add some troubleshooting docs for invalid certificates.
Adding @jburger as someone who's spent a fair bit of time investigating. Does it make sense? Do I have the details right?
Adding @wordlee for word-smithing. Does it read well, is it in the right voice, is it in the right spot?
Latest issue that prompted this:
Relates to https://github.com/OctopusDeploy/Issues/issues/5955
Older related issues:
Relates to https://github.com/OctopusDeploy/Issues/issues/5020
Relates to https://github.com/OctopusDeploy/Issues/issues/5359
Relates to https://github.com/OctopusDeploy/Issues/issues/5337
> Add troubleshooting docs for invalid certificates

- docs/administration/security/octopus-tentacle-communication/index.md
To help customers wanting to add http headers
[This customer](https://octopususergroup.slack.com/archives/C6UGLUWMQ/p1574438557358700) ran into some confusion with it.
> Tweak the tentacle communications page to emphasise TLS not HTTPS

- docs/octopus-rest-api/octo.exe-command-line/create-release.md
Previous wording made it look like when using create-release without specifying --version, it would use whatever the highest NuGet package version was in the project.  As we know, the Release Versioning project setting specifies a specific step in the process and uses that steps package for the version number.  A customer contacted us about the confusion, they expected whatever NuGet package in the process had the highest number, that was the number that got used.
I'm not married to my wording, just trying to clarify the documentation 😄
> Re-wording Basic Examples

- docs/deployment-examples/azure-deployments/deploying-a-package-to-an-azure-cloud-service/index.md
Related to https://github.com/OctopusDeploy/Issues/issues/6111 
We will not be able to fix that issue, as the change would need to happen on Azure Cloud Services. This docs update will inform customer who encounter Timeout Issues or slow re-packaging of a work around, however as this work around disables variable substitution, we're using a warning alert.
> Add a short explanation and workaround warning alert for Azure Cloud Services Timeout issue

- docs/infrastructure/deployment-targets/linux/index.md
The SSH Linux page still contained language that made it sound like SSH was the only option for Linux.
> Updating documentation for Linux

- docs/deployment-examples/azure-deployments/deploying-to-service-fabric/deploying-a-package-to-a-service-fabric-cluster/index.md
This PR adds some information regarding Octopus' stance regarding service fabric issues adds the start of a troubleshooting section and links to a custom SF script to get users out of trouble.
> Add some information on troubleshooting SF

- docs/octopus-cloud/static-ip.md
We're no longer charging customers for a static IP address. This PR explains that there's now a pool of static IPs for everybody and where to find them.
> Update doco for static IPs in the Octopus Cloud

- docs/packaging-applications/build-servers/bitbucket-pipelines/index.md
- docs/shared-content/versions/images/image-version-octo-alpine.include.md
Relates to OctopusDeploy/Issues#4878 and #605
Moving the image version to an include so we can update it without needing to know about any specific usages.
TODO: modify the build/deploy process to update the version in this file when a new image is pushed to docker hub.
> move image version to include

- docs/deployment-patterns/rolling-deployments.md
Add hint to rolling-deployments.md to mention use of Window size with Octopus.Action.MaxParallelism
> Add hint to rolling-deployments.md to mention use of Window size

- docs/octopus-rest-api/octopus-cli/create-release.md
Might want to use very different version numbers for clarity eg 1.0.1 instead 2.0.2
> Typo in version number

- docs/infrastructure/deployment-targets/linux/requirements.md
I've confirmed that ScriptCS/F# work with self contained Calamari
> Corrected the documentation around Self contained Calamari and ScriptCS/F#

- docs/packaging-applications/build-servers/index.md
Added a hint about the ability to push build-information to Octopus before a package exists in the built-in repository.
Requested by user in Community Slack who said they thought it would be useful as a hint :smile:
> Add hint about ability to push build-information before package exists

- docs/infrastructure/deployment-targets/linux/tentacle/index.md
C# and F# scripts work on Linux tentacle, with some additional dependencies.
> Made a note of the new requirements

- docs/octopus-rest-api/octopus.server.exe-command-line/configure.md
- docs/octopus-rest-api/octopus.server.exe-command-line/database.md
- docs/octopus-rest-api/octopus.server.exe-command-line/index.md
- docs/octopus-rest-api/octopus.server.exe-command-line/license.md
- docs/octopus-rest-api/octopus.server.exe-command-line/lost-master-key.md
- docs/octopus-rest-api/octopus.server.exe-command-line/path.md
An automated update of the command line docs for octopus.server.exe version 2020.1.14.
Created by TeamCity project 'Automated Documentation Updates::Update CLI Docs', build 208
> Updating cli docs for octopus.server.exe

- docs/deployment-process/conditions/index.md
This is the docs support for the [Child Run Conditions PR](https://github.com/OctopusDeploy/OctopusDeploy/pull/5718).
Machine-level variable run conditions are now supported, includes basic example/walkthrough.
> Adding machine-level variable-expressions

- docs/administration/authentication/active-directory-authentication/index.md
Our new directory services provider now appears to require a `HTTP` SPN set against the machine, rather than use the service account. This is because we're now using HTTP.sys for the integrated challenge, and it doesn't support user mode authentication. 
This change is intended to support customers experiencing this issue: [internal ticket](https://trello.com/c/62riwP29/3180-unable-to-sign-in-with-domain-account-after-upgrading-to-v2020)
> Added some detail regarding Kerberos

- docs/infrastructure/workers/worker-pools.md
Remove the lies...
" Worker pools are global resources which can't be scoped"
> Worker pool variable link

- docs/projects/project-triggers/automatic-release-creation.md
Re-worked some of the call-outs and links in Auto-release-creation docs
Summary of changes:
- Changed the first callout for build servers at the top from `success` to a `hint`
- Added other build server support in the first callout
- moved warning about ARC support for built-in repo to after the Getting Started section and updated it from `hint` to a `warning`
- Replaced the `success` callout about Azure/TFS packaging to a general **Learn More** section at the bottom with a link to the Guides
- Corrected some links to `automatically creating pre-releases` section referenced in the troubleshooting section
> Quick tidy-up and update of automatic-release-creation

- docs/octopus-concepts/operations-runbooks.md
Search for **runbooks** - example [here](https://octopus.com/docs/search?q=runbooks)
See the results for the octopus-concepts page highlighted below:
This change takes the description from the operation runbooks doc and adds it for the octopus-concepts as well.
> Update runbooks description to be more than just Octopus

- docs/infrastructure/deployment-targets/linux/index.md
Brings the docs up to date with the linux versions we test currently against
> Update tested linux versions to match latest agents

- docs/projects/variables/variable-substitutions.md
A user in community slack raised that the docs were confusing when referring to `empty` being evaluated as `falsy`, so added a warning that variables are treated as Strings, and modified the wording to state an empty **string**.
> Add warning that variable values are evaluated as strings

- redirects.txt
Someone reported this URL was broken: https://octopus.com/docs/deploying-applications/deployment-process/configuration-features
I don't remember where it was linked from.
I think this redirect should fix it. The current url is https://octopus.com/docs/deployment-process/configuration-features
> Add redirect for Configuration Features

- docs/packaging-applications/build-servers/index.md
The pictures needed to be updated as one of them contains "Metadata" which isnt what our current version shows. A user got concerned that they had setup build info correctly since theirs didnt say Metadata. I've taken 3 new screenshots for consistency. I also added a warning that subversion doesnt work for commit messages, only github.
> Update pictures and add warning about Subversion

- docs/octopus-rest-api/octopus.client.md
I think we want to help customers shy away from using the version of Octopus.Client we ship with Octopus Server or Tentacle. Instead, we should recommend they obtain Octopus.Client using the Packages feature.
> Change recommendations for Octopus.Client usage in steps

- docs/octopus-rest-api/octopus.server.exe-command-line/path.md
Added two new path commands.
`telemetry` sets the storage location of temporary files used when collecting telemetry. This should be path shared by all nodes in a cluster.
`clusterShared` sets the root path shared by nodes in a cluster. This is a shorthand way to configure a cluster instead of setting each path individually, previously each of artifacts, built-in repository and task logs would need to be configured.
> Add telemetry and clusterShared path commands

- docs/octopus-rest-api/octopus-cli/index.md
- docs/octopus-rest-api/octopus-cli/run-runbook.md
Adds run-runbook.md and updates the [CLI main page](https://octopus.com/docs/octopus-rest-api/octopus-cli) to add documentation and examples for running runbooks via the cli.
> enh-update: Adds run runbook documentation

- docs/operations-runbooks/runbook-examples/databases/backup-mssql-database.md
- docs/operations-runbooks/runbook-examples/databases/index.md
- docs/operations-runbooks/runbook-examples/index.md
- docs/operations-runbooks/runbook-examples/routine/index.md
- docs/operations-runbooks/runbook-examples/routine/installing-iis.md
- docs/operations-runbooks/runbook-permissions/index.md
- docs/operations-runbooks/runbook-publishing/index.md
- docs/operations-runbooks/runbooks-vs-deployments/index.md
- Add examples index page
- Corrected casing on existing runbook child pages titles
- Removed header from runbooks publishing page
- Added runbook example pages (see below)
- Installing IIS
- Backing up a MSSQL Database
> Add Runbooks examples doco

- docs/security/outbound-requests.md
We're recording new metrics around Structured Configuration Variable usage in 2020.4 - updated the docs to reflect the new outbound metrics with check for update request. 
PR for Structured Config Metrics in Octopus Server: https://github.com/OctopusDeploy/OctopusDeploy/pull/6498
PR for Structured Config Metrics in Octofront: https://github.com/OctopusDeploy/Octofront/pull/2123
> Added Structured Configuration Variable metrics to outbound requests

- docs/shared-content/structured-configuration-variables.include.md
I have a few minor suggestions I hope can simplify wording and improve flow, so I'm raising this as a PR.
There is only one real correction here, which was that the final YAML example didn't contain the `baz`. However, I am suggesting here to adjust the example using the familiar structure from a previous example, because I thought having a property key called `key` might be confusing.
I also would remove "the variables section of your deployment process" because variables don't live under Deployment Process at this point.
I've folded the final sentence about variable substitution syntax into the previous paragraph about that, so that we discuss the basic usage and then the extended syntax.
> Suggested minor improvements to Structured Configuration Variables docs

- docs/octopus-rest-api/octopus-cli/clean-workerpool.md
Added 2 basic examples for `clean-worker` worker pool examples for Octo CLI
> Add clean-worker pool examples for Octo CLI

- docs/projects/variables/variable-filters.md
- docs/projects/variables/variable-substitutions.md
(draft until the changes have been merged to Octostache, and integrated into Calamari)
This PR adds information about four new filters supported in Calamari:
- `YamlSingleQuoteEscape`
- `YamlDoubleQuoteEscape`
- `PropertiesKeyEscape`
- `PropertiesValueEscape`
> Add new filters.

- docs/deployment-process/execution-containers-for-workers/index.md
Updating execution containers page to make it clearer which images can be used, and that they are now available on cloud workers.
> Execution container images and dynamic workers

- docs/security/authentication/active-directory/index.md
The '/' symbol within Document chapters titles are breaking the inpage Targets
> Forward slash breaking in-page links

- docs/octopus-rest-api/octopus.server.exe-command-line/lost-master-key.md
Adding this after the release of 2020.4 where `lost-master-key` command now works as expected
> Add basic example and warning to lost-master-key

- docs/octopus-cloud/index.md
- docs/shared-content/octopus-cloud/octopus-cloud.include.md
No longer references the octopus-server.include file that added the octopus server content.
I removed the shared octopus-cloud content (it was only used in this one place), simplified and rewrote the introduction.
> Removed Octopus Server section

- docs/administration/managing-infrastructure/tentacle-configuration-and-file-storage/index.md
This changed somewhere between 2020.1 and 2020.4 where Calamari used to be installed to `<Tentacle Home>\Calamari`. It's now installed to `<Tentacle Home>\Tools`. Updating docs to reflect this change.
> Update path to Calamari to point to Tools

- docs/deployment-examples/kubernetes-deployments/helm-update/index.md
Adding some documentation around the fact that when using Helm with cloud dynamic workers, it will fall back to executing Helm V2 despite having V3 selected because of the version installed on dynamic workers.  Provided a workaround by suggesting using the Execution Containers feature and letting them know they'd need to change the Worker Image of their Default Worker Pool to something other than Default or Server 2016.
> Adding warning regarding Helm template usage with cloud dynamic workers

- docs/administration/retention-policies/index.md
Included details of build information on the retention policy page.
Information sourced from the BuildInformationCleaner class.
> Update retention policies to include details of build information

- .github/CODEOWNERS
Mark, as discussed, this updates the codeowners file to tag you as the primary codeowner, that way you'll be automatically added to review docs PRs as they come in.
> Updated Codeowner

- docs/shared-content/scripts/register-listening-tentacle-scripts.include.md
Initial script didn't instantiate the $environmentIds var as an array, so it was making stringlists that did not work when registering the tentacle.
> Update register-listening-tentacle powershell

- docs/getting-started/index.md
While working through the getting started guide I noticed that the bash variable substitution example was failing. This is because the variable declaration is not quite right (see [this explanation](https://stackoverflow.com/questions/2268104/command-not-found-error-in-bash-variable-assignment) )
> remove spaces around = in bash example

- docs/security/exposing-octopus/lets-encrypt-integration.md
The updates found in this PR contain documentation updates for the work that has been done to get the Linux Container out of EAP with the removal of Let's Encrypt.
> Let's Encrypt update

- docs/infrastructure/deployment-targets/linux/tentacle/index.md
- docs/infrastructure/deployment-targets/linux/tentacle/quickstart-archive-linux-arm64.include.md
- docs/infrastructure/deployment-targets/linux/tentacle/quickstart-archive-linux-x64.include.md
Dependant upon Server 2020.5 shipping, plus https://github.com/OctopusDeploy/Octofront/pull/2315 being merged
This will add an additional section the same as [this one](https://octopus.com/docs/infrastructure/deployment-targets/linux/tentacle#archive) and change the labels to represent each one correctly.
> Add scripts for installing a linux ARM64 tentacle.

- docs/shared-content/structured-configuration-variables.include.md
This represents changes recently made to fix https://github.com/OctopusDeploy/Issues/issues/6683
> Clarified how the file type for structured configuration variables is determined

- .config/dotnet-tools.json
- .gitignore
- NuGet.Config
- docs/credits.template.md
We recently changed the way we generate licence/credits files and internally test for OSS licence compliance. This has necessitated a change to our `docs` repository with regard to how we generate our `credits.md` file.
This PR includes
- a .NET tool manifest
- a `dotnet` tool to generate the `credits.md` file
- a markdown template file for the credits file
- a `NuGet.config` file to allow downloading the .NET tool from our unauthenticated/public NuGet feed
- a `.gitignore` entry to ignore temporary directories created during generation of `credits.md` in case the cleanup fails.
> Include tools and templates to auto-update credits.md

- docs/support/troubleshooting-access-denied-starting-http-listener.md
Prior to 2021.1.0, we used a manifest to demand administrator permissions on Windows. Now, we log a nice error message instead when we don't have permissions.
Relates to https://github.com/OctopusDeploy/OctopusDeploy/pull/7925
> Create troubleshooting guide for AccessDeniedStartingHttpListener

- docs/installation/octopus-in-container/octopus-tentacle-container.md
https://github.com/OctopusDeploy/Octopus-Docker/blob/master/Tentacle/readme.md
The variable was missing that would allow the containers to be workers. Added it to the list.
> Updating the documentation to show the worker variable

- docs/packaging-applications/build-servers/index.md
I've moved the warning for the VCS types to a more promienent position as many people miss this information which can waste the customer and support team a lot of time.
I've also added a link a short lead up to a blog discussing Manually Pushing Build Information.
> Added and moved some information for clarity

- docs/administration/upgrading/guide/automate-upgrades.md
Not sure where I got `BeginsWith` but it's not a thing :octocat: - Noticed this when I went to actually use this script today to upgrade and it failed here.
> Replace BeginsWith with StartsWith

- docs/security/authentication/active-directory/index.md
- docs/security/authentication/auth-provider-compatibility.md
- docs/security/authentication/authentication-automation-with-octopusdsc.md
- docs/security/authentication/auto-user-creation.md
- docs/security/authentication/azure-ad-authentication.md
- docs/security/authentication/googleapps-authentication.md
- docs/security/authentication/guest-login.md
- docs/security/authentication/index.md
- docs/security/authentication/octopusid-authentication.md
- docs/security/authentication/okta-authentication.md
- docs/security/authentication/troubleshooting-authentication-problems.md
- Added a new compatibility page for the authentication providers
- Updated warning hint blocks to _hopefully_ more accurately describe auth differences between Cloud and Server
- Consolidated a few areas where double hints were present on auth provider pages
- Re-ordered pages to allow compatibility page to be the first child in sub-menu
This change has been deployed to the pre-prod site if you want to visualise the changes
**Could reviewers please check:**
- The matrix for support, and any footnotes for accuracy
- Particularly the External groups section :smile:
> Authentication providers compatibility enhancements

- docs/packaging-applications/package-repositories/docker-registries/octopus-version.md
This PR includes additional details on the new version rules applied to Docker tags,
Not to be merged until 2020.6 has been released.
> Added a section describing the docker versioning rules

- docs/administration/spaces/index.md
- docs/shared-content/administration/disable-default-space.include.md
I was unable to find the section in this page for disabling the default space. Have added an anchor (I think!) to the warning paragraph above the relevant section.
> add anchor for the disable default space

- docs/shared-content/tentacle/tentacle-downloads.include.md
This is a small thing. I hope no one is still using Windows Server 2003, but since it's not officially supported by Tentacle, I think we shouldn't suggest anything here.
> Remove reference to Windows 2003

- docs/octopus-rest-api/tentacle.exe-command-line/agent.md
- docs/octopus-rest-api/tentacle.exe-command-line/configure.md
- docs/octopus-rest-api/tentacle.exe-command-line/delete-instance.md
- docs/octopus-rest-api/tentacle.exe-command-line/deregister-from.md
- docs/octopus-rest-api/tentacle.exe-command-line/deregister-worker.md
- docs/octopus-rest-api/tentacle.exe-command-line/import-certificate.md
- docs/octopus-rest-api/tentacle.exe-command-line/new-certificate.md
- docs/octopus-rest-api/tentacle.exe-command-line/poll-server.md
- docs/octopus-rest-api/tentacle.exe-command-line/polling-proxy.md
- docs/octopus-rest-api/tentacle.exe-command-line/proxy.md
- docs/octopus-rest-api/tentacle.exe-command-line/register-with.md
- docs/octopus-rest-api/tentacle.exe-command-line/register-worker.md
- docs/octopus-rest-api/tentacle.exe-command-line/server-comms.md
- docs/octopus-rest-api/tentacle.exe-command-line/show-configuration.md
- docs/octopus-rest-api/tentacle.exe-command-line/show-thumbprint.md
- docs/octopus-rest-api/tentacle.exe-command-line/update-trust.md
An automated update of the command line docs for tentacle.exe version 6.0.481.
Created by TeamCity project 'Automated Documentation Updates::Update CLI Docs', build 238
> Updating cli docs for tentacle.exe

- docs/administration/managing-infrastructure/subscriptions/index.md
- docs/octopus-rest-api/how-to-create-an-api-key.md
This PR is part of the [API Key Management](https://docs.google.com/document/d/1BwF_RjvOAX0Rc-6JEr3D1w88BJcyqxXuhYr8GPpV5Gc/edit#) pitch.
Add basic documentation around API key expiry. I think the functionality is fairly self-explanatory, so I haven't gone into much detail. Expiry events work pretty much identically to certificate expiry, so that section has largely be copy+pasted.
This feature will be shipping in **2020.6**.
> Document API key expiry

- docs/installation/octopus-in-container/octopus-server-container-linux.md
- docs/installation/octopus-in-container/octopus-server-container-windows.md
- docs/security/authentication/auth-provider-compatibility.md
Adding in text to clarify: 
- Linux container is now fully supported.
- Windows container isn't supported, and probably won't ever be
- Authentication provider update for Linux Container
> Container updates

- docs/installation/octopus-in-container/octopus-tentacle-container.md
Update the tentacle port in the example to point to the default port of the server docker container, instead of 8065.
> Update tentacle containers port

- docs/deployments/kubernetes/deploy-container/index.md
Clean up a few typos and grammatical issues in the documentation.
> Fixes to various typos in the Kubernetes Cluster Step Documentation

- docs/octopus-rest-api/tentacle.exe-command-line/show-configuration.md
As added in https://github.com/OctopusDeploy/OctopusTentacle/pull/283, which shipped in Tentacle 6.0.615.
> Include worker details in Tentacle show-configuration command

- docs/deployments/terraform/plugin-cache/index.md
This PR adds documentation that explains how to use a plugin cache with Terraform when executed from Octopus.
> Added docs on plugin cache

- docs/packaging-applications/create-packages/octopus-cli.md
This is a minor fix to the help command example that is given in the "Create packages with the Octopus CLI" page, the current version doesn't run when pasted into powershell as it includes the path "C:\>"
> Fixes Octo CLI help command example in packaging applications

- docs/installation/octopus-in-container/docker-compose-linux.md
- docs/installation/octopus-in-container/docker-compose-windows.md
- docs/installation/octopus-in-container/octopus-server-container-linux.md
- docs/installation/octopus-in-container/octopus-server-container-windows.md
- docs/installation/octopus-in-container/troubleshooting-octopus-server-in-a-container.md
We have decided to [deprecate support for hosting Octopus Server](https://octopusdeploy.slack.com/archives/C033W4273/p1621221332252800) in a windows container.
> Deprecating Octopus Server windows container images

- docs/deployments/azure/running-azure-powershell/configuring-the-version-of-the-azure-powershell-modules.md
- docs/deployments/azure/running-azure-powershell/index.md
Changes the documentation on Running Azure Powershell scripts to indicate that using the bundled tools is not longer recommended, instead users should use their own version of the Azure Powershell Modules and Azure CLI
> Changes running azure powershell to indicate bundled tools are no longer recommended

- docs/deployments/azure/running-azure-powershell/configuring-the-version-of-the-azure-cli.md
- docs/deployments/azure/running-azure-powershell/configuring-the-version-of-the-azure-powershell-modules.md
- docs/deployments/azure/running-azure-powershell/index.md
This PR makes changes to our Azure Script Step documentation.
The main reason for the changes was to make it very explicit that we do not recommend people use the inbuilt Azure tools, and that we will no longer be updating them.
> Updates our Azure tool guidance

- docs/octopus-rest-api/octopus.migrator.exe-command-line/index.md
The warning explicitly stated that Octopus Migrator wasn't to be used for migrating projects between spaces. Now that Bento is released, I've updated the warning to link to the blog.
> Direct users to Bento

- docs/infrastructure/deployment-targets/windows-targets/requirements/index.md
Windows 2008 and 2008R2 went out of extended support on Jan 14, 2020.
See the [#investigation-dropping-support-for-2008-and-2008r2](https://octopusdeploy.slack.com/archives/C01K8UMMQTX) channel in slack for details.
> Remove 2008 R2 as a supported option

- docs/administration/upgrading/guide/creating-test-instance.md
- docs/shared-content/upgrade/upgrade-download-same-version.include.md
- docs/shared-content/upgrade/upgrade-install-latest-version.include.md
This change adds some additional sections for the creating test instance page within the upgrading octopus guides
It includes: 
- download the latest version for test instance
- and install the latest version for test instance
> Additional sections for the create test instance guide

- docs/infrastructure/deployment-targets/kubernetes-target/index.md
Do we want to call this out in doco since its security based? What are your thoughts?
"To confirm this you can temporarily switch to detection rather than prevention and run the call again."
I think it's a great troubleshooting method but it's a bit dicey to recommend turning off their WAF prevention even temporarily, no?
> Add troubleshooting.

- docs/releases/lifecycles/index.md
When working on a fix for lifecycle auto-deployments to tenants, it was unclear what the expected behavior should be. As it turns out, the behavior actually is listed already in the `Tenants and automatic-environments` hint but it's in the middle of the `Create a new lifecycle` section. I think it makes more sense for the behavior to be outlined in the `Phases` section, along with adding some extra context for the difference between manual vs. auto deployments. There's also an issue with the nested list in the hint which has been fixed.
> Update Lifecycles with more clarity surrounding auto/manual deployments including tenants

- docs/projects/variables/variable-filters.md
To improve discovery and make it clearer where new filters might belong
this splits up the filters into a series of categories. The
filter-specific documentation was moved to sit under its appropriate
category.
> Categorise Octostache Filters

- docs/shared-content/scripts/cancel-queued-deployments-scripts.include.md
Removed the PS c# example because getting it to work with the client with a list object was proving to be very frustrating
> Updating kill tasks to handle pagination

- docs/deployments/azure/cloud-services/index.md
- docs/deployments/azure/deploying-a-package-to-an-azure-web-app/index.md
- docs/deployments/azure/deploying-a-package-to-an-azure-web-app/using-deployment-slots-with-azure-web-apps.md
- docs/deployments/azure/running-azure-powershell/index.md
- docs/deployments/custom-scripts/aws-cli-scripts.md
- docs/deployments/custom-scripts/azure-powershell-scripts.md
- docs/deployments/google-cloud/run-gcloud-script/index.md
We are making an effort to encourage Octopus customers towards using execution containers when executing custom scripts - particularly scripts for cloud providers.
This PR updates all Azure, AWS and GCP documentation that mentions running scripts, and aligns the messaging and content around customers managing their own tooling for their scripts, and encourages them towards using execution containers.
> Encouraging the use of Execution Containers for script steps

- docs/octopus-cloud/migrations.md
Added a general guide on using the export/import feature to migrate to Octopus Cloud
> Updating the migrate to Octopus Cloud guide

- docs/administration/managing-infrastructure/subscriptions/webhook-slack.md
The subscription payload was changed https://github.com/OctopusDeploy/Issues/issues/7069 to make some enum types clearer. The payload on the docs needs to be updated as well to reflect the changes.
> Update subscription payload to reflect enum changes

- docs/infrastructure/deployment-targets/dynamic-infrastructure/index.md
- docs/infrastructure/deployment-targets/dynamic-infrastructure/new-octopustarget.md
- docs/infrastructure/deployment-targets/dynamic-infrastructure/remove-octopustarget.md
- redirects.txt
In August we added functionality to dynamically create targets emitted from step packages.
This PR documents the new functions.
Related changes:
https://github.com/OctopusDeploy/Calamari/pull/785
https://github.com/OctopusDeploy/OctopusDeploy/pull/9774
https://github.com/OctopusDeploy/Calamari/commit/2413e18f6f6fb409f2c58dbe3ada53b339bd199f
> Adds documentation for creating dynamic infrastructure for step package targets

- docs/projects/variables/aws-account-variables.md
Just adding a hint to the page as per the suggestion in the following issue 
resolves OctopusDeploy/ResearchAndDevelopment#110 (internal)
> adding parameter naming hint on AWS accounts variable page

- docs/deployments/aws/ecs/index.md
The ECS step has links for two different deployment failure types. This PR adds documentation that clarifies the meaning behind those error messages.
> Clarification about ECS error messages

- docs/infrastructure/deployment-targets/linux/ssh-requirements.md
Mono support is something that we want to deprecate, but as an interim step for keeping it around we don't want to support Mono < 5.14.0 anymore. This will help us simplify our codebase and CI pipeline for Calamari.
> Update recommended minimum version of Mono to 5.14

- docs/projects/version-control/index.md
Add in links to git providers for users to easily get their personal access token.
> Config as code - links for Git providers access token instructions

- docs/projects/project-triggers/automatic-release-creation.md
Using variables in ARC was added in 2019.3.1, docs haven't been updated to reflect this.
Github Issue: [Issue 4236](https://github.com/OctopusDeploy/Issues/issues/4236).
Code Change and Commit: [Evaluate variables in package names during Auto Release Creation and Scheduled Triggers Commit.](https://github.com/OctopusDeploy/OctopusDeploy/commit/cf79d48cfd512acd086be1a15ba6b426bb98c6e3).
> Removing warnings related to using variables for ARC.

- docs/infrastructure/deployment-targets/linux/index.md
(It does not need to be the user’s default shell.)
> removed the claim about default shell

- docs/projects/export-import/index.md
This was surprising to me when testing this feature and I think deserves mention in the docs.
https://octopusdeploy.slack.com/archives/C033W4273/p1639525456152800
> Note caveat about default lifecycle for Environments export

- docs/installation/octopus-tentacle-container.md
Updates the docs to match the added Tenant options. Also adds docs for Space/MachinePolicy which already existed but weren't listed.
Now shows the latest Tentacle Docker image version (on dev-a):
Relates to https://github.com/OctopusDeploy/Issues/issues/7251
> Update Tentacle container with added env vars

- docs/installation/octopus-tentacle-container.md
A breaking change to the Tentacle Docker image was introduced as a result of fixing https://github.com/OctopusDeploy/OctopusTentacle/issues/322. This PR is to provide a notification to users about the change in the latest version.
> Update Tentacle container docs to warn about breaking change to internal port

- docs/shared-content/scripts/deploy-release-with-prompted-variables-scripts.include.md
Current script does not pass `FormValues` properly. 
API expects UUID of variable as key instead of variable name.
For example: 
```"FormValues": {"8f457792-62f1-d607-2194-cd9846235130": "MyValue"}}```
Currently it is:
```"FormValues": {"MyVariable": "MyValue"}}```
> Fix Golang script example for deployment release with prompted variables

- docs/infrastructure/deployment-targets/dynamic-infrastructure/new-octopustarget.md
The documentation for dynamically creating deployment targets that are authored with step packages (e.g. an AWS ECS cluster) currently contains a link to learn more about step packages which points to the https://github.com/OctopusDeploy/step-api repo. This repo is currently private and so will result in a 404 for any non-Octopus user of the docs. 
This PR removes the link for the moment. There are plans to make the repo public at which time the link could be restored.
> Removes private link to step-api repo from New-OctopusTarget command page

- docs/administration/retention-policies/index.md
The wording in this section I found to be confusing (and possibly even just wrong).
The section says:
> If you happen to have higher versions of packages that have not been released, we will keep them assuming a release will be created.
This is simply not true. I tested this recently:
```
16:07:00   Info     |     Applying retention policies to the built-in package repository.
16:07:00   Verbose  |     Packages uploaded before 12/9/2021 12:07:00 AM +00:00, and not used by any active release, will be deleted.
16:07:00   Info     |     OctopusDeploy.OctoPetShop.Database.1.0.0 was published on 10/22/2021 7:50:27 PM +00:00. It will be kept because the package is used in the following release: Retention Policy Test v0.0.1.
16:07:00   Info     |     OctopusDeploy.OctoPetShop.Database.1.0.1 was …
```
> Clarify/restate how the built-in package repo retention policy works.

- docs/administration/managing-infrastructure/tentacle-configuration-and-file-storage/manually-uninstall-tentacle.md
- docs/infrastructure/deployment-targets/linux/tentacle/index.md
- docs/runbooks/runbook-examples/routine/hardening-ubuntu.md
- docs/runbooks/runbook-examples/routine/hardening-windows.md
- docs/security/hardening-octopus.md
- docs/security/octopus-tentacle-communication/index.md
We had a customer ask about disabling older TLS versions for tentacle, and I thought it'd be good to add this to the docs, under the security/hardening sections.
Since security isn't my forte, could someone confirm it looks ok? :stuck_out_tongue: 
Usual caveats around security have been added:
> Add info on how to disable insecure tls protocols

- docs/deployments/kubernetes/helm-update/index.md
- docs/getting-started/best-practices/worker-configuration.md
- docs/infrastructure/workers/dynamic-worker-pools.md
- docs/projects/steps/execution-containers-for-workers/index.md
Please review changes, and confirm I haven't missed anything. Thanks
> Remove any mention of Win 2016 Dynamic Workers - now deprecated

- docs/administration/retention-policies/index.md
A customer made a good argument for the intuitiveness of inherited retention policies: https://github.com/OctopusDeploy/Issues/issues/7319#issuecomment-1024304810
Since we have now [updated the UI](https://github.com/OctopusDeploy/Issues/issues/7338) to reflect the correct retention behavior, we also want to make it clearer on the _why_ behind retention policies inheriting from previous phases rather than the overall lifecycle policy. Paul provided an [explanation](https://stackoverflow.com/c/octopusdeploy/questions/1312) (internal thread) which I've converted to the docs.
> Add section on inherited retention policies

- docs/projects/variables/variable-templates.md
Current link ends up here:
Maybe the project name just got changed at some point to have a space.
> Add hyphen to project name slug

- docs/deployments/aws/s3/index.md
This PR adds a section to list the output variables created by the `"Upload to AWS S3 Bucket"` step.
This feature is implemented in https://github.com/OctopusDeploy/Calamari/pull/831
> added: Output variables section for upload to AWS s3 step

- docs/infrastructure/deployment-targets/linux/tentacle/index.md
Our Windows installer has a checkbox that will automatically add a firewall rule as part of the Tentacle installation, our Linux script does not (with so many distros, I understand why).  I've added a warning callout so it's readily apparent that they may need to adjust firewall rules.
> Adding warning about firewall rules.

- docs/infrastructure/workers/dynamic-worker-pools.md
This MUST NOT go out before the images have gone live (versions to come).
> Dynamic Workers: add kubectl 1.21.9 and 1.22.6 for Win2019

- docs/deployments/aws/ecs-update-service/index.md
- docs/deployments/aws/ecs/index.md
The Update Amazon ECS Service step works on EC2-backed instances. This removes the documentation directing users that only Fargate clusters are supported.
> Remove Fargate requirement for ECS Update Service step

- docs/projects/version-control/config-as-code-reference.md
Update to the note to make it clear we recommend staying clear of a central deployment repo.
> Clarifying the docs on project locations.

- docs/administration/managing-infrastructure/moving-your-octopus/move-the-octopus-home-folder-and-the-tentacle-home-and-application-folders.md
When moving a tentacle the script wasn't using the $instance variable defined in the config section, so the folder path ended up being hard coded to "InstanceName" instead of the value that was defined in the instance name. This change updates the script so that it will use $instance in the folder paths for $oldHome and $newHome
> Use $instance to define file paths

- docs/releases/lifecycles/index.md
Optional phases don't actually execute auto-deployments https://github.com/OctopusDeploy/Issues/issues/7446. Our docs say they follow the standard rules so we should remove that part and add a note on the actual behaviour.
> Mention optional phases don't do auto-deploy

- docs/octopus-rest-api/octopus.client/getting-started.md
When trying to install Octopus.Client for PowerShell on Windows 2016 the exception below is thrown.
This happens because Microsoft dropped support for TLS 1.1 on their host. I added this step to set TLS 1.2 for the session which fix the issue.
https://stackoverflow.com/questions/55826791/powershell-installing-nuget-says-unable-to-access-internet-but-i-actually-can
https://rnelson0.com/2018/05/17/powershell-in-a-post-tls1-1-world/
```
WARNING: MSG:UnableToDownload «https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409» «»
WARNING: Unable to download the list of available providers. Check your internet connection.
Install-Package : Unable to find package source 'https://www.nuget.org/api/v2'. Use Get-PackageSource to see all available package sources.
At …
```
> Fix Octopus.Client installation for PowerShell on Windows 2016

- docs/administration/spaces/private-space.md
#team-user-onboarding has been working on adding a feature called Private Space, which is now ready to ship. We'd like to include a link in the help sidebar to the docs (a "Learn more" link would appear here under "and learn Octopus"):
In private-space.md, can you let me know if the relative link to the page on Spaces is correct? Should it be absolute instead (`/docs/administration/spaces/index.md`)?
> Add Private Space doc

- docs/infrastructure/deployment-targets/dynamic-infrastructure/new-octopustarget.md
A new version of the ECS cluster target was recently released that changes the way inputs are structured to support additional authentication options, this PR updates the docs for dynamic infrastructure creation to reflect these changes.
> Updates input examples for dynamic creation of ECS Cluster Targets

- docs/infrastructure/deployment-targets/azure/web-app-targets/index.md
This PR updates the Azure Web App discovery documentation to include information about discovering web app slots. It also highlights the fact that the naming structure for discovered web apps has changed since the EAP and that any existing targets discovered will need to be manually cleaned up.
> Adds docs for deployment slot discovery

- docs/infrastructure/workers/dynamic-worker-pools.md
Add more cached versions of worker tools images.
> Add cached worker tools versions

- docs/security/outbound-requests/index.md
A step package public feed was introduced in `2022.1` to support updating existing and creating new steps to be shipped out of band of Server releases. This feed is hosted in Azure and is available on a well-known URL `https://steps-feed.octopus.com`. 
Self-hosted customers may have their Octopus instance behind a firewall and as such may not be able to use the feed without configuring some exceptions. The feed returns some redirects to Azure services as part of servicing requests so multiple exceptions will need to be configured.
This PR adds details to the outbound connections documentation on which URLs Octopus reaches out to. It also moves some existing detail on community step templates into it's own section.
> Adds outbound requests for step package public feed

- docs/infrastructure/deployment-targets/kubernetes-target/index.md
This PR adds documentation for discovery of Kubernetes targets. It only documents Azure Kubernetes Service targets as that is what supported in 2022.2 under an EAP flag.
> Adds kubernetes target discovery docs

- docs/administration/upgrading/guide/upgrading-from-octopus-3.x-to-modern.md
This column wasn't added until 2018.4, so removing the generic include and hard-pasting the contents, sans-project trigger statement.
> Remove SQL reference to ProjectTrigger.IsDisabled

- docs/approvals/service-now/index.md
Update the "Configure ServiceNow" section to include the roles required by the service account to use the integration.
Minor text and formatting changes included
See story [sc-6150](https://app.shortcut.com/octopusdeploy/story/6150/documentation-is-not-clear-about-which-servicenow-role-to-assign)
> Add list of roles required by service account to use integration

- docs/administration/spaces/private-space.md
The Private Space feature has caused a bit of confusion with users that were expecting it to be available for on-premises installations. Adding this note should help them understand that they'd have to switch to Cloud if they want to use the feature.
> Explain that Private Space is a cloud-only feature

- docs/shared-content/scripts/create-and-publish-runbook-scripts.include.md
The powershell script for [Create and publish new runbook snapshot](https://octopus.com/docs/octopus-rest-api/examples/runbooks/create-and-publish-runbook) looks to be using an outdated endpoint. This PR brings the powershell script in line with the other examples from the page.
> Update to powershell script for publishing runbooks

- docs/security/outbound-requests/index.md
We recently updated our amplitude integration to also function for on-prem customers when telemetry has been enabled. As such, behavioural telemetry requests will make its way to `https://telemetry.octopus.com`, which there was no mention of in the docs. This PR simply rectifies this.
> Mention behavioural telemetry as an outbound requests in security section

- docs/approvals/service-now/index.md
Overtime the variable name for manually linking a service now change requestion to a deployment has change in the code base, this PR is to update the documentation to match.
*Note: Image is only missing from the "after" image as the html file was generated locally*
> Update variable name usages to correct name

- docs/shared-content/structured-configuration-variables.include.md
* Explicitly add ampersand (`&`) as a character required to be escaped when replacing text elements in XML documents
* Add reference to the spec for clarity that this is required, not just something we chose to do
This fixes OctopusDeploy/Issues#5907
> Clarify treatment of ampersands in XML Files processed by Structured Variable Replacement

- docs/shared-content/structured-configuration-variables.include.md
PR #1586 added clarification about how special characters are escaped when replacing values into an XML file using the Structured Variables feature.
This PR adds just a bit more "safety net" for customers to help them understand that any XML libraries reading the resulting file will automatically handle un-escpaing the characters.
> More clarification of XML escaping behaviour in Structured Variables

- docs/deployments/aws/ecs-update-service/index.md
- docs/deployments/aws/ecs/index.md
Adds some more information to help users choose between the "deploy an ECS service" step and the "update an ECS service" step.
Context: https://octopusdeploy.slack.com/archives/C27FNL3QW/p1657783176320749
> Additions to ECS docs

- docs/shared-content/octopus-cloud/octopus-cloud-community-plan-instance-limits.include.md
This is no longer enforced due to unexpected behaviour on the instance when enabled.
See https://octopusdeploy.slack.com/archives/C033BH95WRE/p1658971200437169?thread_ts=1658970807.681289&cid=C033BH95WRE
> Remove limited permissions from cloud community limits

- docs/administration/managing-licenses/community/index.md
- docs/shared-content/octopus-cloud/octopus-cloud-community-plan-instance-limits.include.md
- docs/shared-content/octopus-server/octopus-server-community-limits.include.md
We have a link in Octopus https://g.octopushq.com/RestrictedPermissions which redirects to https://octopus.com/start. This isn't very helpful, so this PR adds a section in the docs to link out to.
> Add section on restricted permissions

- docs/installation/octopus-tentacle-container.md
Relates to https://github.com/OctopusDeploy/ResearchAndDevelopment/issues/534
> No more windows docker image for Tentacle

- docs/support/compatibility.md
Package retention on workers https://github.com/OctopusDeploy/Issues/issues/6664 uses a new "feature" of Tentacle which is named mutexes. Older tentacles are still compatible but will wait on retention since the mutex uses a default name on older tentacles.
> Specify Tentacle compatibility for 2022.2

- docs/support/how-to-turn-on-variable-logging-and-export-the-task-log.md
Point 3 was having layout issues on larger res browsers, causing the first part of the line to hop up next to the image.
> Added break above point 3 to avoid layout issues

- docs/installation/octopus-tentacle-container.md
So we do actually want to keep the Windows docker image for Tentacle.. this PR is for re-adding the docs for this. https://github.com/OctopusDeploy/OctopusTentacle/pull/391
> Re-add windows tentacle docker doc

- docs/infrastructure/deployment-targets/linux/tentacle/index.md
- docs/infrastructure/deployment-targets/linux/tentacle/quickstart-fedora.include.md
Tiny improvement to linux tentacle install instructions.
Context: https://octopusdeploy.slack.com/archives/CG9E93KLJ/p1660108499945759
> Ensure we include -y for yum install instructions

- docs/security/users-and-teams/auditing.md
Mismatched naming
Naming in the docs consistent with the Web Portal
> Fixed audit archive wording to match naming in the web portal

- docs/packaging-applications/package-repositories/guides/container-registries/docker-hub.md
Updating the docs to reflect docker [v1 endpoints deprecation ](https://www.docker.com/blog/docker-hub-v1-api-deprecation/#:~:text=Docker%20has%20planned%20to%20deprecate,repositories%20on%20September%205th%2C%202022.)and requirements for authentication to retrieve images and tags.
> Updating docker-hub registry docs to match v2 changes

- docs/deprecations/index.md
As a part of [RFC: Managing deprecations for Octopus Server](https://docs.google.com/document/d/1z6kP9YUPh_GGhrAacQaNtloKq9LnNJ8ARBU-ofWAR2w), we need a place to publish deprecation announcements.
This page will serve as the source of truth for deprecation announcements for Octopus Server.
We will at some point arrange a redirect from octopus.com/deprecations to this page.
> Adds deprecations page

- docs/support/compatibility.md
A fix ([private link](https://github.com/OctopusDeploy/OctopusDeploy/pull/13336)) was added to prevent Tentacles from waiting longer than expected with Octopus 2022.2+. This means we don't need to specify any compatibility issues with this version anymore.
> Revert tentacle compatibility with 2022.2

- .config/dotnet-tools.json
Version 1.0.678 has some fixes to generate credits for the latest OctopusDeploy codebase
> Update creditsfilegenerator to 1.0.678

- docs/packaging-applications/build-servers/github-actions.md
Ran into errors with .NET version when trying to run the example build script (https://octopus.com/docs/packaging-applications/build-servers/github-actions#example.net-core-build) This change will update the version to allow it to build successfully.
> Update .NET version in example script in github-actions.md

- .config/dotnet-tools.json
- .gitignore
Generating credits with the new pnpm frontend workspace results in the pnpm store being committed to git, which is undesirable.
This PR bumps the credits generator to the latest version and adds the pnpm store to be git ignored.
> Ignore pnpm store

- docs/installation/octopus-server-linux-container/docker-compose-linux.md
The current ${USER} variable is incorrectly pulling the system user rather than using the USER value from the .env file. Moving this to a unique environment variable prevents this from happening.
> Updating docker-compose.yml and .env file

- docs/security/users-and-teams/auditing.md
On-prem can now go up to 3650 days for event retention
> Updating event retention maximum days for self-hosted customers

- docs/deployments/kubernetes/helm-update/index.md
Added clarification in how the built-in repository determines what the package id and version are for a helm chart.
> Adding clarification regarding helm charts in built-in repository.

- docs/insights/metrics.md
It [currently](https://octopus.com/docs/insights/metrics) doesn't look good:
> Fixed placement of images in Insights Metrics docs

- docs/approvals/jira-service-management/index.md
- docs/approvals/service-now/index.md
Updating Jira Service Management page to point to `/contact` page, rather than typeform. 
Also updated these callouts to be `hint` rather than `warning`; The warnings looked angry.
> Update JSM request trial method

- docs/installation/octopus-server-linux-container/octopus-in-kubernetes.md
@harrisonmeister 
Have had several customers hit issues with trying to use the entire licence or wrong masterkey, just wanted to make it a little clearer that both need to be base64 encoded
> minor changes to clarify base64 requirement on license and masterkey 

- docs/packaging-applications/build-servers/github-actions.md
This PR contains small updates to the GitHub Actions docs to change action versions and add an example for the build information action.
> Update the GitHub Actions Docs

- docs/packaging-applications/build-servers/github-actions.md
I missed a link to the push build information action in a previous PR.
> Oops, missed a link

- docs/shared-content/versions/images/image-version-install-octopus-cli-action.include.md
This PR fixes the version of the GitHub Actions CLI install action to use just the major semver version.
> Fixed action version

- docs/deployments/patterns/elastic-and-transient-environments/immutable-infrastructure.md
- docs/projects/project-triggers/deployment-target-triggers.md
Some typo fixes.
Validated the following behaviour and confirmed the following is no longer true
```
If the initial deployment of a release was successful but an automatic deployment of that release fails, **Octopus will stop automatically deploying that release**.
```
Auto-deploys still get triggered after an automatic deployment failure for a given release.
[sc-29412]
> Typos and amendments with regard to auto-deploys

- docs/infrastructure/workers/worker-pools.md
As per [this discussion in Octopus' Community slack](https://octopususergroup.slack.com/archives/C6UGLUWMQ/p1669645313275079), the default worker pool for cloud targets could do with some clarification about what targets and what things are covered (e.g., health checks)
> Expand the definition of cloud targets for default worker pool selection

- docs/infrastructure/deployment-targets/kubernetes-target/index.md
* Adds a section for Google Cloud accounts to the existing K8s target auth options, which was missing
* Adds specific information about changes in `kubectl` from v1.26 onward, which may require changes to the customer's execution environment
This is part of the comms for https://github.com/OctopusDeploy/Issues/issues/7621
> Adds information about Google Cloud accounts for GKE

- docs/support/compatibility.md
After the compatibility doc was rolled back the Octopus Server latest version went missing on the compatibility table. This PR brings it back.
> Fixed missing latest version on Octopus Server

- docs/infrastructure/workers/dynamic-worker-pools/ubuntu-1804-end-of-life.md
- docs/notifications/dynamic-workers-ubuntu-1804-deprecation.md
- redirects.txt
This PR adds notification of the end-of-life of Ubuntu 18.04 Dynamic Worker images and the timeline to transition to Ubuntu 22.04 images.
> Adds Dynamic Workers Ubuntu 18.04 end-of-life notification

- docs/infrastructure/deployment-targets/dynamic-infrastructure/azure-cloud-service-target.md
- docs/infrastructure/deployment-targets/dynamic-infrastructure/azure-service-fabric-target.md
- docs/infrastructure/deployment-targets/dynamic-infrastructure/azure-web-app-target.md
- docs/infrastructure/deployment-targets/dynamic-infrastructure/index.md
- docs/infrastructure/deployment-targets/dynamic-infrastructure/kubernetes-target.md
- docs/infrastructure/deployment-targets/dynamic-infrastructure/new-octopustarget.md
- docs/shared-content/infrastructure/create-deployment-targets-hint.include.md
- docs/shared-content/infrastructure/create-deployment-targets-warning.include.md
This PR adds a hint section for docs on creating new deployment targets to let customer understand the need to add a health check step after creating new deployment targets, if these new targets requires package acquisition.
> Add hints for creating deployment targets from scripts

- docs/deprecations/index.md
Extensions will keep working... but only until the end of the year when we start removing/planning to remove the extensibility framework.
This wording suggests things will keep working even after end of this year
> removing the extra wording to avoid confusion

- docs/security/hardening-octopus.md
The tools folder for windows server is located in `C:\Octopus\OctopusServer\Tools` and for tentacles it's `C:\Octopus\Tools`. I noticed the other day we needed to add the changed folder structure for Octopus Server as it's no longer located in the same folder as the tentacles.
> Added the Tools folder for Octopus Server into the Malware Protection for Windows Defender Script

- docs/packaging-applications/build-servers/jenkins/pipeline.md
A comma was missing in the example script which was causing the jenkinsfile to be malformed.
> Comma missing from octopusBuildInformation example

- docs/security/cve/zipbombs-and-octopus-deploy.md
Documents configuration options for self-hosted and Cloud-hosted customers on archive limits.
> Documentation for Archive Limits

- docs/deployments/azure/index.md
- docs/packaging-applications/build-servers/troubleshooting-integrations-with-build-servers.md
We're replacing UserVoice with a new roadmap portal. Two documentation pages have had their links replaced.
> Remove UserVoice links

- docs/security/users-and-teams/auditing/index.md
The link on the event archives was `/api/event/archives` - its not been updated to be 'event**s**', which from testing (and swagger) appeared to be correct.
> Repair events link in archived-audit-events

- docs/installation/octopus-server-linux-container/docker-compose-linux.md
Adding method to trust additional CAs for the docker compose page.
> Adding instructions on how to trust additional CA for docker compose

- docs/installation/octopus-server-linux-container/octopus-in-kubernetes.md
As we enter the Enterprise space, this may come up more often.  I've added instructions on how to configure K8s to use internal or custom certificate authorities so when Octopus Server calls out to resources using internally signed certificates, it doesn't error with an untrusted root ca exception.
> Adding instructions on how to trust additional CA

- docs/infrastructure/deployment-targets/tentacle/index.md
- docs/infrastructure/deployment-targets/tentacle/polling-tentacles-over-port-443.md
- docs/infrastructure/deployment-targets/tentacle/tentacle-communication.md
- docs/infrastructure/deployment-targets/tentacle/windows/index.md
- redirects.txt
Supersedes #1783
This PR adds a new page to guide users when using the new `--server-comms-address` argument added in: https://github.com/OctopusDeploy/OctopusTentacle/pull/440
We're mainly focusing the usage in Octopus Cloud at this stage because self-hosted instances need more server-side configuration work, but we've included some high-level guidance for now.
We've based the new page on https://www.octopus.com/docs/infrastructure/deployment-targets/windows-targets/polling-tentacles-web-sockets
Related Tentacle CLI docs update PR #1833
> Adds documentation for Polling Tentacles over port 443

- docs/projects/variables/variable-substitutions.md
Documentation to accompany the following PRs once they merge:
* https://github.com/OctopusDeploy/Calamari/pull/984
* https://github.com/OctopusDeploy/OctopusDeploy/pull/16369
> Adds documentation for the new `calc` operator in Variable Substitution

- docs/infrastructure/deployment-targets/linux/index.md
After updating the version of OSX used in our build chain, we need to update the version references in our documentation to match.
See https://octopusdeploy.slack.com/archives/C04UP41MCCW
> Updated version number of OSX

- docs/administration/retention-policies/index.md
- docs/security/users-and-teams/auditing/index.md
Adjust the following small things in the public facing documentation for event retention:
Reduce all references to 'event retention coming soon' or 'in v2022.3' to a version that just references the target version. E.g. "Audit Retention functionality was introduced in Octopus 2023.1"
[sc-38724]
> Updated event retention released version

- docs/administration/private-cloud-migration/index.md
This document provides considerations to take into account when migrating an on-premises Octopus instance to a private cloud.
> Document the process of migrating to a private cloud hosting platform

- docs/deployments/kubernetes/deploy-container/index.md
https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/
The reference is probably not real anyway, however we should probably update this just in case.
> Use new registry

- docs/infrastructure/deployment-targets/cloud-target-discovery/index.md
Updates the cloud target removal hint with clarifying information regarding what conditions need to be met before removal.
> Clarifying cloud target removal conditions.

- src/pages/docs/deployments/kubernetes/helm-update/index.md
Based on [this issue](https://github.com/OctopusDeploy/Issues/issues/8132) and [this ticket](https://octopus.zendesk.com/agent/tickets/120752)
> added warning about helm tar.gz package path length

- docs/security/users-and-teams/auditing/index.md
[sc-47076]
Self-hosted customers have reported confusion about why they don't have audit log retention and what the adjustable retention configuration does.
* Removing repeated audit log retention content (eg. when it was introduced, how archived entries can be accessed, retention configurability)
* Reorganized content so all audit log retention content is sitting under the one heading instead of scattered throughout the page
* Clarified when audit log retention is available for Cloud and self hosted customers
* Clarified why audit log retention is configurable prior to retention being available for self hosted customers
> Clarifying audit log retention availability and clean up of audit page

- public/docs/css/main.css
- public/docs/css/vars.css
- src/pages/docs/deployments/kubernetes/kubernetes-object-status/index.md
Supports the icons on the Kubernetes object status page.
> Support icons in Kubernetes post

- src/pages/docs/deprecations/index.md
Adds a deprecation notice for the Create Branch V1 endpoint.
I've also re-formatted the existing deprecation notices so that each deprecation is under it's own heading, making it easier to link to and add additional details.
[sc-49425]
> Add deprecation notice for Create Branch V1

- src/pages/docs/approvals/jira-service-management/index.md
I've added a Jira project type bullet point to the https://octopus.com/docs/approvals/jira-service-management doc based on feedback from Sean Stanway here: https://octopusdeploy.slack.com/archives/C27FNL3QW/p1684744161165749.
If required, I'm happy to edit the wording as I appreciate it could be said differently / better! :-)
> Add Jira project type bullet point

- src/pages/docs/projects/variables/variable-filters.md
Table cells are separated by pipes `|`, so any pipes in the table need to be escaped - even within code blocks in the table.
> Escape table characters

- src/pages/docs/security/authentication/auth-provider-compatibility.md
This one might need reviewing manually on the staging site as there are `nbsp;` to help with the spacing in the table (they might not be needed now thanks to the CSS)
> Harmonise icons for auth provider compatibility page

- src/pages/docs/projects/version-control/unsupported-config-as-code-scenarios.md
Based on [this ticket ](https://help.octopus.com/t/entitynotfoundexception-when-transferring-project-between-servers/29107/9)and [this RND thread](https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1685931595843349)
> changed section of core design decision to warning

- public/docs/css/main.css
- src/pages/docs/security/authentication/auth-provider-compatibility.md
This makes sure the table icons will remain neatly arranged when inline notes are added.
The inline notes are now linked to the explantion.
> Table formatting and notes

- src/pages/docs/administration/upgrading/legacy/upgrading-from-octopus-2.6.5-2018.10lts/index.md
- src/pages/docs/deployments/azure/cloud-services/index.mdx
- src/pages/docs/deployments/azure/deploying-a-package-to-an-azure-web-app/index.md
- src/pages/docs/deployments/azure/deploying-a-package-to-an-azure-web-app/using-deployment-slots-with-azure-web-apps.md
- src/pages/docs/deployments/html-and-javascript-application-deployments.md
- src/pages/docs/deployments/java/deploying-java-applications.md
- src/pages/docs/deployments/windows/virtual-hard-drive-deployments.md
- src/pages/docs/deployments/windows/windows-services.md
- src/pages/docs/infrastructure/accounts/azure/index.md
- src/pages/docs/infrastructure/deployment-targets/tentacle/windows/automating-tentacle-installation.mdx
- src/pages/docs/security/octopus-tentacle-communication/index.md
- src/pages/docs/security/octopus-tentacle-communication/troubleshooting-schannel-and-tls.md
Fragments can't include a `:` character.
They should also be short and ideally all lower, but these are not in scope for this fix.
> Fix invalid fragments (remove :)

- public/docs/css/main.css
From: https://octopusdeploy.slack.com/archives/C04PQ8XJ4CB/p1686716227088579
Make the icons all the same size, rather than relative to the heading size.
> Fix the size of the bookmark icon

- src/pages/docs/tenants/index.md
- src/pages/docs/tenants/tenant-creation/tenanted-deployments.md
- src/pages/docs/tenants/tenant-infrastructure.md
Added several links to tenanted deployments use case page from relevant docs pages. This will help with content discovery and improve our chances of ranking the new page higher in search results.
> Adding links to tenanted deployments use case page

- src/pages/docs/releases/issue-tracking/azure-devops.md
Based on [this rnd slack thread](https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1677792597189299?thread_ts=1677725859.943959&cid=CNHBHV2BX)
> for Azure DevOps we ignore everything if the BuildEnvironment isn't Azure Devops.
Feel free to change wording!
> added warning about azure workitems and other build envs

- src/pages/docs/infrastructure/deployment-targets/tentacle/octopus-tentacle-container.md
- src/pages/docs/infrastructure/workers/worker-tools-versioning-and-caching.md
- src/pages/docs/installation/octopus-server-linux-container/index.mdx
- src/pages/docs/projects/steps/execution-containers-for-workers/index.mdx
The old docs platform had a feature to lookup and replace Docker images with specific versions.
This PR proposes to remove dependence on this feature.
> Removes use of the docker image feature

- src/pages/docs/support/copy-working-directory.md
@steve-fenton-octopus - super minor clarification that it's a project variable not sys env var etc.
[Octopus Community Slack Thread](https://octopususergroup.slack.com/archives/C6UGLUWMQ/p1687312331662429?thread_ts=1687310296.328099&cid=C6UGLUWMQ)
> added location to create variable to copy-workdir page

- src/pages/docs/getting-started/managing-octopus-subscriptions.md
- src/pages/docs/octopus-cloud/index.mdx
Users are having a hard time inviting new users. Along with updates to the invite flow, we need to make updates to the docs. [Slack thread for context](https://octopusdeploy.slack.com/archives/C04NRRR4V8T/p1683815780628359).
> Invite user doc changes

- src/pages/docs/infrastructure/deployment-targets/tentacle/polling-tentacles-over-port-443.md
We've had a customer report ([internal link](https://octopus.zendesk.com/agent/tickets/131548)) that attempting to use the current docs for supporting polling tentacles over port 443 led to some confusion, particularly around trying to use a HTTP reverse proxy for the polling tentacle connection instead of a TCP reverse proxy.
This PR updates the docs to hopefully make the process for this a bit clearer as well as giving some similar examples to the cloud section further up.
> Update self-hosted docs for polling tentacles over port 443

- src/pages/docs/packaging-applications/build-servers/tfs-azure-devops/using-octopus-extension/index.mdx
- Add a warning that we no longer support specifying `latest` as the release version, and the `release_number` output from the create release v6 step should be used instead.
- Update the deploy release v6 step example to show that it's been split into untenanted/tenanted steps
[sc-51793]
> Update Azure DevOps Deploy Release docs

- src/pages/docs/deployments/aws/cloudformation/index.md
- src/pages/docs/deployments/java/error-messages.md
- src/pages/docs/deployments/nginx/configure-octopus-deploy-project.md
- src/pages/docs/deployments/node-js/node-on-linux.md
- src/pages/docs/packaging-applications/create-packages/octopack/octopack-to-include-buildevent-files.md
- src/pages/docs/packaging-applications/create-packages/octopus-cli.md
- src/shared-content/structured-configuration-variables.include.md
This syntax is reserved by the remark / rehype extensions.
The second column should contain "app:port" but this is being converted into "app<port />" due to markdown extensions.
> Fixes display issue with mis-interpreted colons

- public/docs/css/main.css
Because articles don't have a taxonomy, this isn't currently displayed. However, this keeps the CSS in step with the /devops/ site for gradient borders.
> Updated border gradient technique

- src/components/Header.astro
Sets the location to "docs" for the free trial start button so that we can record if someone started a free trial after looking at the docs.
> Set location for free trial start button

- src/pages/docs/deployments/custom-scripts/scripts-in-packages/reference-files-within-a-package.md
The closing tag is missing a `/` character.
> Fix closing tag

- src/pages/docs/support/log-files.md
The Octopus Server logs only `Info` and up to the server log file by default. 
Context: https://octopusdeploy.slack.com/archives/C04JFJXECS1/p1688107961418059?thread_ts=1688105096.747349&cid=C04JFJXECS1
> Logging anything below Info to a file requires a bit more setup.

- src/shared-content/octopus-rest-api/octopus-client-shipped-with-server-and-tentacle.include.md
Bookmarks in markdown should use `{#bookmark-name}`, but understadably we sometimes use `#{bookmark-name}` by accident.
> The # and { are the wrong way around

- src/pages/docs/administration/upgrading/guide/automate-upgrades.mdx
- src/pages/docs/administration/upgrading/index.mdx
- src/shared-content/upgrade/upgrade-high-availability.include.md
Documentation for https://github.com/OctopusDeploy/OctopusDeploy/pull/17683.
[sc-52853]
3 changes:
- [Upgrading Octopus](https://octopus.com/docs/administration/upgrading#upgrading-a-highly-available-octopus-deploy-instance)
- Added a warning message
- All "upgrading a modern version of Octopus" guides, e.g. [Upgrading major releases of Octopus Deploy](https://octopus.com/docs/administration/upgrading/guide/upgrading-major-releases#upgrade-high-availability)
- Added the same message. It's shared content so applies to "upgrading 4.x", "upgrading 3.x", etc
- [How to automate Octopus Deploy upgrades](https://octopus.com/docs/administration/upgrading/guide/automate-upgrades#process)
- Added an additional powershell script for step 7 with retry to handle transient upgrade failures.
> Document db upgrade improvement

- src/pages/docs/packaging-applications/build-servers/build-information/index.md
@steve-fenton-octopus 
https://octopus.com/docs/packaging-applications/build-servers/build-information#using-build-information-in-release-notes-build-info-in-release-notes
> fixed header typo - build-info-in-release-notes

- astro.config.mjs
- package-lock.json
- package.json
- src/components/LastUpdated.astro
- src/pages/docs/octopus-rest-api/octopus-cli/delete-project.md
- src/pages/docs/octopus-rest-api/octopus-cli/disable-project.md
- tsconfig.json
The result of `npm audit fix` on the semver issue.
> Set semver to 6.3.1 due to security issue

- .github/workflows/build-astro.yml
I included the `npm start` in the example in the fix, this is not needed for this repo.
> Action change

- src/pages/docs/octopus-rest-api/cli/octopus-release-deploy.mdx
Internally, some discussion was had about the new go CLI lacking the ability to specify `--version=latest` when deploying a release. This is a feature the old dotnet CLI had.
R&D Perspective: The  "latest" option was deliberately left out of the new CLI, along with other dynamic kinds of features like it.
If someone is using the CLI to do ad-hoc things, then the new CLI has interactive mode to help with this.
- E.g. when deploying a release, the latest version sorts to the top, so if that's what you want you can just hit enter on the prompt.
If someone is using the CLI as part of CI/CD tooling, we deliberately want to be explicit at all points. 
A common workflow is to have a CI system like Github Actions create a release, then follow up and deploy it. 
This happens:
- Job A: Create …
> Add clarifying warning about no "latest" version in deploy release

- src/pages/docs/support/log-files.md
[sc-52877]
As part of https://github.com/OctopusDeploy/OctopusDeploy/pull/19180, we are introducing a new feature to filter Halibut logs in Octopus Server. The server will hide any Halibut logs whose level is lower than the value configured in the new environment variable `OCTOPUS__Logging__Context__Halibut__LogEventLevel`. By default, if there is no value assigned to this environment variable, all logs from Halibut will not appear in Octopus Server.
eg. The environment variable is set to Information, all Halibut logs whose levels are lower than Information level, such as Verbose and Debug, will be filtered out from Octopus Server.
This PR is to update the public doc to reflect this change.
> Change halibut logging documentation

- src/pages/docs/administration/high-availability/configure/octopus-with-active-directory.md
- src/pages/docs/administration/high-availability/configure/octopus-without-active-directory.md
- src/pages/docs/administration/high-availability/design/octopus-for-high-availability-on-azure.mdx
- src/pages/docs/administration/high-availability/design/octopus-for-high-availability-on-gcp.mdx
- src/pages/docs/administration/high-availability/migrate/index.mdx
- src/pages/docs/administration/managing-infrastructure/moving-your-octopus/move-the-database-and-server.md
- src/pages/docs/administration/managing-infrastructure/moving-your-octopus/move-the-server.md
- src/pages/docs/administration/managing-infrastructure/server-configuration-and-file-storage/index.md
- src/pages/docs/administration/private-cloud-migration/index.md
- src/pages/docs/administration/upgrading/guide/automate-upgrades.mdx
- src/pages/docs/administration/upgrading/index.mdx
- src/pages/docs/getting-started/best-practices/configuring-microsoft-dfs-with-octopus-server.md
- src/pages/docs/getting-started/best-practices/installation-guidelines.mdx
- src/pages/docs/installation/octopus-server-linux-container/docker-compose-linux.md
- src/pages/docs/installation/octopus-server-linux-container/index.mdx
- src/pages/docs/installation/octopus-server-linux-container/octopus-in-kubernetes.mdx
- src/pages/docs/octopus-cloud/migrations.md
- src/pages/docs/octopus-rest-api/octopus.server.exe-command-line/path.md
- src/pages/docs/security/exposing-octopus/use-nginx-as-reverse-proxy.md
- src/shared-content/administration/high-availability-shared-storage-overview.include.md
- src/shared-content/administration/moving-octopus-server-folders.include.md
- src/shared-content/administration/octopus-instance-mixed-os-warning.include.md
- src/shared-content/installation/migrate-from-windows-to-linux-container.include.md
- src/shared-content/octopus-cloud/octopus-cloud-community-plan-storage-limits.include.md
- src/shared-content/octopus-cloud/octopus-cloud-storage-limits.include.md
- src/shared-content/upgrade/upgrade-copy-files-for-cloned-instance.include.md
- src/shared-content/upgrade/upgrade-inplace-upgrade.include.md
- src/shared-content/upgrade/upgrade-octopus-backup-folders.include.md
- src/shared-content/upgrade/upgrade-rollback-folders.include.md
[sc-42885]
With audit log retention almost finished, it will be ready for on-prem customers soon (although it missed the 2023.2 boat 😞). 
Let's update the docs!
When looking deeper into this, I found quite a lot of candidate places to update in our docs.
This raised my questions about what should be updated etc.
To start these conversations, this PR was created.
To spark conversation, I found all the places that reference the directories we use (I searched for "artifacts"), and simply updated it to also include event exports.
I'm not saying all these places should be updated. But this highlights all the candidate locations.
Following are the points I wish answered in this PR. Please review these questions and issues, so we can resolve each one.
There are lots of places we reference core …
> EventExports Directory Documentation

- src/pages/docs/tenants/guides/tenants-sharing-machine-targets/assign-tags-to-targets.md
- src/pages/docs/tenants/guides/tenants-sharing-machine-targets/assign-tags-to-tenants.md
- src/pages/docs/tenants/guides/tenants-sharing-machine-targets/creating-the-tenant-tag-set.md
- src/pages/docs/tenants/guides/tenants-sharing-machine-targets/deploying-after-concurrency-tag.md
- src/pages/docs/tenants/guides/tenants-sharing-machine-targets/deploying-before-concurrency-tag.md
- src/pages/docs/tenants/guides/tenants-sharing-machine-targets/setting-the-concurrency-tag.md
The image URLs came up in the test suite. They had a `/images/` part of the path that isn't needed.
I also tested the pages and previous / next buttons. All looks good.
> Fix image urls on new pages

- package.json
- pnpm-lock.yaml
- src/layouts/Default.astro
- src/pages/docs/search.json.ts
- src/pages/docs/sitemap.xml.ts
When using on-page search, for example `CTRL` + `F` the page flow means the whole navigation must be searched before the main content is reached. This changes the page flow to improve the exprience by putting the content first.
Examples use: https://octopus.com/docs/getting-started
Kudos to Lauren and Finnian for pointing out this issue.
cc @laurencagneyoctopus  @FinnianDempsey
> Improve on page search experience

- src/pages/docs/projects/tenants/index.mdx
Fixes the tenant link in the Project tenants page.
> Fix tenant link

- src/components/LastUpdated.astro
Tokens separated by spaces used to be preserved:
{ item.A } { item.B }
^
But since Astro 3 these spaces are stripped, so you need to force it:
{ item.A + ' ' + item.B }
> Astro 3 auto-collapses spaces that we depended on

- package.json
- pnpm-lock.yaml
- public/docs/js/modules/nav-mobile.js
By setting the source navigation's display property, it overrides the CSS. This prevents that.
> Fixes edge case for navigation on mobile

- src/pages/docs/security/hardening-octopus.mdx
The syntax for lists doesn't include an option to us `a. `, `b. `, etc. This may have been a custom extension written for the old docs site.
This list has been updated to use the standard syntax. We can add CSS rules about the numbering system deployed at different levels of nesting if required.
> Fix markdown in MDX file for nested list

- src/pages/docs/projects/variables/system-variables.md
Adds high level documentation for the `Octopus.Deployment.WorkerLeaseCap` variable added in https://github.com/OctopusDeploy/OctopusDeploy/pull/18809.
> document worker lease cap

- public/docs/css/main.css
- src/components/Header.astro
- src/config.ts
- src/pages/docs.md
Adds an interim search icon so a search can be easily triggered from any page.
Also fixes stacking contexts on desktop and mobile (i.e. skiplinks, navigation, fixed header).
> Interim search icon

- .github/workflows/branch-validation.yml
- src/pages/docs/packaging-applications/package-repositories/guides/container-registries/proget-container-registry.md
- src/pages/docs/packaging-applications/package-repositories/guides/maven-repositories/artifactory-maven-feed.md
- src/pages/docs/packaging-applications/package-repositories/guides/maven-repositories/proget-maven-feed.md
- src/pages/docs/packaging-applications/package-repositories/guides/nuget-repositories/proget-nuget-feed.md
Fixes image paths in ProGet articles.
Notes:
I couldn't find a matching image for the following figure, which has been removed. Please add the image if this needs to be shown.
src\pages\docs\packaging-applications\package-repositories\guides\maven-repositories\proget-maven-feed.md
```
Enter a name for your Feed, eg: ProGet-Docker, then click **Create Feed**
:::figure
:::
```
> Fix image paths

- .github/workflows/build-astro.yml
There's a step `Push a package to Octopus Deploy 🐙` which is now optional.
For forks that can't do that step, it's nice to be able to access the zips: https://github.com/jsoref/OctopusDeploy-docs/actions/runs/6394199002
> Allow people to download microsite

- src/pages/docs/infrastructure/workers/dynamic-worker-pools.md
[sc-59991]
We are changing the default worker pool on Octopus Cloud from `Windows (default)` to `Ubuntu (default)`. This PR updates the implied default by changing the examples in the docs to emphasise `Ubuntu`.
This actual change will only affect new customers who sign up from the cut-over date (TBC). We will add a note about the cut-over date in a [follow up task](https://app.shortcut.com/octopusdeploy/story/61174/add-cutover-date-to-public-documentation).
Changes required before merging:
> Change Dynamic Worker defaults to Linux

- package.json
- pnpm-lock.yaml
Fixes a published CVE: https://fluidattacks.com/advisories/swift/
We don't use this feature of zod, but let's update it to remove the risk.
> Patch for zod

- public/docs/css/main.css
> Fix stacking for headers.

- src/pages/docs/security/outbound-requests/telemetry.md
Previously, this page was brittle because it tried to describe every data element, making it harder to change telemetry, resulting in this page becoming out of date.
The detailed list isn't really needed any more because:
1. Customers can download a preview of the request to see what is being sent.
2. We have our GDPR page which describes our stance on data privacy and our compliance.
> Simplifies the telemetry request doc page

- src/pages/docs/projects/variables/variable-substitutions.mdx
The calc variable substitution has been updated such that if a variable appears on the lhs of a calc divide or subtraction operation - they can be wrapped in braces such that the parse can determine if the "/" or "-" is part of the variable, or the operation being performed.
This has necessitated an update to the docs to explain how to best to make use of this solution.
Don't _love_ the code block `{...}` in the warning section, but couldn't _quickly_ work out how to escape the braces!
> Update calc description to describe wrapping variables in { }

- public/docs/css/vars.css
Responding to a warning in Edge, which may be caused by path confusion.
> Make font path relative to root.

- dictionary-octopus.txt
- src/pages/docs/getting-started/managing-octopus-subscriptions.md
We've had a few confused customers come through who are unsure about how to manage access control for their instance located in Control Center V2.
Most of the time they are really close but have either set it up access in the wrong control center version or not accepted the invite link that's emailed to them to complete the process.
[Current docs](https://octopus.com/docs/getting-started/managing-octopus-subscriptions#access-control)
> Add clarification to access control in control center

- README.md
- cspell.json
The credits file is auto-generated and includes many author names. It's better to exclude it from spellcheck.
> Removes the credits file (lots of names in there) from spellcheck.

- package.json
If all the changes found in the branch are excluded from checking, it raises an error.
This change supresses errors caused by zero files in the list to check.
> Allows zero-file checks to pass.

- .github/CODEOWNERS
- README.md
- src/pages/index.md
The first couple of examples added to the non-visible index page.
CODEOWNERS is now owned.
Astro tips added to README to help public contributors.
> Follow up from the docs call

- dictionary-octopus.txt
- src/pages/docs/getting-started/best-practices/installation-guidelines.mdx
In previous versions of Octopus Server, permissions changes wouldn't appear on all nodes in a HA setup instantly, due to caches not being invalidated. This resulted in customers experiencing permission errors depending on which node answered their request. To avoid this, it was recommended to use load balancer "sticky sessions", which would ensure a user always talked to the same node.
The cache invalidation issue no longer exists, and has not for at least a year. Thus, the use of sticky sessions to avoid it is not required.
Using sticky sessions also carries other risks. If the node a user is "stuck" to experiences heavy load they may not be able to talk to the API at all.
Remove the advice to use sticky sessions.
> Remove sticky sessions advice

- package.json
- pnpm-lock.yaml
- public/docs/js/modules/youtube.js
This resolves the issue with YT videos that aren't on their own line being expanded.
```markdown
[This video will auto-embed.](https://www.youtube.com/watch?v=FjPO1k0Y-xA)
This video won't [as it is accompanied by text nodes](https://www.youtube.com/watch?v=FjPO1k0Y-xA)
[The full stop is outside the link, so this won't embed](https://www.youtube.com/watch?v=FjPO1k0Y-xA).
```
> Updates accelerator.

- src/pages/docs/octopus-rest-api/openid-connect/index.md
- src/pages/docs/octopus-rest-api/openid-connect/other-issuers.md
Docs for using OpenID Connect with the Octopus API were added in #2009. There were a couple of sections that were empty or had todos on them 😳:
- Validation of identity tokens
- Details of an error response to a token exchange request.
This PR fills those in. It also changes some of the "getting started" intro paragraphs to be a bit clearer.
> Adds docs on validation of oidc tokens and error response

- src/pages/docs/deployments/kubernetes/index.md
Adding a link to the K8s use case page. I've added it to what is essentially the K8s overview page in Docs which I think gives us license to add a link to a 'marketing' page. 
This docs page is also the first Octopus page that appears in search when someone searches for deployments to kubernetes, so I want to try and speed up the new page being recognised by search engines and also pass some of the authority from the docs page to the use case page.
> Add link to K8s use case page

- dictionary-octopus.txt
- src/pages/docs/infrastructure/deployment-targets/tentacle/linux/index.mdx
I found a broken link and this PR fixes that and what looks like a erroneous update to the systemd header for linux tentacle
> Fix linux tentacle pre-req link and systemd header

- src/pages/docs/platform-engineering/forking-git-repos.md
This PR adds a new section to the platform engineering docs describing how to fork repos before deploying a CaC enabled downstream project.
> Add a section describing how to fork repos

- package.json
- pnpm-lock.yaml
- public/docs/js/search.js
A small search scoring change to boost shallow results vs deeply nested results.
This may help to boost the landing pages for a search like "packages", where the Packages landing page is currently in position 4.
> Bonus score for shallow results

- dictionary-octopus.txt
- src/pages/docs/platform-engineering/secret-variables.md
There are some special considerations to take into account when defining secret variables in upstream projects. This PR adds a page to the documentation explaining how to define sensitive variables.
> Add documentation n structuring secrets in upstream projects

- cspell.json
- package.json
- pnpm-lock.yaml
- public/docs/js/search.js
- src/pages/report/oldest-content.astro
Changes the scoring system to surface less nested pages, as these are often the better results - especially for single-word searches, like "runbooks".
> Updated search

- dictionary-octopus.txt
- src/pages/docs/security/authentication/active-directory/index.md
Tidy up of Active Directory page.
1. Remove fragments not linked internally or through oc.to short links
2. Fix fragments that are used (lower case, word-separated, and readable)
3. A couple of bold items changed to headings
4. General markdown layout improvements
5. New terms added to the dictionary for NETBIOS and setspn
6. Example domains and usernames improved readability
No fragement domains for /docs/security/authentication/active-directory in short.io:
> Tidy up AD page.

- dictionary-octopus.txt
- src/pages/docs/tenants/tenant-creation/connecting-projects.md
- src/pages/docs/tenants/tenant-creation/index.mdx
- src/pages/docs/tenants/tenant-creation/tenanted-deployments.md
- src/pages/docs/tenants/tenant-deployment-faq.md
- src/pages/docs/tenants/tenant-infrastructure.md
- src/pages/docs/tenants/tenant-lifecycles.md
- src/pages/docs/tenants/tenant-roles-and-security.md
- src/pages/docs/tenants/tenant-tags.md
- src/pages/docs/tenants/tenant-types.md
- src/pages/docs/tenants/tenant-variables.mdx
The following pages are being updated in this PR:
- https://octopus.com/docs/tenants/tenant-creation
- https://octopus.com/docs/tenants/tenant-creation/connecting-projects
- https://octopus.com/docs/tenants/tenant-creation/tenanted-deployments
- https://octopus.com/docs/tenants/tenant-deployment-faq
- https://octopus.com/docs/tenants/tenant-infrastructure
- https://octopus.com/docs/tenants/tenant-lifecycles
- https://octopus.com/docs/tenants/tenant-roles-and-security
- https://octopus.com/docs/tenants/tenant-tags **This one has the largest content changes**
- https://octopus.com/docs/tenants/tenant-types
- https://octopus.com/docs/tenants/tenant-variables
The main goal is to align the pages with the suggested Octopus writing style, so this means:
- Removing unnecessary capitalizations
- …
> Docs cleanup of tenants section

- src/shared-content/scripts/run-runbook-scripts.include.md
In files we update that flag the spelling for API-YOURAPIKEY we are using the less redundant API-YOUR-KEY
> Resolves spelling issue in API key placeholder

- dictionary-octopus.txt
- src/pages/docs/infrastructure/deployment-targets/linux/ssh-requirements.md
Use of `>` adjusted to be code block instead
> edited format of PATH line

- dictionary-octopus.txt
- src/pages/docs/deployments/kubernetes/helm-update/index.md
[sc-66477]
This PR adds a warning message about a known limitation with the Helm `--atomic` flag and its interaction with Octopus's step cancellation mechanism. Octopus sends a SIGKILL to terminate processes when they are cancelled, and this results in the Helm process not being able to perform an automatic rollback. This can happen when either:
1. The user clicks on the cancel button during the deployment
2. The deployment times out (before the Helm `--timeout` limit is reached)
> Add warning message about known Helm upgrade limitations

- src/pages/docs/octopus-rest-api/openid-connect/github-actions.md
- src/pages/docs/octopus-rest-api/openid-connect/index.md
- src/pages/docs/octopus-rest-api/openid-connect/other-issuers.md
This PR makes some small improvements to the docs for using OpenID Connect to access the Octopus API based on some recent feedback.
- Some users have been tripped up when setting the `id-token` permissions on a job: other existing implicit permissions now need to be explicitly set. We have a callout for this but have found that this can be skimmed over and users will reach for the example which didn't explain this well. The examples now have comments highlighting the explicitly required permissions.
- A callout has been added that OIDC is used for machine-to-machine connections, not for user authentication, with a link to the authentication providers docs. 
- A callout has been added that the subject on an OIDC identity doesn't support wildcards at the moment.
> Small improvements to OIDC docs based on recent feedback

- package.json
- pnpm-lock.yaml
- public/docs/js/search.js
- src/pages/docs/search.json.ts
If you search for chained words, commonly found in code blocks, you'll expect to find results.
For example, `Octopus.Release.Channel.Name` is a chunk of code that appears on [Release versioning](https://octopus.com/docs/releases/release-versioning) page. You'd expect to find that page if you searched for "Octopus.Release.Channel.Name".
> Handles chained terms in search

- dictionary-octopus.txt
- src/pages/docs/packaging-applications/package-repositories/built-in-repository/index.md
[sc-69469](https://app.shortcut.com/octopusdeploy/story/69469)
The **Show Examples** button has been removed and replaced with content in the help sidebar
> updated description of where examples for package push live

- README.md
- astro.config.mjs
- dictionary-octopus.txt
- public/docs/css/main.css
Not yet actively used, but in the pipeline. Hence the page itself is still in light mode.
> Code block update for light/dark modes

- dictionary-octopus.txt
- src/pages/docs/security/users-and-teams/external-groups-and-roles.md
Small tweak to external groups and users page. Added a note to point people to the auth provider compatibility page. Myself and a partner were confused by our external auth support.
> Small tweak to external groups and users page to improve clarity.

- public/docs/css/main.css
When you use a keyboard, the skiplinks should be visible on focus.
1. Navigate to the page
2. Hit tab
3. The skip to... should appear
> Makes skip links visible on focus

- public/docs/css/main.css
Border was without unit `rem` I missed that somehow so that's a quick fix to that.
> Image typo fix

- src/pages/docs/octopus-rest-api/octopus-cli/index.mdx
Adding deprecation notice to appear in page title and side navigation.
> Adding 'Deprecated' tag to title of Octo CLI

- src/pages/docs/infrastructure/deployment-targets/tentacle/linux/index.mdx
Fixes a broken external link to Microsoft documentation and brings it up to date with ".NET" now being the name for "the thing that runs on Windows and Linux".
> Change link and reword as ".NET" rather than ".NET Core".

- src/pages/docs/projects/variables/tenant-variables.mdx
The pipes weren't escaped which led to incorrect table content.
> Fix pipes not being escaped and simplify intro text

- src/pages/docs/infrastructure/workers/dynamic-worker-pools.md
[sc-48553]
In response to [Dynamic Workers for 'deploy' running out of disk space](https://app.shortcut.com/octopusdeploy/story/48553/workers-running-out-of-disk-space-regularly), this PR publicly documents the available disk space when Dynamic Workers are provisioned.
> Document available Dynamic Worker disk space

- src/pages/docs/octopus-rest-api/openid-connect/github-actions.md
- src/pages/docs/octopus-rest-api/openid-connect/index.md
- src/pages/docs/octopus-rest-api/openid-connect/other-issuers.md
This PR updates the OIDC docs to include the following:
- Support for using wildcard characters which was released in `2024.1`
- A section on how to use the Octopus CLI with OIDC
> Add subject wildcard and CLI usage to OIDC docs

- .github/CODEOWNERS
team-user-onboarding name in github has been update to team-product-growth.
> Update Codeowners from team-user-onboarding to team-product-growth

- src/pages/docs/infrastructure/deployment-targets/index.mdx
- src/shared-content/infrastructure/target-roles.include.md
[sc-75742]
This PR renames target roles to target tags on the Deployment targets page.
> Rename target roles to target tags on the Deployment targets page

- src/pages/docs/deprecations/index.md
The Azure Resource Manager powershell module was deprecated by microsoft in 2021 - however it is still being used/available for use in OctopusDeploy.
If users are using the module, we will show them a warning asap - use of the module will be (soft) disabled in 2024.3, and fully removed for 2024.4.
Section appears:
> Add AzureRM to deprecations

- src/pages/docs/tenants/guides/tenants-sharing-machine-targets/setting-the-concurrency-tag.md
Currently set to `#{Project.Environment.Id}`, changing to `#{Octopus.Environment.Id}`
> Change #{Project} to #{Octopus} for environment ID

- src/pages/docs/deployments/kubernetes/server-side-apply/index.md
We want to be more specific than just saying "Octopus supports Server-Side Apply for all of our Kubernetes steps" because some people might expect to see it in the Helm step or kubectl script step which don't have it.
> Explicitly list the steps that support Server-Side Apply

- src/pages/docs/octopus-cloud/disaster-recovery.md
We don't currently have a good way to comprehensively export data from a Cloud instance.
For Octonauts, this is being discussed internally [here](https://octopusdeploy.slack.com/archives/C01EG659GHK/p1713855979631789).
[sc-76512]
> Remove section on exporting data from Octopus Cloud

- dictionary-octopus.txt
- src/pages/docs/infrastructure/deployment-targets/kubernetes/kubernetes-agent/storage/index.md
[sc-76947]
We need to get this page in before release since the installation dialog references it.
Local render - are too many words formatted as code?
> Add storage options for Kubernetes agent

- dictionary-octopus.txt
- src/pages/docs/infrastructure/deployment-targets/kubernetes/kubernetes-agent/permissions/index.md
[[sc-76944]](https://app.shortcut.com/octopusdeploy/story/76944/documentation-permissions)
> Add permissions page for Kubernetes Agent

- src/shared-content/tentacle/configure-ssh-connection-target.include.md
- src/shared-content/tentacle/configure-ssh-connection-worker.include.md
- Both SHA256 and MD5 fingerprints are supported
- Simplify the script for getting the MD5 fingerprint
- Include a script for getting the SHA256 fingerprint
> Update SSH target docs to use SHA256 fingerprints

- dictionary-octopus.txt
- src/pages/docs/security/octopus-tentacle-communication/regenerate-certificates-with-octopus-server-and-tentacle.md
Adding a warning to the regenerate tentacle communication certificate page to prevent people following those directions when attempting to update the SSL certificate. The new warning will point them to the appropriate documentation section.
> Add warning to regenerate certificate page

- src/pages/docs/releases/creating-a-release.md
See screenshot - code snippet is displaying on prod. The content from the imported segment has already been added to the page directly so it is no longer needed anyway.
> Removing import instruction

- src/pages/docs/administration/copilot/index.md
Added some links that were missed due to an automerge in a [previous PR](https://github.com/OctopusDeploy/docs/pull/2275).
> Fixed links in Copilot docs

- src/pages/docs/infrastructure/deployment-targets/kubernetes/kubernetes-agent/storage.md
OpenShift does not support privileged containers by default and when enabled, there are issues with file access. Adding a warning to the storage page indicating people should use a custom storage class.
Shortcut story: [sc-77491]
> Add Kubernetes Agent OpenShift storage warning

- public/docs/css/main.css
- public/docs/css/vars.css
Example: https://octopus.com/docs/packaging-applications/create-packages/octopack/troubleshooting-octopack
> Update code blocks to switch on the new data-theme.

- src/pages/docs/administration/copilot/index.md
These settings essentially make a docs page accessible by URL only:
```
navSearch: false
navSitemap: false
navMenu: false
robots: noindex, follow
```
> Hide the page so only people with the url can read the docs

- src/pages/docs/infrastructure/deployment-targets/kubernetes/kubernetes-agent/index.md
A customer reported this, so let's add a small callout
> Add NFS CSI driver troubleshooting note

- src/pages/docs/deprecations/index.md
Posting a notice in our documentation as part of the deprecation plan for bundled tools [[internal link](https://docs.google.com/document/d/1qZYRIjmSjJceVase-WMTvTcUIj6umBkqBt8wBLLSBQ8/edit)]
[sc-74658]
> Add deprecation notice for bundled tools

- src/pages/docs/infrastructure/deployment-targets/kubernetes/kubernetes-api/index.md
the warning was backwards.. the Deployment Process Worker Pool will override the Deployment Target Worker Pool not the other way around.
Testing:
Deployment Target Worker Pool - Local Ubuntu
Deployment Process Worker Pool - Hosted Ubuntu 
Task Logs indicate Deployment Process Worker Pool - Hosted Ubuntu  was used:
> fixed k8s worker pool warning

- src/pages/docs/infrastructure/deployment-targets/kubernetes/kubernetes-agent/index.md
Changed to a table so when we version to `2.*.*` we can show the supported versions over time
Shortcut story: [sc-73874]
> Change Kubernetes agent version requirements to a matrix

- src/pages/docs/security/index.md
:wave: Corrected some out of date information regarding accessing pen. test reports, including links to our trust centre and additional context regarding our certifications.
> Corrected some out of date security information

- src/pages/docs/installation/octopus-server-linux-container/docker-compose-linux.md
The example project name in the guide is `Octopus` (used as `docker compose --project-name Octopus up -d`), except docker throws an error, because, quoting the Docker docs, "Project names must contain only lowercase letters, decimal digits, dashes, and underscores, and must begin with a lowercase letter or decimal digit."
See docs here: https://docs.docker.com/compose/project-name/#set-a-project-name 
Before:
After:
> Fix invalid project casing in "Octopus Server Container with Docker Compose" guide

- src/pages/docs/administration/copilot/index.md
GitHub has naming conventions that describe how to refer to the copilot extension. This PR updates the documentation to follow those conventions.
> Update Octopus extension for GitHub Copilot docs with Github naming conventions

- .github/workflows/branch-validation.yml
- .github/workflows/build-astro.yml
- cspell.json
This is a pre-requisite for the branch protection rule fix.
> Give the branch validation and deployment pipeline steps clear names

- src/pages/docs/infrastructure/deployment-targets/kubernetes/kubernetes-agent/troubleshooting.md
One main way the agent installation can fail is with a timeout. This can be caused by a number of different things but there are a few things that are likely to be common causes.
I've updated the documentation to list several common causes to help users identify the problem in their case. I've also added another command that gets the logs for the tentacle pod as this will most likely help them to identify the issue.
> Add troubleshooting info for when the Agent install command times out

- src/pages/docs/administration/copilot/index.md
The modification date was before the publishing date.
> Fixing a typo in the modification date field

- .npmrc
Instead of faulting out, just warn users when their PNPM version is incorrect. This is especially useful if you're ahead of the specified version.
> Just warn for PNPM mismatch

- src/pages/docs/administration/copilot/index.md
This PR adds instructions on using the Copilot extension with on-premises instances.
> Added instructions on how to expose an on-premises Octopus instance

- dictionary-octopus.txt
- src/pages/docs/projects/built-in-step-templates/manual-intervention-and-approvals.md
Included a small paragraph to mention the "Needs Approval" tab on the task page for managing deployment pending manual intervention.
> Mention the "Needs Approval" tab for manual intervention.

- src/pages/docs/administration/migrate-spaces-with-octoterra/index.md
This PR adds instructions on how to effectively convert a CaC project back to a regular project. It also has a few small line edits.
> Note how to convert a CaC project back in the octoterra migration docs

- src/pages/docs/infrastructure/deployment-targets/kubernetes/kubernetes-agent/ha-cluster-support.md
I realised that we don't have a section for 2024.2 users as we only talk about the UI option for installation. I've added the 2024.2 section to show how users would update the helm command to add HA support to their agent.
> Add a 2024.2 section for HA Cluster support

- src/pages/docs/packaging-applications/build-servers/github-actions.md
Warning wording taken from GHA marketplace listing for build info: https://github.com/marketplace/actions/push-build-information-to-octopus-deploy
> updated github actions to include warning about commits in build info

- src/pages/docs/infrastructure/accounts/openid-connect.md
> Update the default subject keys used in healthchecks for oidc accounts

- src/pages/docs/packaging-applications/package-repositories/docker-registries/index.md
See https://github.com/OctopusDeploy/Issues/issues/8156
I've collapsed the "problem" dialogue into the known limitations sections. It doesn't appear to require a callout, I don't know what customers can do about it.
> Add gitlab auth to know docker limitatons

- src/pages/docs/infrastructure/deployment-targets/kubernetes/kubernetes-agent/index.md
The `Agent tooling` section wasn't clear that the agent does not use execution containers for all k8s steps _past_ a certain version
> Tweak agent tooling to be clearer

- src/pages/docs/infrastructure/deployment-targets/linux/index.md
Updates the list of Linux distributions we run Tentacle integration tests against.
The MacOS version was left unchanged as the version could not be determined. However, we also only run unit tests in this environment.
[SC-85714]
> Update Linux versions tested against

- src/pages/docs/getting-started/managing-octopus-subscriptions.md
Updates `managing-octopus-subscriptions` to reflect trials now being created in Control Center V2 (CCV2) instead of V1. Also other minor adjustments to reflect updated CCV2 UI.
[sc-83461]
> Update subscription management docs to reflect CCV2 trials

- src/pages/docs/octopus-cloud/static-ip.md
Update our Static IP docs to use the correct terminology. We don't use the built-in worker in Octopus Cloud at all.
> Correct information about DW IP addresses.

- src/pages/docs/kubernetes/tutorials/first-kubernetes-deployment.md
Some of the new sections under `/Kubernetes` don't have overview pages; but the section heading needs an `index.md` page for the title + position metadata. So we ended up making the first page in the section the index page.
But, that changes the page URL to be that of the section, not the page:
`/Kubernetes/tutorials/first-kubernetes-deployment.md` -> `/Kubernetes/tutorials/index.md`
URL is now `/docs/kubernetes/tutorials`
But, we want to keep using the _correct_ link in our emails and other places, so they still work if we later decide to implement an overview page.
> Add redirect to fix broken link from overview page

- src/pages/docs/administration/migrate-spaces-with-octoterra/index.md
The docs had a malformed link which has been fixed.
> Fixed a malformed link in the octoterra docs

- src/pages/docs/octopus-rest-api/cli/octopus-release-create.mdx
When testing creating releases for maven packages I ran into an issue where the default version was being used, not the specified version. It turns out the Step name should be the first section of the `{packageOrStep}:{package-ref-name}:{version}` format, not the package ref name. e.g.
`octopus release create --project "Maven Script" --package "Run a Script:begin_beginai:1.1.1" --space "Another One" --no-prompt verbose`
> Update octopus create release docs

- src/pages/docs/projects/export-import/index.mdx
Added warning around version support for bento migrations.
Due to the nature of GA being 1 version behind Cloud, migration from cloud to self hosted is not practically supported.
> added version warning for bento migrations

- src/pages/docs/kubernetes/targets/kubernetes-agent/index.md
Make it clearer that it's the public key of the root organization CA certificate
> Minor language cleanup for custom Octopus Server certificates with K8s Agent

- src/pages/docs/tasks/prioritize-tasks.md
Remove mention of the feature being in v2024.2
> Remove octopus version from lifecycle priority docs

- src/pages/docs/octopus-rest-api/octopus-cli/create-release.md
The `--git-resource` parameter is new. Can only be merged _after_ https://github.com/OctopusDeploy/cli/pull/392 has been merged and released
Shortcut story: [sc-69100]
> Update octopus-cli create release with new parameter

- src/pages/docs/octopus-rest-api/openid-connect/other-issuers.md
- Moved version information to the bottom of the page
- Updated an image linked to by this doc in [a previous PR](https://github.com/OctopusDeploy/docs/pull/2488)
> Update OIDC Other Issuers doc

- src/pages/docs/octopus-rest-api/openid-connect/github-actions.md
- src/pages/docs/octopus-rest-api/openid-connect/index.md
- src/pages/docs/octopus-rest-api/openid-connect/other-issuers.md
This PR adds the `openid` icon to the Open ID Connect pages.
> Add icons for Open ID Connect pages

- dictionary-octopus.txt
- src/pages/docs/projects/version-control/ocl-file-format.md
This PR adds a code icon to the OCL syntax, no other changes are needed in terms of updated screenshots.
> Add icon to OCL syntax page

- src/pages/docs/projects/version-control/moving-version-control.md
This PR adds an icon to the Moving Version Control page
> Add icon to moving version control page

- src/pages/docs/packaging-applications/build-servers/tfs-azure-devops/using-octopus-extension/install-octopus-cli-capability.md
- src/pages/docs/packaging-applications/create-packages/octopus-cli.md
There are old links to the downloads page on octopus.com which is an out of date page and a source of confusion for customers.
Fix these links to direct users to the github releases page for that same cli tool (the deprecated one).
> Change cli link to github releases page.

- src/pages/docs/projects/version-control/unsupported-config-as-code-scenarios.md
This PR includes some small updates to the unsupported config-as-code scenarios to indicate that non-sensitive variables are now supported for config-as-code projects.
> Update unsupported config-as-code scenarios

- src/pages/docs/kubernetes/targets/kubernetes-agent/troubleshooting.md
Customers on older versions of the agent, but newer versions of Octopus Server may run into this issue, so adding some troubleshooting
Shortcut story: [sc-93127]
> Add Kubernetes agent health check troubleshooting

- src/pages/docs/kubernetes/targets/kubernetes-agent/troubleshooting.md
Missed a `#` to make it consistent with the `V1` heading
> Set correct heading level

- public/docs/css/main.css
There was an issue with Github icon being pushed to the side.
Task: https://octopus-deploy-team.monday.com/boards/7162465638/pulses/7435936809
Fixed:
> Header icons fix

- src/pages/docs/packaging-applications/build-servers/codefresh-pipelines.md
> Add doco for deploy a release cf step

- .github/CODEOWNERS
Reviewing CloudPT ownership, I found:
- a couple of pages that better belong with Modern Deployments and Backend Foundations Team
- Dynamic Worker pages should be owned by CloudPT
[sc-82146]
> Update Cloud Platform Team ownership

- src/pages/docs/kubernetes/targets/kubernetes-agent/index.md
- src/pages/docs/kubernetes/targets/kubernetes-agent/troubleshooting/sha1-certificate-incompatibility.md
- Fixed the markdown code for rendering the table
- PR also includes an unrelated small hyperlink adjustment
> Fix the formatting in the Kubernetes Agent version requirements table

- .github/CODEOWNERS
Discussed with RobE and NickJ, moving CODEOWNERSHIP of database deployments for docs to Modern Deployments (MD).
https://octopusdeploy.slack.com/archives/C04F5HY8JPJ/p1726800624405499?thread_ts=1726788822.771049&cid=C04F5HY8JPJ
> Updating ownership of database deployments to MD

- src/pages/docs/kubernetes/targets/kubernetes-agent/images.md
Adds a new page under the Kubernetes agent that lists all the default images, where they and the source code are hosted and also details their purpose.
> Add new page listing Kubernetes agent container images

- src/pages/docs/security/authentication/azure-ad-authentication.mdx
Add a new troubleshooting section for EntraID users with 200+ security groups as this requires specific configuration of the app registration in Azure that may be missing.
[sc-93371]
> chore(docs): Add troubleshooting details for users with 200+ security groups

- src/pages/docs/octopus-cloud/maintenance-window.md
- src/pages/docs/octopus-cloud/migrations.md
- src/pages/docs/octopus-cloud/permissions.md
- src/pages/docs/octopus-cloud/static-ip.md
- src/pages/docs/octopus-cloud/task-cap.md
Minor touchups as part of #project-docs-refresh
[sc-82146]
> Octopus Cloud small improvements

- src/pages/docs/kubernetes/targets/kubernetes-agent/index.md
- src/shared-content/tentacle/configure-k8s-worker.include.md
Adding warning callout explaining how to avoid Kubernetes agent & Kubernetes worker naming clashes.
> Add warning for Kubernetes agent naming

- src/pages/docs/infrastructure/workers/kubernetes-worker/cluster-configuration.md
Support have requested that our support email not be displayed on our docs - and we should rather reference the support page.
The only potential concern is the font/layout of the footer of the table - it MAY get confused with the following paragraph.
The page now appears:
> Remove support emails from k8s docs

- src/pages/docs/packaging-applications/build-servers/github-actions.md
This change is intended to simplify the documentation for our GitHub Actions. [See the existing doc in full here.](https://octopus.com/docs/packaging-applications/build-servers/github-actions)
What's changed here?
- Moved the most fundamental info to the top of the doc. (I.e. what are Octopus Actions and how do I use them?)
- Removed a lot of general info on GitHub Actions and replaced it with links to GitHub's own docs.
- Removed instructions for using each Octopus Action as this info is duplicated in the docs of the individual actions. Instead, I've listed all available Octopus Actions in one place and provided links for more information. 
- Replaced the existing example with a simpler workflow modelling a common use case - i.e. logging in with OICD, creating a Release, then deploying …
> Update GitHub Actions Docs

- src/shared-content/scripts/upload-artifact-to-deployment-scripts.include.md
The script to upload an artifact to an existing deployment prepends extra headers in the file content when uploading to Octopus.
This PR updates the script to use a byte stream instead of streaming as multipart form data. This ensures that the header content is not added to the artifact.
Fixes https://github.com/OctopusDeploy/docs/issues/2399
Tested using [artifact.csv](https://github.com/user-attachments/files/17427805/artifact.csv)
Running the original script and downloading the artifact from Octopus:
Running the new script and downloading the artifact from Octopus:
> fix: update upload artifact to deployment script to use byte stream

- public/docs/css/main.css
Fixes the follow up issue on #2129
> Code font is too small for readability

- src/pages/docs/administration/data/backup-and-restore.md
- src/pages/docs/projects/variables/sensitive-variables.md
- src/pages/docs/security/data-encryption.md
Documentation changes to accompany https://github.com/OctopusDeploy/OctopusDeploy/pull/28689, which changed our default master key length to 256 bits.
> Updates references to AES to 256 bit where appropriate

- src/pages/docs/infrastructure/deployment-targets/tentacle/windows/index.mdx
The downloadable link has been updated to remove the version as well as include checksum files
> Update Calamari.Legacy links

- src/pages/docs/kubernetes/steps/helm.md
- src/pages/docs/kubernetes/steps/kubernetes-ingress.md
- src/pages/docs/kubernetes/steps/kubernetes-resources.md
- src/pages/docs/kubernetes/steps/kubernetes-service.md
- src/pages/docs/kubernetes/steps/kustomize.mdx
- src/pages/docs/kubernetes/steps/yaml.md
Callouts are missing line breaks. This PR should fix this formatting issue.
> Fixing formatting issues

- src/pages/docs/kubernetes/targets/kubernetes-agent/index.md
It turns out we had upgraded the SDK used by the agent a few versions ago (by @OctopusDeploy/team-server-at-scale as part of the .NET 8 work).
As a result, the supported versions of the agent change to 1.28 -> 1.31
> Update actually supported Kubernetes versions for the agent

- src/pages/docs/octopus-cloud/frequently-asked-questions.md
- src/pages/docs/octopus-cloud/maintenance-window.md
- src/pages/docs/octopus-cloud/uptime-slo.md
Improves, defines and clarifies content about Octopus Cloud uptime SLO. 
Adds a table of track record data.
Add recent & accurate data points to maintenance windows page.
Link FAQ to uptime track record.
> Add Cloud uptime track record; update SLO; update references.

- src/pages/docs/infrastructure/deployment-targets/linux/index.md
We no longer support Fedora 39. So it should be removed from our docs.
> Remove Fedora 39 from our supported platforms list

- src/pages/docs/octopus-cloud/uptime-slo.md
Add uptime metrics for November 2024. Tweak clarity of what 95th percentile means.
> Update uptime track record for November 2024

- src/pages/docs/projects/built-in-step-templates/manual-intervention-and-approvals.md
[It was observed](https://octopusdeploy.slack.com/archives/C04GAH78491/p1733096479465069) that our docs do not make it clear what should happen when a manual intervention is aborted.
What Octopus Deploy does, is that it treats that like any other failure, and then proceeds to evaluate the run conditions of subsequent steps. So if a step is setup to run on a previous step failing, then it will run.
This PR aims to help specify this behaviour so it is more clear to our customers on how manual interventions should behave.
We added a sample to the docs on the Octostache variable that you could use to control steps with variable conditions.
This sample was tested, and here are the results:
The configured variable:
A deployment where we aborted the manual intervention:
A deployment where we …
> Adding more information about the behaviour of manual interventions

- .vscode/extensions.json
- .vscode/settings.json
- README.md
- cspell.json
Initially only in-editor suggestions.
Recommends our styles for lists, spacing around elements, heading outlines, and so on.
> Markdown linting

- src/shared-content/scripts/find-variable-usage-scripts.include.md
Updates the variable usage script to check for variables in CaC projects.
[sc-93621]
Script output:
```
Looking for usages of variable named name in space: 'Default'
Checking project 'First Project'
Checking project 'Second Project'
Checking project 'Third Project'
Checking project 'Generic OIDC'
Checking project 'GCP OIDC'
Checking project 'CAC project'
Found 9 results:
Project           : First Project
VariableSet       : 
MatchType         : Step
Context           : Deploy a Release
Property          : Actions
AdditionalContext : 
Link              : http://localhost:8065/app#/Spaces-1/projects/Projects-296/deployments/process/steps?actionId=291aaf52-a4d7-45ce-b48a-a5921118e5f5
Project           : Generic OIDC
VariableSet       : 
MatchType         : Step
Context           : HashiCorp …
```
> Update variable usage script to handle CaC projects

- src/pages/docs/kubernetes/targets/kubernetes-agent/index.md
- src/pages/docs/kubernetes/targets/kubernetes-agent/supported-versions-policy.md
Adds a short explainer to describe when we make updates to the supported versions of Kubernetes.
Unsure if we want to direct people to talk to support for something that we'll get to eventually - but I think it's a nice touch.
> Kubernetes agent supported versions policy

- src/pages/docs/octopus-rest-api/octopus-cli/create-release.md
Was erroneously added in #2479.
This was not added to the deprecated CLI, just the new CLI which has it's docs auto-updated
> Remove --git-resource from deprecated CLI create release command

- src/pages/docs/kubernetes/targets/kubernetes-agent/index.md
Tentacle is currently using `v14` of the Kubernetes C# SDK, which targets `1.30`
> Fix Kubernetes agent cluster versions

- src/pages/docs/deployments/custom-scripts/run-a-script-step.md
Updated run a script step package reference variables to include specific about docker image variables
[SC-81855]
> Package reference docker image variables

- dictionary-octopus.txt
- src/pages/docs/octopus-rest-api/octopus-cli/create-release.md
- src/pages/docs/octopus-rest-api/octopus-cli/deploy-release.md
https://github.com/OctopusDeploy/docs/commit/84533e1c25d86cfe9d305c9e24b25051e91b60ba#diff-3ff5010e27082aad4cc3916a5118a1a06022f9f70d5334e22fcc05c70ff5b5d0R27 changed the word `timespan` to `time span` in the CLI output.
CLI output:
> Deploy-release.md: revert accidental change to CLI output

- src/pages/docs/kubernetes/targets/kubernetes-agent/index.md
The supported Kubernetes server versions have been updated due to an upgrade of the Kubernetes client library in the agent.
[sc-99802]
> Update the supported Kubernetes server versions for the Kubernetes agent

- src/pages/docs/deployments/terraform/index.md
Removed stale tested versions and reworded to remove the need to explicitly define this every time the testing range changes.
> Remove dated TF version references

- dictionary-octopus.txt
- src/pages/docs/infrastructure/deployment-targets/linux/ssh-deployments.md
The ssh-deployments file states that calamari is used such that packages can be acquired - either from server or from nuget.
This has been updated to reference (and link to) all possible external repos.
> Tweak ssh-deployments to reference all external feeds, not just nuget

- src/pages/docs/infrastructure/accounts/google-cloud/index.md
The existing [OpenId Connect](https://octopus.com/docs/infrastructure/accounts/openid-connect#deployments-and-runbooks) page covers most of the relevant details for Oidc accounts. Let me know if you think additional details related to the generic oidc account would fit here let me know. This change includes the CLI commands and call out on the gcloud account that generic OpenId Connect accounts can be used instead.
> Update docs to include Generic Oidc Changes

- dictionary-octopus.txt
- src/pages/docs/packaging-applications/package-repositories/nuget-feeds.md
We recently added a feature configuration that enables/disables users from creating/modifying external NuGet Feeds with SMB or local file paths.
This PR updates the docs to point users in the right direction.
> Update NuGet Feed docs with feature configuration

- src/pages/docs/projects/variables/system-variables.md
- src/pages/docs/projects/version-control/config-as-code-reference.md
- src/pages/docs/projects/version-control/converting/index.md
- src/pages/docs/projects/version-control/index.md
- src/pages/docs/runbooks/config-as-code-runbooks.md
- src/pages/docs/runbooks/runbook-publishing/index.md
- src/pages/docs/runbooks/runbooks-vs-deployments/index.md
- src/pages/docs/runbooks/scheduled-runbook-trigger/index.md
This adds a general info page for CaC Runbooks, mostly outlining the differences between CaC Runbooks and the old Runbooks. 
It also updates the other places in the docs where we talk about only having CaC for deployments. 
✅ Accuracy 
✅ Clarity
✅ Formatting - I found the capitalisation of 'runbooks' a bit tricky to get right. [See the Octopus grammar rules here!](https://www.octopus.design/932c0f1a9/p/457bc4-grammar-rules/t/page-457bc4-58679287-0)
> Update docs for CaC Runbooks

- src/pages/docs/security/index.md
There shouldn't be an "s" at the end of "providers" in this sentence:
> If you don't want to use an external identity providers, you can let Octopus Deploy securely manage your usernames and passwords for you.
> Fix typo on Security page

- public/docs/css/main.css
> Cater for multi-line link labels in right sidenav

- src/pages/docs/infrastructure/deployment-targets/linux/ssh-requirements.md
- src/shared-content/tentacle/configure-ssh-connection-target.include.md
Mono has been deprecated and unavailable as an option for SSH targets for the past year. https://github.com/OctopusDeploy/OctopusDeploy/pull/21590
> Update SSH Target Requirements: Remove Deprecated Mono Mentions

- src/pages/docs/infrastructure/deployment-targets/linux/index.md
Based on internal discussions, Octopus will begin considering the linux supported platforms to be based on the .NET (or other) framework support that is available (in addition to the underlying platform vendors support)
> Update linux requirements

- src/shared-content/scripts/export-step-templates-scripts.include.md
The example script needed to be tweaked slightly to fix the export of the templates
> Fixed up the example script

- src/pages/docs/infrastructure/deployment-targets/linux/index.md
Remove alpine from supported list as we currently dont build for `linux-musl-x64`
> Remove alpine from support

- src/pages/docs/projects/built-in-step-templates/email-notifications.md
[sc-103432]
Update the SMTP Configuration section to include Google SMTP OAuth 2.0 credentials with information on how to set up Google's Workload Identity Federation.
> Update smtp configuration to include google oauth information

- src/pages/docs/projects/community-step-templates.md
"...you should check the community step template."
"...you should check the community step template library."
> Fix awkward end of sentence

- src/pages/docs/platform-engineering/enterprise-patterns.md
The enterprise patterns page has been updated to note that separate instances can be used for PCI compliance
> Noted that separate instances can be used for PCI compliance

- src/pages/docs/administration/retention-policies/index.mdx
Add documentation around the retention policy for server tasks
https://github.com/OctopusDeploy/OctopusDeploy/pull/29622
https://github.com/OctopusDeploy/Issues/issues/9296
[sc-88660]
> Add task retention policy documentation

- src/pages/docs/octopus-cloud/uptime-slo.md
Updated stats. Gave sentence about fewer than 9 minutes of total downtime per month a little more prominence.
> Update Uptime SLO stats for March 2025

- src/pages/docs/kubernetes/live-object-status/troubleshooting/index.md
- src/pages/docs/kubernetes/targets/kubernetes-agent/kubernetes-monitor.md
Small updates to troubleshooting and a link to how the Kubernetes monitor is upgraded.
There is a shortened link tied to the `Connection ID was not found` heading, before merging this needs to be updated too.
> Update KLOS docs

- src/pages/docs/kubernetes/targets/kubernetes-agent/upgrading.md
In v2024.4 we included support for automatic major upgrades for Kubernetes agents, updating the docs to reflect this.
> Update Kubernetes agent upgrade doc

- src/pages/docs/installation/index.mdx
- src/pages/docs/installation/sql-database/index.mdx
Octopus previously used a link to download SQL express server provided by [an external blog post](https://www.hanselman.com/blog/download-sql-server-express). However the link has since broken.
[[sc-108133]](https://app.shortcut.com/octopusdeploy/story/108133/sev-3-the-url-we-use-for-sql-express-in-the-server-install-does-not-work-requested-by-james-cornford)
A new link was created using an oct.to url which links directly to the micosoft SQL express download page.
Fixes https://github.com/OctopusDeploy/Issues/issues/9352
http://downloadsqlserverexpress.com/
https://oc.to/downloadsqlserverexpress
> replace broken link to SQL express in docs

- src/pages/docs/octopus-rest-api/how-to-create-an-api-key.md
API keys no longer have no default expiry date. Default is now set to 180 days.
Custom links caused spellcheck to fail. Remove `{#HowtocreateanAPIkey-CreatinganAPIkey}` and `{#HowtocreateanAPIkey-DisablingAPIKeyCreation}`. Links for sections are now auto generated.
[sc-110043]
> Update default API Key expiry information

- src/pages/docs/projects/variables/system-variables.md
This adds variable definitions already available in our docs here - https://octopus.com/docs/deployments/custom-scripts/run-a-script-step#docker-image-package-variables
> Add Docker image package variables

- .markdownlint.json
- .vscode/settings.json
- src/pages/docs/administration/spaces/index.mdx
Tested on a page to ensure the config is picked up.
This should help markdown lint rules be applied regardless of IDE.
> Move markdown lint config into json file

- src/pages/docs/kubernetes/targets/kubernetes-agent/troubleshooting/index.md
Adds a new troubleshooting section for the exec error for the Kubernetes agent/worker
> Add troubleshooting section for script pod exec error

- src/pages/docs/kubernetes/live-object-status/index.md
- src/pages/docs/kubernetes/live-object-status/troubleshooting/index.md
We recently added a new configuration property to projects for Kubernetes Live Object Status
> Add docs for new KLOS project configuration

- src/pages/docs/kubernetes/live-object-status/troubleshooting/index.md
Troubleshooting tip for when a Kubernetes monitor is completely lost from Octopus server's knowledge
> Another troubleshooting entry for the Kubernetes monitor

- src/pages/docs/infrastructure/accounts/openid-connect.md
The feeds anchor had a space init making it so the markdown didn't interpret it as an achor.
> Minor update to fix Markdown anchor for feeds

- src/pages/docs/infrastructure/deployment-targets/tentacle/windows/index.mdx
Adding information about the .NET dependency options for Windows Tentacle, and how that behaves with upgrades. 
See this [slack discussion](https://octopusdeploy.slack.com/archives/C033W4273/p1747213334996659?thread_ts=1746008230.532929&cid=C033W4273) for more context on why (only accessible internally to Octopus folks).
> Windows Tentacle publishing and upgrade options

- src/pages/docs/deployments/custom-scripts/logging-messages-in-scripts.md
Add docs for new service message `##octopus[stderr-output]`
[sc-77584]
Related to https://github.com/OctopusDeploy/OctopusDeploy/pull/33735
> Add stderr-output to docs

- src/pages/docs/releases/issue-tracking/jira.md
Update docs to include parsing branch names for jira work items.
[sc-112190]
> Add branch name parsing to jira integration docs

- src/pages/docs/deprecations/index.md
Adds a call out for the default C# scripting library migration to dotnet-script from scriptcs in 2025.2. This gives options to switch back to ScriptCS but calls out it's hard EOL in 2025.3
> Add scriptCS to 2025.2 planned deprecations

- src/pages/docs/kubernetes/live-object-status/troubleshooting/index.md
Adding an anchor link to existing docs on troubleshooting KLOS. Will be using this anchor for a short link.
> Add anchor link to Installation section in Kubernetes Live Object Status troubleshooting

- src/pages/docs/packaging-applications/create-packages/octopus-cli.md
Given we are using the new CLI now, these docs need to be refreshed to be up to date with the latest CLI.
> Updated deprecated Octopus CLI commands

- src/pages/docs/octopus-cloud/dynamic-worker.md
Make it more explicit that customers can lease one VM of each type, and can do so concurrently.
> Update dynamic worker docs

- src/pages/docs/projects/built-in-step-templates/email-notifications.md
[sc-118085]
Update microsoft docs link and ensure `SMTP.SendAsApp` permission specifically called out.
> Callout SMTP.SendAsApp in Microsoft SMTP OAuth docs

- src/pages/docs/administration/reporting/report-on-deployments-using-excel.md
- src/pages/docs/deployments/azure/service-fabric/packaging.md
- src/pages/docs/deployments/dotnet/netcore-webapp.md
- src/pages/docs/deployments/nginx/create-and-push-asp.net-core-project.md
- src/pages/docs/deployments/patterns/elastic-and-transient-environments/immutable-infrastructure.md
- src/pages/docs/deployments/patterns/elastic-and-transient-environments/keeping-deployment-targets-up-to-date.md
- src/pages/docs/packaging-applications/package-repositories/built-in-repository/index.md
- src/pages/docs/projects/variables/prompted-variables.md
- src/pages/docs/projects/version-control/creating-release-from-a-build-server-plug-in.mdx
- src/pages/docs/releases/creating-a-release.md
- src/pages/docs/tenants/tenant-tags.md
The old Octo Command Line tool is deprecated. The documentation still refers to the old CLI in a few areas, which may be confusing for users.
This PR updates the documentation to remove references to the old CLI.
[sc-118974]
Updated sections
- Data export
- Deployments - packaging
- Deployments - auto deploy overrides
- Creating releases
- Build server integrations
- Try running locally and check
- Grammar and spelling
> Update cli commands

- src/pages/docs/octopus-rest-api/examples/bulk-operations/index.md
Adding a couple of missing links as per [this request](https://octopusdeploy.slack.com/archives/C03UDS16R6G/p1758692606463149)
> Adding missing links

- src/pages/docs/deprecations/index.md
Following our blog post on [Removing support for SHA-1 certificates in Octopus Tentacles
](https://octopus.com/blog/removing-sha1-tentacles) and the now closed issue on [Removing support on Linux self-hosted and Cloud for SHA-1 certificates in Octopus Tentacles](https://github.com/OctopusDeploy/Issues/issues/9508), we're adding a section to the deprecations page for the appropriate release.
This follows an internal support thread from an earlier discussion with Simon: https://octopusdeploy.slack.com/archives/C08AH85QTN3/p1754783324066279?thread_ts=1752220740.422009&cid=C08AH85QTN3
> Adding deprecations notice for SHA1 Tentacle changes to 2025.3 release

- src/pages/docs/argo-cd/resources/index.md
- src/pages/docs/argo-cd/steps/update-application-image-tags.md
- src/pages/docs/argo-cd/steps/update-application-manifests.md
Added to the supported-use cases, and also as a warning to the 2 step pages.
> ArgoCD: Add warnings to indicate github alone is supported
