OctopusDeploy/docs

- docs/how-to/how-to-turn-on-variable-logging-and-export-the-task-log.md
The formatting had the image in between the two sentences.
> Added a line before and after bottom image

- docs/administration/upgrading/upgrading-from-octopus-3.x.md
Formatting had images beside text instead of beneath text.
> Added lines between steps and images

- docs/administration/upgrading/upgrading-from-octopus-3.x.md
Fixed link to MSI installer - the image was in the link, and messed with the formatting
Fixed sentence to be bold - "When should I upgrade to Tentacle 3.1?"
> Fixed additional formatting

- docs/guides/elastic-and-transient-environments/cleaning-up-environments.md
Images in step 4 & 6 were inline with the text.
> Format update

- docs/deploying-applications/deploying-to-azure/deploying-a-package-to-an-azure-web-app/index.md
Detailing options to use Zip or checksum file comparison method to accomplish deployment of only changed files.
> Added info about timestamps/checksum

- docs/how-to/get-the-raw-output-from-a-task.md
Step 2 text formatted inline with the image from step 1
> Moved step 2 text below first image

- docs/guides/azure-deployments/creating-an-azure-account/creating-an-azure-service-principal-account.md
Added a brief note on how to get the tenant ID without having to go to the legacy AD portal
> Added easier way to get Tenant ID

- docs/installation/installing-tentacles/azure-virtual-machines/via-an-arm-template.md
Someone has accidentally added a duplicate of the dependsOn node. They both had exactly the same data.
> Removed duplicate dependsOn property

- docs/deploying-applications/variables/sensitive-variables.md
heads up for ##{ -> #{ issue that can be encountered
> variable substitution works for senstive variables

- docs/api-and-integration/octo.exe-command-line/creating-releases.md
> fix for #18 clarifications on octo exe step version options

- CONTRIBUTING.md
- voice-tone.md
> First draft of voice tone

- docs/administration/authentication-providers/admin-user.include.md
- docs/administration/authentication-providers/azure-ad-authentication.md
- docs/administration/authentication-providers/googleapps-authentication.md
Added info so people setting up a new instance without using Server Manager know to run admin command
> added info about the admin command for OIDC setup

- docs/api-and-integration/octopus.server.exe-command-line/configure.md
As it was missing `xFrameOptionAllowFrom`, but also a lot more.
> Update Octopus.Server.exe configure args

- docs/api-and-integration/octo.exe-command-line/creating-releases.md
Related to https://github.com/OctopusDeploy/Issues/issues/3056
> Release notes syntax support

- docs/deploying-applications/artifacts.md
new_otopusartifact -> new_octopusartifact
> Fixed spelling error

- docs/administration/subscriptions_troubleshooting.partial.md
- docs/administration/subscriptions_webhooks_[3.12,).partial.md
Subscription email and webhook troubleshooting information
> Subscription email and webhook troubleshooting information

- docs/deploying-applications/Deploying-Mobile-Applications.md
Under `deploying applications` new documentation with info on deploying a mobile app.
> New documentation Deploying-Mobile-Application

- docs/deploying-applications/variables/system-variables.md
🌵 🌵 🌵  **This is waiting for the `3.14.15` release, will merge once that has been released** 🌵 🌵 🌵
> Add new output variables from an Azure Cloud Service deployment

- docs/api-and-integration/octopus.server.exe-command-line/export-certificate.md
- docs/api-and-integration/octopus.server.exe-command-line/index.md
- docs/api-and-integration/octopus.server.exe-command-line/new-certificate.md
- docs/api-and-integration/octopus.server.exe-command-line/regenerate-certificate.md
- docs/api-and-integration/tentacle.exe-command-line/index.md
- docs/api-and-integration/tentacle.exe-command-line/index_list-instances-command_[3.12,).partial.md
- docs/api-and-integration/tentacle.exe-command-line/new-certificate.md
Related to OctopusDeploy/Issues#3574
Related to OctopusDeploy/OctopusTentacle#10
> Add docs for new certificate commands

- docs/deploying-applications/deploying-to-azure/deploying-a-package-to-an-azure-web-app/using-deployment-slots-with-azure-web-apps.md
- Update Azure RM Remove-AzureRmWebAppSlot to use -ErrorAction Continue
- Update Azure RM staging slot swap to use Switch-AzureRmWebAppSlot
> Update Azure Web App deployment slots docs

- docs/how-to/move-the-octopus-home-folder-and-the-tentacle-home-and-application-folders.md
Hi Guys
I was running move tentacle script but it didn't copy any of the sub folders of home folder. I have added -Recurse switch for copy-item command.
> Copy home folder including sub folders

- docs/reference/troubleshooting-aws-transport-error.md
Added stub page for AWS Transport troubleshooting information
> AWS_TLS Troubleshooting stub

- docs/packaging-applications/versioning-in-octopus-deploy.md
Minor phrasing changes and spelling/grammar changes
> Minor versioning page updates

- docs/deploying-applications/docker-containers/registries/index.md
Fixed Ocotpus typo. Merge whenever
> Typo correction

- docs/key-concepts/environments/machine-policies.md
Closes OctopusDeploy/Issues#3730
> Add info about agent level variables in custom health check scripts

- docs/support/record-a-memory-trace.md
The points 3 and 4 in section 'Get a snapshot from your running Octopus Server' might be merged in signe step:
`dotmemory.exe get-snapshot Octopus.Server`
> A bit of simplification of getting a snapshot

- docs/infrastructure/azure/creating-an-azure-account/creating-an-azure-service-principal-account.md
The Azure Powershell module has been updated to only accept SecureString for passwords with some cmdlets.
> Updated some scripts to use SecureString rather than string for passwords

- docs/infrastructure/windows-targets/index.md
- docs/infrastructure/windows-targets/legacy-requirements.md
- docs/infrastructure/windows-targets/requirements.md
- docs/installation/index.md
Moved the tentacle requirements out of the main procedure with both latest and legacy versions
> Infrastructure cleanup

- docs/deploying-applications/terraform-deployments/apply-terraform/index.md
Added some examples for accessing terraform output variables after discussion with customer https://help.octopus.com/t/removing-quotes-from-json-variables/20074/2
> Terraform variable outputs

- docs/packaging-applications/supported-packages.md
Added a warning around multi part file  extensions and pre-release naming
> .tar.gz warnings

- docs/administration/upgrading/index.md
Updated warning message and removed some excess wording around upgrading to 4.x or 2018.x
> Warning update for upgrade bug

- docs/administration/tentacle-configuration-and-file-storage/manually-uninstall-tentacle.md
> Tentacle spelling change

- docs/deployment-process/lifecycles/index.md
Goes hand in hand with https://github.com/OctopusDeploy/OctopusDeploy/pull/2430
> Add callout for tenanted deployments to automatic environments in a lifecycle

- docs/administration/workers/built-in-worker.md
- docs/administration/workers/external-workers.md
- docs/administration/workers/index.md
- docs/administration/workers/worker-pools.md
> Add workers patch

- docs/administration/retention-policies/retention-policy-tentacle-cleanup-and-troubleshooting.md
This turned out to be a bit more expansive that I first planned
> Wording cleanup

- docs/administration/security/index.md
Added text to the top level security doc to make it as discoverable as possible to people looking at the security docs. I'll end the actual link when we know the best way to host the PDF.
> [WIP] security review doc

- docs/deployment-process/variables/variable-substitution-syntax.md
Doco for https://github.com/OctopusDeploy/Issues/issues/4859
> Added documentation for text replacement in variable syntax

- docs/administration/security/hardening-octopus.md
The port is listed as 1443 but should be 1433.
> Update SQL Server TCP Port

- docs/deployment-examples/asp.net-core-web-application-deployments/index.md
> Minor grammar changes

- docs/administration/upgrading/index.md
Refer to this conversation: https://octopusdeploy.slack.com/archives/C3KT1DFSM/p1539568071000100
> Link to a github issue for broken upgrade paths

- docs/api-and-integration/octopus.server.exe-command-line/license.md
> updated the Octopus.Server.exe license options

- docs/api-and-integration/tentacle.exe-command-line/agent.md
- docs/api-and-integration/tentacle.exe-command-line/checkservices.md
- docs/api-and-integration/tentacle.exe-command-line/configure.md
- docs/api-and-integration/tentacle.exe-command-line/create-instance.md
- docs/api-and-integration/tentacle.exe-command-line/delete-instance.md
- docs/api-and-integration/tentacle.exe-command-line/deregister-from.md
- docs/api-and-integration/tentacle.exe-command-line/deregister-worker.md
- docs/api-and-integration/tentacle.exe-command-line/extract.md
- docs/api-and-integration/tentacle.exe-command-line/import-certificate.md
- docs/api-and-integration/tentacle.exe-command-line/index.md
- docs/api-and-integration/tentacle.exe-command-line/new-certificate.md
- docs/api-and-integration/tentacle.exe-command-line/poll-server.md
- docs/api-and-integration/tentacle.exe-command-line/polling-proxy.md
- docs/api-and-integration/tentacle.exe-command-line/proxy.md
- docs/api-and-integration/tentacle.exe-command-line/register-with.md
- docs/api-and-integration/tentacle.exe-command-line/register-worker.md
- docs/api-and-integration/tentacle.exe-command-line/server-comms.md
- docs/api-and-integration/tentacle.exe-command-line/service.md
- docs/api-and-integration/tentacle.exe-command-line/show-configuration.md
- docs/api-and-integration/tentacle.exe-command-line/show-thumbprint.md
- docs/api-and-integration/tentacle.exe-command-line/version.md
- docs/api-and-integration/tentacle.exe-command-line/watchdog.md
Created by TeamCity project 'Octofront::Update CLI Docs', build 12
> Updating cli docs for tentacle.exe

- docs/api-and-integration/octo.exe-command-line/clean-environment.md
- docs/api-and-integration/octo.exe-command-line/create-channel.md
- docs/api-and-integration/octo.exe-command-line/create-environment.md
- docs/api-and-integration/octo.exe-command-line/create-project.md
- docs/api-and-integration/octo.exe-command-line/create-release.md
- docs/api-and-integration/octo.exe-command-line/delete-release.md
- docs/api-and-integration/octo.exe-command-line/deploy-release.md
- docs/api-and-integration/octo.exe-command-line/dump-deployments.md
- docs/api-and-integration/octo.exe-command-line/list-deployments.md
- docs/api-and-integration/octo.exe-command-line/list-latestdeployments.md
- docs/api-and-integration/octo.exe-command-line/list-machines.md
- docs/api-and-integration/octo.exe-command-line/list-releases.md
- docs/api-and-integration/octo.exe-command-line/promote-release.md
So we can do the automatic doc updates
> Restructure code blocks to match doc structure of server & tentacle

- docs/api-and-integration/octo.exe-command-line/clean-environment.md
- docs/api-and-integration/octo.exe-command-line/clean-workerpool.md
- docs/api-and-integration/octo.exe-command-line/create-autodeployoverride.md
- docs/api-and-integration/octo.exe-command-line/create-environment.md
- docs/api-and-integration/octo.exe-command-line/create-project.md
- docs/api-and-integration/octo.exe-command-line/create-release.md
- docs/api-and-integration/octo.exe-command-line/create-workerpool.md
- docs/api-and-integration/octo.exe-command-line/delete-autodeployoverride.md
- docs/api-and-integration/octo.exe-command-line/delete-releases.md
- docs/api-and-integration/octo.exe-command-line/deploy-release.md
- docs/api-and-integration/octo.exe-command-line/dump-deployments.md
- docs/api-and-integration/octo.exe-command-line/export.md
- docs/api-and-integration/octo.exe-command-line/import.md
- docs/api-and-integration/octo.exe-command-line/index.md
- docs/api-and-integration/octo.exe-command-line/list-deployments.md
- docs/api-and-integration/octo.exe-command-line/list-environments.md
- docs/api-and-integration/octo.exe-command-line/list-latestdeployments.md
- docs/api-and-integration/octo.exe-command-line/list-machines.md
- docs/api-and-integration/octo.exe-command-line/list-projects.md
- docs/api-and-integration/octo.exe-command-line/list-releases.md
- docs/api-and-integration/octo.exe-command-line/list-tenants.md
- docs/api-and-integration/octo.exe-command-line/list-workerpools.md
- docs/api-and-integration/octo.exe-command-line/list-workers.md
- docs/api-and-integration/octo.exe-command-line/pack.md
- docs/api-and-integration/octo.exe-command-line/promote-release.md
- docs/api-and-integration/octo.exe-command-line/push.md
- docs/api-and-integration/octo.exe-command-line/version.md
An automated update of the command line docs for octo.exe.
Created by TeamCity project 'Octofront::Update CLI Docs', build 13
> Updating cli docs for octo.exe

- docs/deployment-process/project-triggers/automatic-release-creation.md
Hello,
I found a broken link while I was reviewing your documentation for Automatic Release Creation and PR should fix the link. After making the changes I was able to follow the formatted link to the intended destination.
> Removing characters breaking link in the Automatic Release Creation document

- docs/api-and-integration/octopus.server.exe-command-line/path.md
An automated update of the command line docs for octopus.server.exe.
Created by TeamCity project 'Octofront::Update CLI Docs', build 17
> Updating cli docs for octopus.server.exe

- docs/credits.md
An automated update of the credits / license attribution file, based on the latest code in https://github.com/OctopusDeploy/OctopusDeploy. 
Please review for
* syntactical correctness (ie, markdown looks correct)
* logical correctness (ie, when reading it, it makes sense)
* license conformance (we agree with the license in question and we are able to redistribute it)
Created by TeamCity project 'Octofront::Update credits.md (OSS license attribution file)', build 14
> Update credits / license attribution

- docs/api-and-integration/compatibility.md
> Updates to show compatible versions for 2019.1 and greater

- docs/administration/data/data-migration.md
- docs/administration/upgrading/legacy/upgrading-from-octopus-2.6.5-2018.10lts/migrating-data-from-octopus-2.6.5-2018.10lts.md
- docs/api-and-integration/migration-api/index.md
- docs/octopus-cloud/data.md
- docs/octopus-cloud/migrations.md
This PR just leaves some breadcrumbs and instructions for users looking to migrate from self-hosted to cloud, based on the decisions made [here](https://docs.google.com/document/d/1APxPoN_TUv4wZY_V92re4mZQisyE5Uj1RKAFsZr_imw/edit#).
**Before merging:**
> Cloud migrations changes

- docs/infrastructure/accounts/username-and-password.md
small typo - change connect to connecting
> Update username-and-password.md typo

- docs/api-and-integration/work-items/index.md
- docs/api-and-integration/work-items/jira.md
> Work-items patch lee

- docs/deployment-examples/custom-scripts/index.md
Came out of this support ticket - https://help.octopus.com/t/step-template-powershell-script-parameter-mapping/22467/5
> Try and make how parameters are passed clearer

- docs/octopus-cloud/static-ip.md
Fixing some out of date instructions and some general wording updates.
> Static IP Update

- docs/administration/data/octopus-database/index.md
- docs/administration/high-availability/configuring-octopus-for-high-availability.md
- docs/installation/sql.include.md
Discussion: https://octopusdeploy.slack.com/archives/C27FNL3QW/p1553475083189700
> HA db information added

- docs/support/record-a-performance-trace.md
They did a re-org and things moved around
> Update links to JetBrains dotTrace docs

- docs/deployment-process/releases/guided-failures.md
A customer has spotted this missing information which has recently changed https://secure.helpscout.net/conversation/841907916/44098?folderId=2741712
> Updated the doc with step required condition.

- docs/deployment-examples/certificates/index.md
Relates to OctopusDeploy/Issues#3590
> Flesh out cert variable section a little more

- docs/api-and-integration/metadata/github.md
- docs/api-and-integration/metadata/index.md
- docs/api-and-integration/metadata/jira.md
- docs/api-and-integration/metadata/release-notes-templates.md
Some minor doc updates for Octopus 2019.5. Some larger structure changes for this are coming in a subsequent PR so I'm merging this now so customers have a reference to look at. Revisions should arrive shortly. :)
> Octopus 2019.5 Metadata and Work Item Updates

- CONTRIBUTING.md
- docs/api-and-integration/calamari.md
- docs/api-and-integration/octopus.client.md
- docs/deployment-examples/custom-scripts/error-handling.md
- docs/deployment-examples/custom-scripts/index.md
- docs/deployment-examples/custom-scripts/logging-messages-in-scripts.md
- docs/deployment-examples/custom-scripts/output-variables.md
- docs/deployment-examples/custom-scripts/passing-parameters-to-scripts.md
- docs/deployment-examples/custom-scripts/scripts-in-packages/reference-files-within-a-package.md
- docs/deployment-examples/custom-scripts/using-variables-in-scripts.md
- docs/deployment-process/artifacts.md
- docs/deployment-process/variables/output-variables.md
Fixed up the language codes based on our contributing doc.
> Updated language codes from c# to cs

- docs/administration/security/outbound-requests.md
- Updates the list of metrics sent in the usage statistics payload to include the new Monthly Active Users metric, which will be introduced with https://github.com/OctopusDeploy/octopusdeploy/pull/3808
> Mention monthly active users telemetry

- docs/administration/security/index.md
Changed ..." responsibilities taken by whomever is hosing your Octopus Server" to ..." responsibilities taken by whomever is hosting your Octopus Server"
> Fixed spelling in Provided By the Host section

- docs/administration/spaces/index.md
- docs/api-and-integration/metadata/index.md
- docs/api-and-integration/tfs-azure-devops/index.md
- docs/api-and-integration/tfs-azure-devops/using-octopus-extension/build-versions-in-team-build.md
- docs/api-and-integration/tfs-azure-devops/using-octopus-extension/extension-compatibility.md
- docs/api-and-integration/tfs-azure-devops/using-octopus-extension/index.md
- docs/api-and-integration/tfs-azure-devops/using-octopus-extension/install-octo-capability.md
- docs/api-and-integration/tfs-azure-devops/using-octopus-extension/manually-install-the-build-task.md
- docs/deployment-process/project-triggers/automatic-release-creation.md
- docs/getting-started.md
- docs/packaging-applications/package-repositories/built-in-repository/pushing-packages-to-the-built-in-repository.md
* modernize/make consistent references to Azure DevOps/TFS/VSTS/VSO
* update UI descriptions for Azure DevOps
> Refresh some references to, and descriptions of, Azure DevOps

- docs/administration/authentication/guest-login.md
We used to have a 'kiosk' feature that allowed for automatically logging into a guest account.
This is PR documents how it would now work, assuming some other PR's are accepted.
Related links:
- [Authenticator PR](https://github.com/OctopusDeploy/GuestAuthenticationProvider/pull/10)
- [Octopus Server PR](https://github.com/OctopusDeploy/OctopusDeploy/pull/3809)
- [Internal backlog item](https://trello.com/c/fRwz4kXc/146-allow-guest-autologin-via-query-string-parameters)
> Added some documentation for automatic guest login

- docs/api-and-integration/metadata/release-notes-templates.md
Relates to OctopusDeploy/Issues#5583
> Documenting PackageBuildMetadata

- docs/deployment-process/variables/system-variables.md
Add Octopus.Deployment.Trigger.Id and Octopus.Deployment.Trigger.Name
> Add new Trigger system variables to docs

- docs/api-and-integration/octopus.migrator.exe-command-line/export.md
- docs/api-and-integration/octopus.migrator.exe-command-line/import.md
- docs/api-and-integration/octopus.migrator.exe-command-line/index.md
- docs/api-and-integration/octopus.migrator.exe-command-line/migrate.md
- docs/api-and-integration/octopus.migrator.exe-command-line/partial-export.md
- docs/api-and-integration/octopus.migrator.exe-command-line/version.md
An automated update of the command line docs for octopus.migrator.exe.
Created by TeamCity project 'Automated Documentation Updates::Update CLI Docs', build 54
> Updating cli docs for octopus.migrator.exe

- docs/deployment-examples/terraform-deployments/apply-terraform/index.md
Remove incorrect ConvertFrom-JSON switch in example command
> Remove ConvertFrom-JSON

- docs/infrastructure/deployment-targets/linux/tentacle/index.md
Change to Linux Tentacle docs to now point to the apt and yum repositories
> Linux tentacle package repos

- docs/infrastructure/deployment-targets/linux/tentacle/index.md
Added an example to the docs for running Linux Tentacle as a systemd service
> run tentacle as systemd service

- docs/support/log-files.md
I went looking for "retention" around server logs and didn't find anything in the docs, Justin helped me learn that we control it via the nlog file.
When I found this page, because it didn't have the word "retention" I kept looking elsewhere.
I ended up repeating similar text from the section below, not sure if the page should be reworded more to support explaining more things about hte nlog file.
> Retention of server logs maxArchiveFiles

- docs/administration/managing-infrastructure/script-console.md
Trying to help a customer who got confused when they couldn't target the Octopus Server directly. https://help.octopus.com/t/script-console-suggestion-run-on-octopus-server-option/23522/3
> Updated wording and explained Octopus Server

- docs/administration/authentication/index.md
- docs/administration/authentication/octopusid-authentication.md
Initial page content for Octopus ID authentication provider
See also OctopusDeploy/Octopurls/pull/39
> Octopus ID

- docs/deployment-process/releases/deployment-notes.md
- docs/packaging-applications/create-packages/versioning.md
Updates to better explain why changes are not accumulated across pre-releases.
Source 
https://help.octopus.com/t/release-changes/23784/6
> Pre-releases and deployment notes

- docs/deployment-process/channels/index.md
Test code:
```
new[] {
"b",
"beta",
"",
"+meta",
"beta+meta",
"b+meta"
}
.Where(x => Regex.IsMatch(x, @"^(|\+.*)$"))
//.Where(x => Regex.IsMatch(x, @"^[^\+].*"))
```
> Fixed the regex for channel rules

- docs/support/process-dumps.md
Fixing word selection on process dump page.
> Fix typo on Process Dumps page

- docs/deployment-examples/custom-scripts/index.md
- docs/deployment-examples/custom-scripts/powershell-core.md
Moved the PowerShell content into a new section (the old placement conflicted with new updates to the custom-scripts/index.md).
> Moving the powershell core content

- docs/deployment-process/steps/custom-step-templates.md
Related to https://github.com/OctopusDeploy/OctopusDeploy/pull/4360
> Add info about new package control type

- docs/deployment-process/releases/deployment-notes.md
- docs/deployment-process/variables/system-variables.md
Relates to OctopusDeploy/Issues#5604
> Docs for the deployment changes templates

- docs/deployment-process/operations-runbooks/index.md
We received some early feedback that suggested it was not clear that Runbooks can access/consume Project Variables. So we wanted to pull this out into its own section to make it clear that variables are supported, and list the known limitations for the current release.
Would this text help you on your journey with Runbooks and Project Variables? :)
> Adding a Runbook variables section

- docs/infrastructure/workers/dynamic-worker-pools.md
Starting with a small amount of documentation for dynamic worker pools, who they are for, how they work and what tools are installed on them.
Related to: https://github.com/OctopusDeploy/Octopurls/pull/44
> Basic documentation for dynamic worker pools

- docs/deployment-examples/sql-server-databases.md
Our documentation for Redgate tooling was out of date, updated references to DLM and ReadyRoll to the updated Redgate products.
> Updated documenation to reflect changes to Redgate tooling.

- docs/administration/security/exposing-octopus/lets-encrypt-integration.md
I thought it might be a good idea to document the LTS versions for this fix. Is this something we do? Is there a more readable way to word it?
> Document LTS versions supporting ACME v2

- docs/infrastructure/deployment-targets/linux/tentacle/index.md
User reported typo in the install and start command for Debian.
> Update Debian tentacle install and start command

- docs/deployment-process/variables/variable-filters.md
See https://github.com/OctopusDeploy/Octostache/pull/36
PS: I took the liberty to extrapolate the version of introduction.
> add doc variable filter UriPart

- docs/infrastructure/deployment-targets/dynamic-infrastructure/aws-accounts.md
- docs/infrastructure/deployment-targets/dynamic-infrastructure/azure-accounts.md
- docs/infrastructure/deployment-targets/dynamic-infrastructure/index.md
- docs/infrastructure/deployment-targets/dynamic-infrastructure/token-accounts.md
- docs/infrastructure/deployment-targets/dynamic-infrastructure/username-password-accounts.md
Added docs and examples for:
- Token accounts
- AWS accounts
- Username/password accounts
> Added additional account cmdlet docs

- docs/infrastructure/deployment-targets/linux/tentacle/index.md
Update linux tentacle documentation to indicate the PowerShell Core scripts can be used
> Update linux tentacle documentation

- docs/packaging-applications/build-servers/bitbucket-pipelines/index.md
Relates to OctopusDeploy/Issues#4878
Our docs point to a specific tag (over a year old) that had a bug, a client recently raised said bug after following the docs.
We're looking into automating this for future releases of OctopusCLI
> update docker image tag

- docs/octopus-rest-api/octopus-cli/index.md
Also stop calling the global tool option recommended (as netcore gobal tools are kinda out of fashion now - they are just a packaging mechanism that adds complexity)
> Add homebrew install as an option to the octoups cli page

- docs/octopus-rest-api/octopus-cli/install-global-tool.md
Relates to https://github.com/OctopusDeploy/OctopusCLI/pull/50
> Clear up dotnet tool sdk requirements

- docs/octopus-cloud/static-ip.md
Add some clarity around static IP addresses for Tentacles and DW's
> Add some clarity around static IP addresses for Tentacles and DW's

- CONTRIBUTING.md
Adding some docs for the new syntax for referencing docker images
> Added docs for referencing docker image

- docs/deployment-examples/custom-scripts/scripts-in-packages/index.md
https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1584577449195000
> Clarify how Octopus handles duplicate scripts in packages

- docs/shared-content/concepts/octopus-cli.include.md
There was some inconsistency between the different methods of downloading, different links etc.
@jess-ross - this came out of the comments you made on the instructions.
@wordlee - this seem better?
> Simplify the how to get octopus cli instructions

- docs/projects/variables/system-variables.md
I also moved the following from the Deployment section into the new Runbook section:
Octopus.Web.RunbookSnapshotLink
Octopus.Web.RunbookRunLink
> Added runbook system variables

- docs/deployment-examples/custom-scripts/index.md
- docs/deployment-examples/custom-scripts/scripts-in-packages/index.md
- docs/infrastructure/deployment-targets/linux/ssh-deployments.md
See https://github.com/OctopusDeploy/Issues/issues/6267
I've tried to make this page clear, helpful, and not too long, nor duplicate too much information from other places. The page feels, on balance, to be a much more helpful single resource for doing this kind of work with Octopus.
> Updated custom scripts in packages to match cross-platform behaviour

- docs/octopus-rest-api/octopus-cli/allow-releaseprogression.md
- docs/octopus-rest-api/octopus-cli/build-information.md
- docs/octopus-rest-api/octopus-cli/clean-environment.md
- docs/octopus-rest-api/octopus-cli/formatted-output.md
- docs/octopus-rest-api/octopus-cli/install-autocomplete.md
> Updated page order

- docs/installation/requirements.md
- docs/shared-content/installation/sql.include.md
Lines up with our intent for 2020: https://octopus.com/blog/raising-minimum-requirements-for-octopus-server#question-will-i-be-affected
See https://octopusdeploy.slack.com/archives/CDANN5QLT/p1586905758124900
> Increase SQL Server reqs

- docs/infrastructure/workers/dynamic-worker-pools.md
Update available kubectl versions
> Update available kubectl versions

- docs/octopus-cloud/static-ip.md
I read in a document somewhere when I started that we should avoid bullet points when possible but maybe this is a case for them? You tell me. I added this because I had a ticket asking this question and heard we get this question somewhat regularly.
> Added instructions to get to the static IP page

- docs/administration/data/data-migration.md
On occasion, customers are tempted to do this, but it lands them in hot water, sometimes bricking their instance entirely. I think it is a pretty typical thing for an engineer to attempt though, so I'm hoping that some explicit wording here should prevent some confusion for them and our engineers in support.
For example: [Internal tracking](https://secure.helpscout.net/conversation/1151986741/63948?folderId=557082)
> Call out that that Export -> Modify -> Import isn't supported

- docs/security/authentication/azure-ad-authentication.md
Users following guide receive an error unless this additional step is actioned
> addition of step to enable ID tokens

- docs/infrastructure/deployment-targets/windows-targets/azure-virtual-machines/configuration-structure.md
- docs/infrastructure/deployment-targets/windows-targets/azure-virtual-machines/diagnosing-issues.md
- docs/infrastructure/deployment-targets/windows-targets/azure-virtual-machines/index.md
- docs/infrastructure/deployment-targets/windows-targets/azure-virtual-machines/via-an-arm-template.md
- docs/infrastructure/deployment-targets/windows-targets/azure-virtual-machines/via-powershell.md
- docs/infrastructure/deployment-targets/windows-targets/azure-virtual-machines/via-the-azure-cli.md
- docs/infrastructure/deployment-targets/windows-targets/azure-virtual-machines/via-the-azure-portal.md
- docs/infrastructure/deployment-targets/windows-targets/azure-virtual-machines/via-the-classic-azure-portal.md
Noted that the VM extension is depreciated and will be unsupported from 2021.
> Vm extension wording

- docs/octopus-rest-api/octopus.migrator.exe-command-line/index.md
I'm not 100% on the wording. Feel free to wordsmith if either of you want to change how either line is written.
> Add warning about spaces and data migration link

- docs/deployment-patterns/rolling-deployments.md
- added section for child step variable run conditions 
- added links to learn more section
> Rolling deployment doco update

- redirects.txt
Add a redirect for a broken link
> Add redirect for deployment-applications/configuration-files

- docs/projects/variables/system-variables.md
Related Calamari PR: https://github.com/OctopusDeploy/Calamari/pull/567
> Added Octopus.Action.Azure.ExtensionsDirectory variable

- docs/projects/variables/system-variables.md
Reverts OctopusDeploy/docs#780
Accidentally updated the docs prematurely.
> Revert "Added Octopus.Action.Azure.ExtensionsDirectory variable"

- docs/projects/index.md
Expand the detail on the project settings for deployment targets. Essentially explaining the 2 options shown below a bit more :)
> Update deployment targets project settings doco

- docs/installation/requirements.md
- docs/support/compatibility.md
Adding in a section for SQL Server and Operating System support for Octopus.
> Update to Compatibility Page

- docs/deployment-process/steps/custom-step-templates.md
Pending publication of https://github.com/OctopusDeploy/blog/pull/288
> Link to custom step template blog post

- docs/infrastructure/workers/dynamic-worker-pools.md
Updated docs for the Windows 2019 dynamic worker rollout.
These docs are expected to be modified again within the week - we just want to make sure customers can find information when / if they go looking.
> Interim updates for the Win2019 dynamic worker rollout

- docs/deployment-examples/terraform-deployments/index.md
- docs/runbooks/runbook-examples/terraform/index.md
- docs/runbooks/runbook-examples/terraform/provision-aws-with-terraform.md
This example is a bit 'off-script', but I was running out of Nice-to-haves ;)
> Adding terraform example

- docs/deployment-examples/terraform-deployments/index.md
https://help.octopus.com/t/terraform-v0-12-28-and-template-parser/25437/8
This ticket brought this to my attention and I wanted to reflect this information in our documentation.
> Adding warning about updating the terraform tool

- docs/shared-content/security-disclaimer.include.md
This PR adds a security disclaimer in a snippet that can be reused throughout the documentation whenever there is a need by adding the text `!include <security-disclaimer>`.
Are comfortable with the wording in this PR or is there a better way of conveying the point?
> Security disclaimer

- docs/octopus-rest-api/octopus-cli/create-workerpool.md
- docs/octopus-rest-api/octopus-cli/delete-releases.md
- docs/octopus-rest-api/octopus-cli/dump-deployments.md
Added examples for:
- `create-workerpool`
- `delete-releases`
- `dump-deployments`
> More Octo cli examples

- docs/octopus-rest-api/octopus.server.exe-command-line/configure.md
This is a very large command, I did a basic example, but not sure if it's enough.  Feel free to request more to this one if you feel it should have more.
> Adding basic example to configure

- docs/deployment-process/configuration-features/structured-configuration-variables-feature.md
- docs/deployment-process/configuration-features/xml-configuration-variables-feature.md
- docs/shared-content/structured-configuration-variables.include.md
Some suggested revisions for the Structured Configuration XML documentation.
See my comments on the diff for more information.
> Structured Configuration XML documentation revisions

- docs/deployment-process/channels/index.md
Fixing a markdown issue on line 60. The ^ and ^ were causing an issue. Escaped them
> Fixing a markdown issue on line 60. 

- docs/shared-content/structured-configuration-variables.include.md
- Added a table and description that has examples for replacement for each of the supported file formats.
- Updated the wording around enabling Structured Configuration
- Added info about using Structured Configuration with Run a script step and linked to the package files page that describes how the packages are extracted.
> Structured Configuration Variables Cheetsheet and updated to enabling guide

- docs/deployment-examples/kubernetes-deployments/kubectl/index.md
- docs/infrastructure/workers/dynamic-worker-pools.md
This was easier as a PR than as comments.
> Dynamic workers edits

- docs/deployment-examples/kubernetes-deployments/kubectl/index.md
- docs/infrastructure/workers/dynamic-worker-pools.md
* Adds mention of ubuntu
* Removes mention that we're updating the default
* Explains what "default" means and the pros/cons of using it
> Updates for dynamic worker pools

- docs/runbooks/runbook-examples/routine/lets-encrypt-renew-certificate.md
Added Runbook example for Lets Encrypt renewal of a certificate
> Added Runbook example for Lets Encrypt renewal of a certificate

- docs/packaging-applications/create-packages/octopack/index.md
Just fixing a small typo I found while reading the docs 🙂
> Fix typo in Octopack index

- docs/octopus-rest-api/examples/deployment-process/get-steps-using-package.md
- docs/octopus-rest-api/examples/tagsets/create-tagset.md
- docs/octopus-rest-api/examples/tagsets/index.md
- docs/octopus-rest-api/examples/tasks/index.md
- docs/octopus-rest-api/examples/tasks/run-healthcheck.md
- docs/octopus-rest-api/examples/users/index.md
- docs/shared-content/scripts/create-tagset-scripts.include.md
- docs/shared-content/scripts/get-steps-using-package-scripts.include.md
- docs/shared-content/scripts/run-healthcheck-scripts.include.md
- Steps using referenced package
- Create tagset
- Run healthcheck
> Add more api examples

- docs/octopus-rest-api/examples/tenants/index.md
- docs/shared-content/scripts/create-a-tenant-scripts.include.md
This has the one example, wasn't able to get the other one functional.
> Adding partial tenant stuff

- docs/octopus-rest-api/examples/feeds/download-package-from-builtin-feed.md
- docs/shared-content/scripts/download-package-scripts.include.md
> Add API example to download a package for the built-in-feed

- docs/infrastructure/deployment-targets/azure/index.md
Updated the Azure documentation:
1) Instructions reflect the updated Azure Portal
2) Link to getting started video for folks to follow along with
3) New Az PowerShell module script which works with both PowerShell and PowerShell Core (cross-platform support)
4) Added Script from Octopus Labs to fully automate the entire account creation
5) Added notes that service management APIs are being depreciated, so management certs are no longer useful.
> Updating the azure documentation

- docs/packaging-applications/build-servers/jenkins/pipeline.md
Update docs for https://github.com/OctopusDeploy/octopus-jenkins-plugin/pull/92
Issue: https://github.com/OctopusDeploy/octopus-jenkins-plugin/issues/93
> Jenkins: Add "branch" support for build information

- docs/octopus-rest-api/examples/variables/find-variable-usage.md
- docs/octopus-rest-api/examples/variables/find-variableset-variables-usage.md
- docs/shared-content/scripts/find-variable-usage-scripts.include.md
- docs/shared-content/scripts/find-variableset-variables-usage-scripts.include.md
- Simplified de-duplication to actually work in Powershell
- Added a python example for variableset usage
- Modified the hint to include another limitation based on feedback from @ryanrousseau :bowing_man:
> Update variable and variableset usage examples

- docs/octopus-rest-api/examples/accounts/create-aws-account.md
- docs/shared-content/scripts/create-aws-account-scripts.include.md
- docs/shared-content/scripts/create-azure-service-principal-scripts.include.md
Create an account for:
* AWS
* Azure
using Go
> Account Examples

- docs/deployment-examples/certificates/export-certificate.md
User requested info about where exported certificates are downloaded to.
> Added where downloaded certificates go

- docs/projects/variables/prompted-variables.md
Calling out more options explicitly on the new additions to prompted var functionality (more variable types and adding control types) due to a couple support tickets.
> Updating with new additions to prompted vars

- docs/deployment-examples/kubernetes-deployments/helm-update/index.md
Updating 'Do to the design of helm...' to 'Due to the design of helm...'
> Updating word to correct spelling

- docs/security/authentication/active-directory/index.md
- docs/security/authentication/googleapps-authentication.md
- docs/security/authentication/okta-authentication.md
Added in tip at top of page explaining this will not work on cloud
> Updating auth

- docs/octopus-cloud/migrations.md
Show the roadmap and remove the datestamp.
> Further wording tweaks

- docs/packaging-applications/build-servers/github-actions.md
This update is to show the new GitHub Action that was created to install the Octopus Deploy CLI
> GitHub Actions docs updated with official GitHub Action

- docs/administration/upgrading/guide/automate-upgrades.md
I just recently spent the time automating the upgrade of my main local instance and used this guide as a reference. These edits are based on my experience using this and some improvements I made along the way. Overall, the guide and corresponding script is shorter and (I think) easier to understand.
> Improve automate upgrades guide

- docs/administration/managing-infrastructure/moving-your-octopus/move-the-home-directory.md
- docs/administration/managing-infrastructure/server-configuration-and-file-storage/index.md
- docs/administration/managing-infrastructure/server-configuration-and-file-storage/moving-octopus-server-folders.md
Added telemetry folder to server configuration and file storage page, and added section to show how to change the folder.
Relates to https://github.com/OctopusDeploy/Issues/issues/6410
> Add telemetry details, including how to change the folder

- docs/projects/variables/variable-substitutions.md
Matched the explanation of how conditions are evaluated to the algorithm in what I believe is the operative Octostache method:
https://github.com/OctopusDeploy/Octostache/blob/master/source/Octostache/Templates/TemplateEvaluator.cs#L186-L192
```
internal static bool IsTruthy(string value)
{
return value != "0" &&
value != "" &&
string.Compare(value.Trim(), "no", StringComparison.OrdinalIgnoreCase) != 0 &&
string.Compare(value.Trim(), "false", StringComparison.OrdinalIgnoreCase) != 0;
}
```
> Matched "Truthy and Falsy Values" to code

- docs/security/outbound-requests.md
> Added OS architecture telemetry to outbound request table

- docs/shared-content/concepts/create-projects.include.md
Changed the curly quotes to straight quotes
> Fix curly quotation marks

- docs/getting-started/first-deployment/deploy-a-package.md
Replace curly quotes with straight quotes
> Fix curly quotes

- docs/infrastructure/deployment-targets/dynamic-infrastructure/azure-cloud-service-target.md
- docs/infrastructure/deployment-targets/dynamic-infrastructure/azure-service-fabric-target.md
- docs/infrastructure/deployment-targets/dynamic-infrastructure/azure-web-app-target.md
- docs/infrastructure/deployment-targets/dynamic-infrastructure/kubernetes-target.md
> Dynamic infrastructure default worker pool option

- docs/shared-content/scripts/find-variable-value-usage-scripts.include.md
We got a ticket saying the syntax was wrong for the loop for variable sets and I tested it and he was right.
> Changing syntax for iterating through Items.

- docs/infrastructure/deployment-targets/kubernetes-target/index.md
Add linebreak before point 9 of the Kubernetes target page
> Fix bullet point

- docs/deployments/kubernetes/deploy-container/index.md
Added documentations for Kubernetes Job fields.
https://github.com/OctopusDeploy/OctopusDeploy/pull/8753
> Added docos for Kubernetes Job

- docs/administration/high-availability/design/octopus-for-high-availability-on-aws.md
- docs/administration/high-availability/design/octopus-for-high-availability-on-azure.md
- docs/administration/high-availability/design/octopus-for-high-availability-on-premises.md
- docs/administration/high-availability/maintain/polling-tentacles-with-ha.md
- docs/shared-content/administration/polling-tentacles-and-ha-connecting.include.md
- docs/shared-content/administration/polling-tentacles-and-ha-registering.include.md
- docs/shared-content/administration/polling-tentacles-and-ha.include.md
- docs/shared-content/administration/polling-tentacles-connection-different-ports.include.md
- docs/shared-content/administration/polling-tentacles-connection-same-port.include.md
Adding in a section about Polling Tentacles and opening up Ports to register them in Azure
> Adding in Firewall and Networking

- docs/projects/variables/system-variables.md
https://octopusdeploy.slack.com/archives/C033W4273/p1619632648171000
> Reference a flag added to give users the ability to suppress warnings.

- docs/administration/managing-infrastructure/performance/index.md
Made the performane troubleshooting section a bit easier to navigate.  Cleaned up / combined the amount of information we ask for when reaching out to support.
> Performance support

- docs/projects/steps/execution-containers-for-workers/index.md
Added a link to our blog that describes in detail how to create custom Docker images.
> Reference our blog post on how to create custom Docker images

- docs/security/authentication/azure-ad-authentication.md
https://octopusdeploy.slack.com/archives/C27FNL3QW/p1615931346005900 - Discussion around issue
> Updated Azure AD, added hint for username being an email

- docs/administration/high-availability/configure/octopus-with-active-directory.md
- docs/administration/high-availability/configure/octopus-without-active-directory.md
Updated docs to show examples of automating additional nodes to the cluster.
> Enh ha automation

- docs/octopus-cloud/migrations.md
We've decided that we want Bento to be the mechanism through which customers migrate between Server and Cloud (and vice-versa). We no longer support the manual migration method - this method is costly and risky in terms of human intervention. 
We will direct customers towards using Bento for migrations, and monitor Support/feedback channels to direct where/whether we need to put more work into making Bento better for this scenario.
Slack link:
https://octopusdeploy.slack.com/archives/C01NJV6V2KX/p1616718871024000
> Bento is the One True Way for migrations - direct customers that way.

- docs/octopus-rest-api/examples/projects/enable-disable-project.md
- docs/shared-content/scripts/enable-disable-project-scripts.include.md
Adding posh and python script examples to enable/disable projects via REST API
> Rest api project enable/disable examples

- docs/runbooks/runbook-examples/routine/hardening-ubuntu.md
- docs/shared-content/tentacle/configure-ssh-connection-target.include.md
- docs/shared-content/tentacle/configure-ssh-connection-worker.include.md
updating docs to show how to retrieve ssh host fingerprint using ed25519 algorithm.
related to PR - [Internal Link](https://github.com/OctopusDeploy/OctopusDeploy/pull/9342)
> update docs to retirve SSH fingerprint using ed25519 algorithm

- docs/octopus-rest-api/examples/artifacts/create-and-upload-artifacts.md
- docs/octopus-rest-api/examples/artifacts/download-deployment-artifacts.md
- docs/octopus-rest-api/examples/artifacts/index.md
- docs/octopus-rest-api/examples/certificates/index.md
- docs/octopus-rest-api/examples/channels/index.md
- docs/octopus-rest-api/examples/deployment-process/index.md
- docs/octopus-rest-api/examples/deployment-targets/index.md
- docs/octopus-rest-api/examples/deployments/index.md
- docs/octopus-rest-api/examples/environments/index.md
- docs/octopus-rest-api/examples/events/index.md
- docs/octopus-rest-api/examples/feeds/index.md
- docs/octopus-rest-api/examples/lifecycles/index.md
- docs/octopus-rest-api/examples/project-groups/index.md
- docs/octopus-rest-api/examples/projects/index.md
- docs/octopus-rest-api/examples/releases/index.md
- docs/octopus-rest-api/examples/reports/index.md
- docs/octopus-rest-api/examples/runbooks/index.md
- docs/octopus-rest-api/examples/spaces/index.md
- docs/octopus-rest-api/examples/step-templates/index.md
- docs/octopus-rest-api/examples/tagsets/index.md
- docs/octopus-rest-api/examples/tasks/index.md
- docs/octopus-rest-api/examples/tenants/index.md
- docs/octopus-rest-api/examples/users-and-teams/index.md
- docs/octopus-rest-api/examples/variables/index.md
- docs/shared-content/scripts/download-artifact-from-deployment-scripts.include.md
- docs/shared-content/scripts/upload-artifact-to-deployment-scripts.include.md
* Added new API example folder, `Artifacts`
* Added script examples for uploading and downloading artifacts
* [Cleaned up index ordering to account for new folder](https://github.com/OctopusDeploy/docs/commit/c8ac012bdc3b67fd150948c121240c6644a506da)
>  Artifact Rest API Examples

- docs/administration/upgrading/index.md
I'm not sure the 2nd link I added will work as it's an anchor. I couldn't find any other examples of linking to an anchor point.
> Adding warning about watchdog when upgrading

- docs/getting-started/first-runbook-run/define-the-runbook-process-for-targets.md
Changed from run on a deployment target to run on each deployment target
Removed spaces in bash script to correct use. (Confirmed with Kenny and Finnian)
> Updated Runbook content

- docs/releases/issue-tracking/jira.md
Here you go folks, just fixing a little typo I spotted.
> Jenkins Is Not A Possessive

- docs/infrastructure/workers/dynamic-worker-pools.md
> Kim execution containers

- docs/security/authentication/active-directory/index.md
Fixes https://github.com/OctopusDeploy/ResearchAndDevelopment/issues/28
> Add User vs Kernel mode via HTTP.sys or Kestrel

- docs/administration/high-availability/design/octopus-for-high-availability-on-azure.md
- docs/administration/high-availability/migrate/index.md
- docs/administration/upgrading/guide/automate-upgrades.md
- docs/shared-content/administration/load-balancer-endpoint-info.include.md
Fleshing out the guide to migrate to HA as we have gotten a lot of questions around order of operations, what can be done prior to the outage window, etc.
> Migrate to ha

- docs/packaging-applications/package-repositories/guides/cloudsmith-feed.md
@DevOpsDerek I just saw some of the collapsing sections rendered funny so I fixed that.
> Cloudsmith: fixup the format for the collapsing sections

- docs/support/process-dumps.md
@harrisonmeister - Not 100% sure of the wording, happy to adjust it!
> Updated Process Dump to include Calamari.exe

- docs/projects/version-control/index.md
Update the documentation to include the following - 
- We have added 2 fields in build server integrations to specify branch variable name and commit.
- Provide some details on recommended scopes for the personal access token based on the least privilege principle.
> Update Config as Code documentation

- docs/octopus-cloud/index.md
Change speaks for itself really
> Fixes cloud signup link

- docs/packaging-applications/build-servers/github-actions.md
@harrisonmeister 
fixed typo for default log level
> fixed typo

- docs/shared-content/samples/samples-instance-features-list.include.md
An automated update of the features directory list for the Customer Solutions Team samples instance, https://samples.octopus.app.
Created by the SamplesDirectory process, run from https://samples-admin.octopus.app
> Updating features directory for samples instance

- docs/support/how-to-turn-on-variable-logging-and-export-the-task-log.md
@harrisonmeister 
Just added some extra info about what is logged, found over at:
https://octopus.com/docs/support/debug-problems-with-octopus-variables#DebugproblemswithOctopusvariables-Writethevariablestothedeploymentlog
> Added info about evaluated variables

- docs/getting-started/index.md
Experimenting with changing the free trial button. Moving from the bottom to the top
> changes to the free trial button

- docs/projects/index.md
There are now two methods for customizing your project logo (icon + custom image), where previously there was only the custom image. This change communicates how to use both methods.
> Update project logo docs

- docs/projects/version-control/creating-and-deploying-releases-version-controlled-project.md
Changed to clarify intention behind each field. Just added a little extra info about each
@harrisonmeister - Just a suggestion, feel free to adjust to how you like! 
https://octopus.zendesk.com/agent/tickets/86312
> updated Creating a release from a build server plug-in

- docs/shared-content/scripts/get-steps-using-package-scripts.include.md
Changed script to check for version-controlled project and if the base Octopus Server version is greater than 2022.1 to use new API endpoints, falls back to old endpoint if the version is pre-2022.1
> Updated PowerShell REST Script

- docs/deployments/aws/aws-s3-create-bucket/index.md
We want to add a link to our survey in the documentation.
> Add survey link for Create S3 Bucket step

- docs/shared-content/scripts/cancel-queued-deployments-scripts.include.md
The script checks the wrong variable to know if there are more pages. Just a quick fix up to the script for the next person.
> Fixes the cancel all tasks PowerShell script

- docs/administration/managing-infrastructure/tentacle-configuration-and-file-storage/manually-uninstall-tentacle.md
Adding some additional steps for manually uninstalling the Octopus tentacle service.
> Tentacle manual uninstall updates

- docs/administration/managing-infrastructure/performance/index.md
Changed 'rebuilt' to 'rebuild'.
> Fixing typo in SQL tip

- docs/infrastructure/workers/dynamic-worker-pools.md
Add 3.3.1 to the windows dynamic workers cached images
> Add 3.3.1 to dynamic workers windows cached images

- docs/infrastructure/deployment-targets/cloud-target-discovery/index.md
- docs/infrastructure/deployment-targets/dynamic-infrastructure/kubernetes-target.md
- docs/infrastructure/deployment-targets/kubernetes-target/index.md
There have been recent updates and another one which will be merged imminently, which add functionality to Cloud Target Discovery for Kubernetes clusters. These documentation changes reflect this additional functionality.
I'm unsure if the way I have presented the introduction of new features in different versions is appropriate so I would like some feedback on that.
Here is a screen cap of how it looks on the web page:
> Update Kubernetes Target Discovery Documentation

- docs/infrastructure/deployment-targets/linux/tentacle/quickstart-debian.include.md
Very tiny but very noticeable typo.
> spotted some typos, quick tweak

- docs/projects/version-control/config-as-code-reference.md
Update existing documentation to use slugs instead of names.
> Update CaC reference for slugs

- docs/installation/octopus-server-linux-container/index.md
I've updated the cache description and added a column to highlight whether the volume mount should be local to the container or in durable storage.
> Updated container storage description

- docs/deployments/aws/s3/index.md
Adding a new error scenario and resolution steps to S3 step template documentation
> Adding new error scenario and resolution

- docs/support/compatibility.md
Typo in header - should be forward.
> Fixing typo

- docs/administration/retention-policies/index.md
- docs/security/users-and-teams/auditing.md
The documentation to support the new feature of archiving event records.
> Event retention documentation

- docs/infrastructure/accounts/ssh-key-pair.md
Add ED25519 key generation for modern, more secure environments.
> Update SSH Key generation docs

- docs/insights/csv-download.md
Before:
After:
No extra line break.
> Remove extra line break in warning

- .config/dotnet-tools.json
Update to latest version that includes changes from https://github.com/OctopusDeploy/DependencyScanner/pull/63
> Update creditsfilegenerator to 1.0.680

- docs/approvals/service-now/index.md
> added SNOW troubleshooting section

- docs/approvals/service-now/index.md
Add more information to aid people's understanding around normal vs standard changes, and extend troubleshooting - incrementally.
> Add more words about standard vs normal

- docs/approvals/service-now/index.md
> extend description of snow requirements

- docs/security/index.md
replacing the 2021 review with the two 2022 reviews
> added links to 2022 pentest exec summaries

- docs/security/users-and-teams/auditing.md
[sc-30076]
Reflecting more accurate rollout dates to better inform customers.
> Amending audit log retention rollout dates

- docs/shared-content/scripts/find-variable-usage-scripts.include.md
- docs/shared-content/scripts/find-variable-value-usage-scripts.include.md
- docs/shared-content/scripts/find-variableset-variables-usage-scripts.include.md
- docs/shared-content/scripts/list-users-scripts.include.md
- docs/shared-content/scripts/list-users-with-editing-roles-scripts.include.md
The affected scripts generate CSV files without the first row.
This PR fixes the bug.
> Fix csv file generation

- docs/projects/version-control/config-as-code-reference.md
- docs/projects/version-control/converting/index.md
- docs/projects/version-control/editing-a-project-with-version-control-enabled.md
Reverts OctopusDeploy/docs#1713. @harrisonmeister This was not meant to go to Prod yet. Apologies - waiting for Q4 launch first. Can we revert back until then? Thanks!
> Revert "Update config-as-code-reference.md"

- docs/deprecations/index.md
Put onboarding deprecation notice in the [sc-11966]
> Add deprecation notice for `/useronboarding` endpoint

- docs/deployments/aws/cloudformation/index.md
A new feature in Octopus exposes a new error code. This PR adds the error code to the existing documentation.
> Added additional docs for the new error message

- docs/projects/variables/system-variables.md
- docs/releases/release-notes.md
This PR adds documentation for the new variables included with the issue https://github.com/OctopusDeploy/Issues/issues/7941.
> Documented new release notes variables

- docs/installation/requirements.md
See [here](https://octopusdeploy.slack.com/archives/C01HZFJRYSH/p1670528368122199) (internal link)
> Add Windows Server 2022 to install supported OS

- docs/security/users-and-teams/index.md
I've added a User API Key Management section that details what happens when a User account is disabled or deleted.
> Add section on user api key management

- docs/security/users-and-teams/index.md
I've updated text from this:
A disabled user's API keys will not function. An attempt to use it will throw a...
to this:
A disabled user's API keys will not function. Any attempt to use them will throw a...
The grammar police told me to - at least, that's my excuse and I'm sticking to it!
> Minor grammar edit

- docs/security/users-and-teams/index.md
One last time, then I'll browse away from the page - I promise!
> Another grammar edit

- docs/packaging-applications/build-servers/tfs-azure-devops/using-octopus-extension/index.md
- docs/packaging-applications/build-servers/tfs-azure-devops/using-octopus-extension/install-octopus-cli-capability.md
related to https://github.com/OctopusDeploy/OctoTFS/pull/292
> updated for AzureDevops v6 steps

- docs/insights/metrics.md
Adds documentation for https://github.com/OctopusDeploy/OctopusDeploy/pull/16705
> Added documentation for deployment duration

- docs/deprecations/index.md
> Added DFS deprecation information for 2023.1

- docs/shared-content/scripts/create-and-deploy-release-scripts.include.md
- docs/shared-content/scripts/create-aws-account-scripts.include.md
- docs/shared-content/scripts/create-azure-service-principal-scripts.include.md
- docs/shared-content/scripts/create-google-cloud-account-scripts.include.md
- docs/shared-content/scripts/run-runbook-scripts.include.md
Also removed some TS examples for accounts that are not supported in the current TS client
> Updated some examples for creating/deploying releases.

- docs/installation/octopus-server-linux-container/docker-compose-linux.md
Adding missing end to code block to fix formatting.
> Adding missing code block end

- docs/administration/data/octopus-database/index.md
Crosslink the SQL Performance generic maintenance recommendations into the admin page.
> Crosslink SQL Performance pages

- docs/getting-started/managing-octopus-subscriptions.md
Update docs page to include self-service purchasing workflow.
> Self service purchasing docs inclusion

- src/pages/docs/infrastructure/deployment-targets/cloud-target-discovery/index.md
Replicating wording from [pull/1849](https://github.com/OctopusDeploy/docs/pull/1849/files)
> Clarifying cloud target removal conditions.

- src/pages/docs/guides/index.md
This file won't be used in production, but is required during pre-production testing.
> Placeholder for guides

- public/docs/css/main.css
- src/components/LastUpdated.astro
- src/data/language.json
- src/layouts/Default.astro
Component to add last modified date to pages, based on frontmatter.
> Last updated date

- src/layouts/Default.astro
Moves the last updated date to the end of the article.
> Move last updated date.

- public/docs/css/main.css
- public/docs/css/vars.css
> Page margin

- package-lock.json
- package.json
- public/docs/css/main.css
- public/docs/js/modules/detail-tabs.js
`element.role` silently failed in Firefox, so `element.setAttribute('role'...` needs to be used instead.
> Resolves tab issue in Firefox

- src/pages/docs/deployments/custom-scripts/run-a-script-step.md
> Remove extra table header pipe

- src/pages/docs/deployments/azure/cloud-services/index.mdx
Fixes the path to the package feed image.
> Fix package feed image path

- src/pages/docs/octopus-rest-api/examples/projects/index.md
Adding links to Projects overview page
> Adding content to Projects overview page

- src/pages/docs/infrastructure/deployment-targets/kubernetes-target/index.md
[sc-49733]
will have to wait until changes have been shipped
> kubelogin updates

- src/pages/docs/security/octopus-tentacle-communication/index.md
Fixing broken link as per [this request](https://octopusdeploy.slack.com/archives/C03UDS16R6G/p1688637684112859) from Clare.
> Fix broken link on Octopus Tentacle Communication

- src/pages/docs/administration/upgrading/guide/automate-upgrades.mdx
When testing a recent change I spotted the syntax highlighting was missing from this code block.
Language added to fix this.
> Add language for code sample

- src/pages/docs/security/users-and-teams/auditing/index.md
As per https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1688701795566539 this information is out of date.
[sc-53473]
> Update security auditing

- .github/workflows/build-astro.yml
This is an alternative suggestion for increasing memory.
> Attempt to set size on npm command

- src/pages/docs/octopus-rest-api/examples/accounts/index.md
- src/pages/docs/octopus-rest-api/examples/artifacts/index.md
- src/pages/docs/octopus-rest-api/examples/certificates/index.md
- src/pages/docs/octopus-rest-api/examples/channels/index.md
- src/pages/docs/octopus-rest-api/examples/events/index.md
- src/pages/docs/octopus-rest-api/examples/feeds/index.md
- src/pages/docs/octopus-rest-api/examples/index.md
- src/pages/docs/octopus-rest-api/examples/lifecycles/index.md
- src/pages/docs/octopus-rest-api/examples/project-groups/index.md
- src/pages/docs/octopus-rest-api/examples/releases/index.md
- src/pages/docs/octopus-rest-api/examples/runbooks/index.md
- src/pages/docs/octopus-rest-api/examples/spaces/index.md
- src/pages/docs/octopus-rest-api/examples/step-templates/index.md
- src/pages/docs/octopus-rest-api/examples/tasks/index.md
- src/pages/docs/octopus-rest-api/examples/tenants/index.md
- src/pages/docs/octopus-rest-api/examples/users-and-teams/index.md
- src/pages/docs/octopus-rest-api/examples/variables/index.md
- src/pages/docs/runbooks/runbook-examples/databases/index.md
- src/pages/docs/security/authentication/active-directory/index.md
- src/pages/docs/tenants/guides/index.md
- src/pages/docs/tenants/guides/multi-tenant-region/index.md
- src/pages/docs/tenants/guides/multi-tenant-saas-application/index.md
- src/pages/docs/tenants/guides/multi-tenant-teams/index.md
I've added all listing links to pages in Docs which came up in Steve's search discussed in this [Slack thread](https://octopusdeploy.slack.com/archives/C03UDS16R6G/p1689745571024199).
> Adding listing links to Docs pages

- src/pages/docs/infrastructure/deployment-targets/kubernetes-target/index.md
@steve-fenton-octopus 
@benPearce1  
@IsaacCalligeros95 
Updated the kubelogin note but feel free to make any changes!
> updated kubelogin note for aks

- src/pages/docs/administration/managing-infrastructure/subscriptions/index.md
> Update subscriptions page to include clarification on how the filters and options work

- src/shared-content/scripts/push-package-scripts.include.md
Update script to match https://github.com/OctopusDeploy/OctopusDeploy-Api/pull/167
> Update push package script example

- package-lock.json
- package.json
- public/docs/js/search.js
- src/components/Plausible.astro
- src/layouts/Default.astro
Adds the search event logging for Plausible.
> Add search event for Plausible

- src/components/Plausible.astro
Script should be rendered inline.
> Render script inline

- src/pages/docs/deployments/aws/ecs/index.md
See ticket here: https://octopus.zendesk.com/agent/tickets/146328
> Removing stack from this help tip, as this can be named.

- src/pages/docs/deployments/kubernetes/deploy-raw-yaml/index.md
- src/pages/docs/deployments/kubernetes/glob-patterns.md
- src/pages/docs/deployments/kubernetes/kubectl/index.md
- src/pages/docs/deployments/kubernetes/kustomize/index.md
This PR adds the docs for the new Kustomize step
> kustomize docs

- src/pages/docs/administration/high-availability/index.md
Updating docs licensing information around high availability so that it aligns with what we say on our pricing page.
Docs page:
Pricing page:
> Update high availability licensing information

- src/config.ts
Resolves the 404 caused by the incorrect path to the font preload URLs.
> Fix preload urls.

- package.json
- pnpm-lock.yaml
- public/docs/css/main.css
- public/docs/css/vars.css
- public/docs/js/modules/detail-tabs.js
- public/docs/js/modules/nav-mobile.js
- public/docs/js/modules/search-dialog.js
- src/components/Header.astro
- src/themes/accelerator/components/Authors.astro
- src/themes/accelerator/components/AuthorsMini.astro
- src/themes/accelerator/components/Header.astro
- src/themes/accelerator/components/Related.astro
- src/themes/accelerator/layouts/Default.astro
- src/themes/accelerator/utilities/language.json
Contains accessibility improvements for:
- Menu disclosure
- Search icon
- Tabs
> Update accelerator - accessbility improvements

- src/pages/docs/infrastructure/deployment-targets/offline-package-drop.md
Also included a workaround to revert the functionality to previous behavior
[sc-60449]
> Add a warning to the offline drop docs about a breaking change in PS 7.3 that breaks our offline drop script

- .github/workflows/branch-validation.yml
Naming the job "test" will make the pull request checks more understandable.
> Rename the status check to "test"

- .github/workflows/build-astro.yml
Resolves #2018 by conditionally running Octopus steps based on the presence of the URL secret.
> Conditionally run deploy steps only if an Octopus URL is present

- .github/workflows/build-astro.yml
See #2018 - adjusted condition to handle whether deployment steps should run.
> Adjust condition for SHOULD_DEPLOY

- src/pages/docs/projects/steps/configuration-features/xml-configuration-variables-feature.md
> Fix table on XML Configurations Feature page

- package.json
- pnpm-lock.yaml
Isolated the support for markdown in frontmatter as a performance bottleneck. Reduced the overheads of processing support for the commonly used items.
> Performance experiment

- src/pages/docs/projects/variables/certificate-variables.md
See [Slack discussion](https://octopusdeploy.slack.com/archives/C033W4273/p1697069606822529).
> Adding a little extra context for pfx certificate variables

- src/pages/docs/infrastructure/deployment-targets/machine-policies.mdx
- src/pages/docs/projects/steps/conditions/index.mdx
See previous changes here - https://github.com/OctopusDeploy/docs/pull/2005/files
> Review and update docs for RPC retry feature.

- dictionary-octopus.txt
- public/docs/css/main.css
- public/docs/css/vars.css
Ensures bold text is rendered on Mac OS.
> Bold text rendering for Mac OS.

- dictionary-octopus.txt
- src/pages/docs/infrastructure/deployment-targets/machine-policies.mdx
- src/pages/docs/packaging-applications/package-repositories/index.md
- src/pages/docs/projects/built-in-step-templates/health-check.md
- src/pages/docs/projects/deployment-process/performance.md
- src/pages/docs/projects/steps/conditions/index.mdx
- src/pages/docs/projects/variables/system-variables.md
- src/pages/docs/releases/release-notes.md
- src/pages/docs/security/users-and-teams/auditing/index.md
- src/pages/docs/support/troubleshooting-failed-or-hanging-tasks.md
[sc-62820]
Updating the version numbers in our docs to be up-to-date for the RPC retries and Event Retention features.
> Readjusting the version numbers

- README.md
- dictionary-octopus.txt
- frontmatter.json
- src/pages/index.md
This improves image insertion and preview paths.
> Front Matter Config

- src/pages/docs/platform-engineering/managing-project-resources.md
- src/pages/docs/platform-engineering/managing-space-resources.md
Added suggestions that got missed after approval of #2065
> Platform engineering docs suggestions

- src/pages/docs/getting-started/reference-architectures.md
The PR at https://github.com/OctopusDeploy/Library/pull/1430 added some custom variables that can be defined when deploying the reference architecture step. This PR documents the new fields.
> Added notes on custom variables

- src/pages/docs/platform-engineering/managing-project-resources.md
- src/pages/docs/platform-engineering/managing-runbook-resources.md
This PR adds documentation for the process of exporting and importing runbooks.
> Added docs for exporting a runbook

- src/pages/docs/platform-engineering/listing-downstream-drift.md
- src/pages/docs/platform-engineering/merging-downstream.md
This PR is the documentation that related to the steps in the PR https://github.com/OctopusDeploy/Library/pull/1441/files.
> Added documentation on the new "Octopus - Find CaC Updates" steps

- src/pages/docs/administration/managing-licenses/community/index.mdx
- src/shared-content/octopus-cloud/octopus-cloud-community-plan-instance-limits.include.md
- src/shared-content/octopus-server/octopus-server-community-limits.include.md
Added community slack link to the licence limits
> Finnd update community licence add slack

- package.json
- pnpm-lock.yaml
- public/docs/js/modules/search-dialog.js
- public/docs/js/search.js
Improved scoring - balancing really strong matches with the new nesting bonus.
`CTRL` + `SPACE` opens search, to match the Octopus Web Portal.
> Updates search

- src/pages/docs/platform-engineering/managing-space-resources.md
This PR links to a youtube video supporting the documentation.
> Added a supporting video to exporting space resources

- src/pages/docs/platform-engineering/managing-project-resources.md
This PR adds a supporting video demonstrating the deployment of managed projects.
> Added a supporting video

- src/pages/docs/platform-engineering/forking-git-repos.md
I used the wrong format of Youtube link. This PR fixes it.
> Fixed a YouTube link

- dictionary-octopus.txt
- src/pages/docs/getting-started/reference-architectures/eks-reference-architecture.md
This PR adds details on the feature branch deployments added to the EKS RA step.
> Added notes on feature branch deployments

- src/pages/docs/platform-engineering/managing-runbook-resources.md
This PR adds an example video to the runbook deployment docs page.
> Linked to example video for runbook deployments

- src/pages/docs/search.md
> Move search menu item up

- dictionary-octopus.txt
- src/pages/docs/getting-started/best-practices/environments-and-deployment-targets-and-roles.md
Reduce from 20 to 10 per space.
Consensus amongst TAMs and SEs was 10 was a surprising number and 5 would be raised eyebrow time.
> Change recommendation for environments per space

- src/pages/docs/projects/project-triggers/scheduled-deployment-trigger.md
- src/pages/docs/runbooks/scheduled-runbook-trigger/index.md
Relates to https://github.com/OctopusDeploy/Issues/issues/8525
[sc-66947]
> Make docs a bit clearer on scheduled trigger logic

- src/pages/docs/infrastructure/accounts/aws/index.md
- src/pages/docs/infrastructure/accounts/openid-connect.md
Try and make it easier for users to fall in the pit of success.
Updates based on feedback from a customer trying to get AWS OIDC setup
[sc-69507]
> Update AWS OIDC docs

- src/pages/docs/octopus-rest-api/openid-connect/github-actions.md
`in to obtain` -> `in order to obtain` :D
> Fix grammatical error

- dictionary-octopus.txt
- package.json
- pnpm-lock.yaml
- public/docs/js/modules/headers.js
- public/docs/js/modules/nav-mobile.js
- public/docs/js/modules/nav-sticky.js
- public/docs/js/modules/stemmer.js
- public/docs/js/modules/toc.js
- public/docs/js/search.js
- src/config.ts
- src/themes/accelerator/components/RecentlyUpdated.astro
- src/themes/accelerator/utilities/img.mjs
Dependabot has [highlighted an issue in VITE](https://github.com/OctopusDeploy/docs/security/dependabot/10) that is resolved by updating the Accelerator dependency.
> Update accelerator (resolves VITE issue)

- src/pages/docs/infrastructure/accounts/openid-connect.md
The page was published in 2023, and updated in January.
Dates fixed to reflect this.
> Resolves the date formatting issue

- src/pages/docs/deprecations/index.md
Add deprecation notice for Helm V2
> Add Helm V2 deprecation notice

- dictionary-octopus.txt
- package.json
- pnpm-lock.yaml
- public/docs/css/main.css
- public/docs/css/vars.css
- public/docs/js/search.js
- src/components/Header.astro
- src/config.ts
- src/layouts/Default.astro
- src/layouts/Search.astro
- src/pages/docs/infrastructure/accounts/aws/index.md
- src/pages/docs/search.md
- src/themes/accelerator/components/Search.astro
Follow up to this [PR](https://github.com/OctopusDeploy/docs/pull/2154) - messed up commit history and started with a clean branch from main.
> Search component

- public/docs/css/main.css
- public/docs/js/search.js
- src/themes/accelerator/components/Search.astro
Fixed:
- z-index conflict on mobile
- No results smaller and with padding
- Tabbing into search caused losing focus on input (blur was called)
- Return btn cleared input (submit issue)
> Fixed enter submit issue and some styling

- public/docs/js/search.js
Fixed reported issues:
- If you scroll to the bottom of the page, then start typing in search, the page scrolls up a bit on each keypress
- When typing in search and backspace everything (because you made a mistake) it won't let you type again unless you click inside the search bar again with your mouse
- When searching for e.g. Tenants and then clicking on a search result and then trying to search again won't populate new search results (no dropdown with results when searching a second time)
> Search bug fixes

- public/docs/css/main.css
- public/docs/js/search.js
- src/themes/accelerator/components/Search.astro
If you select a page from search dropdown there is a chance this error will occur. Sometimes right away sometimes on a 3rd or 4th page selection. Can't reproduce this issue locally but happens on staging. Anyway I'm hoping this change will resolve it.
> Resolving site_features issue

- public/docs/css/main.css
- public/docs/css/vars.css
- public/docs/js/search.js
Position changed to fixed and that is fixed.
> Fixed scroll issue

- src/pages/docs/infrastructure/accounts/aws/index.md
fixed div format
before: 
after:
> updated aws oidc

- dictionary-octopus.txt
- public/docs/css/main.css
- public/docs/js/modules/figures.js
- src/components/Image.astro
This PR is about a new image component. Although it's not being used anywhere for now - each image has to be manually replaced with this new component. Due to that fact for now I added some styles for current images so they'll look more or less as the component. This is how they'll look like now:
This is the image component:
1. Default
https://github.com/OctopusDeploy/docs/assets/148771144/b605b5ae-ec02-4da2-b2cf-e5410a4b2300
2. With caption
https://github.com/OctopusDeploy/docs/assets/148771144/d9e82d36-a40a-4339-9733-7f39b97124aa
> Image component

- public/docs/css/main.css
- public/docs/css/vars.css
- src/components/Card.astro
- src/pages/docs.mdx
Card component created with two variants:
1. Default
https://github.com/OctopusDeploy/docs/assets/148771144/480bde2b-f544-4864-8126-c9b0eefc56d8
2. Padded
https://github.com/OctopusDeploy/docs/assets/148771144/8d0ec854-1265-4c61-84e5-f066094109ce
> Card component

- src/pages/docs/octopus-rest-api/openid-connect/index.md
> Fix warning in OIDC docs

- src/pages/docs.mdx
We have a utility to embed YouTube videos that avoid loading everything up front. That speeds up the initial page load.
I've also updated the modified date.
> Speed up page with YT embed and update modified date

- package.json
- pnpm-lock.yaml
- src/pages/docs/infrastructure/deployment-targets/linux/ssh-requirements.md
- src/pages/docs/infrastructure/deployment-targets/tentacle/linux/index.mdx
* Fixes broken link
* Fixes erroneous .net install comment, just the prerequisites are required.
> Update linux prereq links and wording

- src/pages/docs/getting-started/index.md
Copy on current page references projects that do not exist in the screenshot
> Copy updates on Getting Started

- dictionary-octopus.txt
- src/pages/docs/infrastructure/deployment-targets/kubernetes-target/index.md
- src/pages/docs/infrastructure/deployment-targets/tentacle/tentacle-communication.md
Added warning about Worker pool for K8s targets, feel free to modify wording!
> updated kube target docs to include workerpool warning

- dictionary-octopus.txt
- src/pages/docs/administration/managing-infrastructure/subscriptions/index.md
- src/pages/docs/deployments/certificates/wildfly-certificate-import.md
- src/pages/docs/deployments/deployment-freezes.md
- src/pages/docs/projects/community-step-templates.md
- src/pages/docs/projects/custom-step-templates.md
A few broken links on docs appeared in a website crawl
> Fixing broken links

- src/pages/docs/octopus-rest-api/getting-started.mdx
- src/pages/docs/octopus-rest-api/index.mdx
- src/shared-content/concepts/rest-api.include.md
Copy updates to overview page and splitting the getting started content to it's own page.
> Octopus REST API updates

- dictionary-octopus.txt
- src/pages/docs/packaging-applications/build-servers/appveyor/index.md
- src/shared-content/scripts/create-a-lifecycle-scripts.include.md
This fixes spelling errors, mainly by adding terms to the dictionary.
> Fixes spelling errors

- src/pages/docs/deprecations/index.md
Hey @rain-on 
This PR updates your branch to set the modified date on the page you updated.
Thanks,
Steve
> Update modified date

- dictionary-octopus.txt
- src/pages/docs/deprecations/index.md
Mainly to simplify sentences and remove passive voice.
> A light edit of deprecations.

- dictionary-octopus.txt
- src/pages/docs/administration/managing-infrastructure/server-configuration-and-file-storage/index.md
- src/pages/docs/deployments/kubernetes/deploy-ingress/index.md
- src/pages/docs/deployments/kubernetes/deploy-service/index.md
- src/pages/docs/deployments/packages/transfer-package.md
- src/pages/docs/deployments/windows/virtual-hard-drive-deployments.md
- src/pages/docs/installation/octopus-server-linux-container/octopus-in-kubernetes.mdx
Resolves spelling issues in the step selection branch.
> Resolve spelling issues

- dictionary-octopus.txt
- src/pages/docs/deployments/databases/index.md
Updated the list of products and reordered them, placing the our Redgate partners at the top.
> Updating list of database products and providing links

- src/pages/docs/approvals/servicenow/index.md
Adds version numbers for newer functionality in ITSM docs
> Adding version numbers to ITSM docs

- src/pages/docs/administration/copilot/index.md
This page needs to be hidden until the service is publically available.
> Set publish date into the future

- .vscode/extensions.json
Suggests the right list of extensions to users of VS Code / GitHub codespaces.
> Add extensions configuration to help onboarding

- public/docs/css/main.css
- public/docs/css/vars.css
- src/components/Feedback.astro
- src/components/Header.astro
- src/pages/docs/getting-started/index.md
https://github.com/OctopusDeploy/docs/assets/148771144/f3c7740f-8f16-4d38-8615-e0232e6a614b
> Buttons update

- src/pages/docs/administration/copilot/index.md
Based on feedback from the Github Team, the app name of the Copilot agent needs to be updated.
> Update the Copilot App name

- src/pages/docs/octopus-cloud/index.mdx
Making minor copy change as per [this conversation](https://octopusdeploy.slack.com/archives/CAT2JGHGF/p1715562829848009?thread_ts=1714546769.681789&cid=CAT2JGHGF)
> Change line around exceeding limits

- .github/CODEOWNERS
Team Github is now Team DevEx! 🦖
> Update code owners to include Team DevEx 🌷 

- src/pages/docs/infrastructure/deployment-targets/kubernetes/kubernetes-agent/automated-installation.md
Adds documentation on how to install and manage the kubernetes agent using terraform
> Add automated install docs for K8s Agent

- .astro/settings.json
- package-lock.json
- package.json
- pnpm-lock.yaml
- src/pages/docs/projects/steps/conditions/index.mdx
@steve-fenton-octopus I'm not too sure what's going on with the package.json file being updated with pnpm 9.1.0, I didn't touch that file
Changes:
More than 10 steps can execute in parallel by default:
> updated step conditions to better reflect max parallelism

- src/pages/docs/administration/copilot/index.md
This PR makes the page public and rewords the intorduction.
> Update Github Copilot docs

- .octopus/variables.ocl
Testing removal of restriction following error.
> Remove restriction

- .github/workflows/branch-spellcheck.yml
- .github/workflows/branch-validation.yml
- .github/workflows/build-astro.yml
Short circuits in-flight actions when a new commit arrives. Fails fast. Caches pnpm.
> Faster CI feedback

- src/pages/docs/administration/copilot/index.md
This PR adds a link to the copilot extension marketplace listing
> Added a link to the marketplace

- public/docs/css/main.css
- public/docs/css/vars.css
> Code blocks styles hotfix

- src/pages/docs/infrastructure/accounts/index.md
Add OpenID Connect to the list.
> Add OpenID Connect to the list.

- .octopus/variables.ocl
Moving this into the library set, so we can use it from all projects.
> Moving the variable into the AWS library variable set.

- public/docs/css/main.css
- public/docs/css/vars.css
- New paddings within side nav component.
- Adjusted it's height as well for both mobile and desktop.
- New scrollbar for side nav.
> Side nav ui changes

- dictionary-octopus.txt
- src/pages/docs/administration/migrate-spaces-with-octoterra/index.md
This PR adds documentation that describes how to migrate a space and projects, including CaC projects, with Octoterra.
> Added hidden docs for migrating spaces with octoterra

- src/pages/docs/administration/migrate-spaces-with-octoterra/index.md
Updated the octoterra docs to describe the scenario where a CaC project is exported, modifed, and reimported.
> Updated docs for new scenario

- src/pages/docs/infrastructure/deployment-targets/kubernetes/kubernetes-agent/index.md
Remove double instance of the word “the”
> Fix minor typo

- public/docs/css/main.css
- public/docs/css/vars.css
- src/themes/octopus/components/NavigationItem.astro
https://github.com/OctopusDeploy/docs/assets/148771144/4db3c045-a6b9-46da-8929-4254bb5545a6
> Side nav changes + icon

- dictionary-octopus.txt
- src/pages/docs/administration/managing-infrastructure/performance/record-a-performance-trace.md
- src/pages/docs/deployments/aws/ecs/index.md
- src/pages/docs/infrastructure/deployment-targets/tentacle/windows/automating-tentacle-installation.mdx
- src/pages/docs/installation/automating-installation.mdx
- src/pages/docs/packaging-applications/build-servers/github-actions.md
- src/pages/docs/support/call-jenkins-rest-api-from-powershell.md
Broken links fixed for multiple docs pages
> Broken link fixed

- src/pages/docs/administration/reporting/index.md
- src/pages/docs/administration/reporting/report-on-deployments-excel-template.md
- src/pages/docs/administration/reporting/report-on-deployments-using-excel.md
- src/pages/docs/administration/reporting/report-on-deployments-with-sql.md
Mainly updating the section on `DeploymentHistory` update frequency. Also includes some small improvements elsewhere.
> Reporting updates

- src/pages/docs/administration/data/backup-and-restore.md
Refresh triggered by the [https://octopushq.atlassian.net/wiki/spaces/MAR/pages/3092086876/Octopus+Docs](Docs retirement check).
> Refreshes the backup/restore page

- public/docs/css/main.css
There was a request to have a bold font for current page in side nav
> Side nav bold font

- src/pages/docs/projects/version-control/github/index.md
Updating the hint on the GitHub App announcement re [this conversation on Slack](https://octopusdeploy.slack.com/archives/C03UDS16R6G/p1721259669659729?thread_ts=1721225542.092489&cid=C03UDS16R6G)
> Updating GitHub App announcement

- src/pages/docs/administration/reporting/index.md
- src/pages/docs/administration/reporting/report-on-deployments-excel-template.md
- src/pages/docs/administration/reporting/report-on-deployments-using-excel.md
- src/pages/docs/administration/reporting/report-on-deployments-with-sql.md
This PR is updating the reporting pages.
The only changes needed were to add a title icon to the pages.
> Updating reporting pages

- src/config.ts
> GTM update

- .github/workflows/branch-validation.yml
- .github/workflows/build-astro.yml
- package.json
- pnpm-lock.yaml
- src/themes/octopus/utilities/page-report.js
> Adds a CSV report

- dictionary-octopus.txt
- src/pages/docs/deployments/databases/sql-server/dacpac.md
Updating instructions as they were referencing a template that has been deprecated and removed.
> Updating dacpac instructions

- src/pages/docs/administration/high-availability/load-balancing/index.mdx
Resolves the self-redirect loop
> Redirect loop fix

- src/pages/docs/infrastructure/workers/autoscaling-workers/cluster-configuration.md
A few typos were found, and added extra fields to the table to support local dev cluster types.
* Moved table description above the table
* added new rows
* fixed a typo
* updated headings
* 
OLD VERSION
NEW VERSION
> Tweak K8s Cluster Config

- src/pages/docs/infrastructure/workers/kubernetes-worker/index.md
Ideally this would include the feedback survey link - but for now we only know the community slack.
This can be updated once we have the link - but for now, at least it feels complete.
> Add EAP Callout

- src/pages/docs/best-practices/self-hosted-octopus/installation-guidelines.mdx
- src/pages/docs/infrastructure/accounts/azure/index.md
- src/pages/docs/infrastructure/deployment-targets/dynamic-infrastructure/azure-accounts.md
- src/pages/docs/octopus-rest-api/examples/users-and-teams/add-azure-ad-to-users.mdx
- src/pages/docs/security/authentication/auth-provider-compatibility.md
- src/pages/docs/security/authentication/auto-user-creation.md
- src/pages/docs/security/authentication/azure-ad-authentication.mdx
- src/pages/docs/security/authentication/googleapps-authentication.mdx
- src/pages/docs/security/authentication/index.md
- src/pages/docs/security/users-and-teams/external-groups-and-roles.md
- src/shared-content/scripts/add-azure-ad-identity-to-users-scripts.include.md
* GoogleApps to Google Workspace
* AzureAD/Azure AD/Azure Directory to Microsoft Entra ID
> Authentication provider name changes

- src/pages/docs/tenants/guides/index.md
Adding an icon to the tenant's guide index page.
> Adding icon to Tenant guide page

- src/pages/docs/octopus-cloud/index.mdx
Copy updates to the Octopus Cloud page as per the [request here](https://octopusdeploy.slack.com/archives/C077NUMLJSH/p1725512330952709).
> Octopus Cloud Overview copy updates

- src/pages/docs/administration/migrate-spaces-with-octoterra/index.md
This PR adds a warning to the migration docs.
> Added warning about migration

- src/pages/docs/octopus-cloud/index.mdx
Copy updates as per [this request on Slack](https://octopusdeploy.slack.com/archives/C077NUMLJSH/p1726448068933699?thread_ts=1725512330.952709&cid=C077NUMLJSH)
> Octopus Cloud copy updates

- src/pages/docs/projects/version-control/converting/migrating-variables.md
- src/pages/docs/projects/version-control/creating-release-from-a-build-server-plug-in.mdx
> Update Creating releases from a build server plugin on a version-controlled project

- .github/workflows/branch-spellcheck.yml
- .github/workflows/branch-validation.yml
- .github/workflows/build-astro.yml
- package.json
Updates to pnpm `9.10.0`, which will be consistent with the version used in the frontend (being updated in https://github.com/OctopusDeploy/OctopusDeploy/pull/27659)
> Update to pnpm 9.10.0

- package.json
- pnpm-lock.yaml
Missed this one when doing #2518
> Update @pnpm/exe to 9.10.0

- src/pages/docs/packaging-applications/create-packages/octopus-cli.md
A comment is appearing on the page, this removes it.
> Fix a comment appearing on the cli page.

- .github/CODEOWNERS
@skermajo and I have discussed that this page better fits BIT over PGT so I've updated the code owners.
> Update CODEOWNERS for managing subscriptions

- src/pages/docs/kubernetes/targets/kubernetes-agent/upgrading.md
> Fix Kubernetes agent auto-upgrading dates

- src/pages/docs/octopus-cloud/getting-started-with-cloud.mdx
Structure/content changes are individually noted.
Other changes are primarily to match instructions to our current UI.
[sc-82146]
> Update Octopus Cloud Getting Started

- .github/workflows/branch-validation.yml
- .github/workflows/build-astro.yml
A recent update highlighted this issue with the package id.
> Updates the package for push build info

- src/pages/docs/kubernetes/targets/kubernetes-agent/images.md
Update docs to include a suggested worker tool image for ARM workloads
[sc-95659]
> Update worker tools image suggestion for ARM workloads

- src/pages/docs/installation/file-storage/local-storage.mdx
Image border isn't applied correctly on last image on the page
> Image border fix on DFS page

- src/pages/docs/octopus-cloud/frequently-asked-questions.md
Amazing - thanks for this page!
This is just some formatting changes to bring the page into our usual markdown style.
> Formatting changes

- src/pages/docs/kubernetes/targets/kubernetes-agent/index.md
This is a re-application of #2396 as it appears to have been lost during the `kubedocs` re-organization
> Update Kubernetes agent tooling

- src/pages/docs/deployments/custom-scripts/index.md
- src/pages/docs/deployments/custom-scripts/scripts-in-packages/index.md
- src/pages/docs/packaging-applications/package-repositories/docker-registries/index.md
- src/pages/docs/packaging-applications/package-repositories/guides/container-registries/docker-hub.md
- src/pages/docs/projects/steps/configuration-features/substitute-variables-in-templates.md
- src/pages/docs/releases/issue-tracking/jira.md
- src/pages/docs/security/users-and-teams/user-roles.md
- src/shared-content/teamcity/teamcity-pack.include.md
Removing / updating broken links
> Fixing broken link

- src/pages/docs/packaging-applications/build-servers/github-actions.md
While dogfooding my own GH action docs, I realised they could be a bit clearer (and more correct). 
I will comment an explanation for each change on the code. Feel free to suggest some more changes and I'll add them, if you've been using the docs yourself too!
✅ Correctness
☑️ Typos etc. 
Fixes[sc-93404]
> Small improvements to GH action docs

- src/layouts/Author.astro
- src/layouts/Redirect.astro
- src/themes/octopus/components/Navigation.astro
- src/themes/octopus/components/NavigationItem.astro
- src/themes/octopus/layouts/Redirect.astro
Backstop fix for the navigation issue.
> Fix navigation

- src/pages/docs/octopus-cloud/uptime-slo.md
Update Octopus Cloud uptime statistics for January 2025.
> Update Uptime stats for January 2025

- src/pages/docs/octopus-cloud/migrations.md
This PR updates the Cloud Migration documents as per [this request](https://octopusdeploy.slack.com/archives/C04GAH78491/p1738116662587109)
> Updating Cloud Migration Documentation

- src/pages/docs/octopus-cloud/dynamic-worker.md
Add a new page to provide an overview of dynamic workers for Octopus Cloud.
> New dynamic worker page for Octopus Cloud section

- src/pages/docs/projects/built-in-step-templates/email-notifications.md
Update the email notification docs to include the credentials required for microsoft oauth 2.0 authentication.
Include instructions on setting up the required app registration and federated credentials.
[sc-104631]
> Update email notification docs to include Microsoft OAuth

- src/pages/docs/octopus-rest-api/tentacle.exe-command-line/update-trust.md
- src/pages/docs/security/octopus-tentacle-communication/regenerate-certificates-with-octopus-server-and-tentacle.md
* Updates the docs to better cover polling tentacles.
* Fixes automatic rotation script commands.
* Grammatical fixes
> Certificate regen updates

- src/pages/docs/projects/export-import/index.mdx
Removed version import/export released. Added link to migration docs
> Added link from import/export to migration docs

- src/pages/docs/projects/version-control/config-as-code-reference.mdx
- src/pages/docs/projects/version-control/converting/index.mdx
- src/shared-content/version-control-repository-url-format.include.md
> Add note about different vsc providers using different repo URL formats

- src/pages/docs/administration/octoai/index.md
This PR adds a hidden page that we will share with select customers who are trialing OctoAI.
> Added hidden page for OctoAI

- src/pages/docs/projects/steps/execution-containers-for-workers/index.mdx
Updates dockerhub link for execution container runtime-deps image.
> Update Dockerhub link

- dictionary-octopus.txt
- src/shared-content/upgrade/upgrade-in-place-upgrade.include.md
Added recommendation to scale database during upgrades to our guides
> Added recommendation to scale database during upgrades

- src/pages/docs/octopus-cloud/migrations.md
- src/pages/docs/projects/export-import/index.mdx
> Update export/import and migration docs to include CaC projects

- src/pages/docs/infrastructure/accounts/openid-connect.md
- src/pages/docs/packaging-applications/package-repositories/guides/container-registries/amazon-ec2-container-services.md
Updates ECR docs to include configuration details for Oidc.
> Docs for AWS ECR Oidc feeds

- src/pages/docs/kubernetes/live-object-status/installation.md
- src/pages/docs/kubernetes/targets/kubernetes-agent/kubernetes-monitor.md
- src/pages/docs/kubernetes/targets/kubernetes-agent/upgrading.md
Several links were in the wrong format and did not work.
> Fix broken links

- src/pages/docs/octopus-cloud/uptime-slo.md
Update Octopus Cloud uptime statistics for April 2025.
> Update Uptime stats for April 2025

- src/pages/docs/packaging-applications/package-repositories/artifactory-generic-feeds.md
> Add known limitation in the teamcity plugin due to Octo CLI

- src/pages/docs/packaging-applications/package-repositories/guides/container-registries/amazon-ec2-container-services.md
Add callout with limitations of using worker creds with ECR feeds on server.
[sc-104095]
> Add callout for using worker credentials with ECR feeds

- src/pages/docs/getting-started/managing-octopus-subscriptions.md
- src/pages/docs/octopus-cloud/getting-started-with-cloud.mdx
- src/pages/docs/security/users-and-teams/index.md
Renames Access Control to User Access and Admin Access (for server subscriptions).
[sc-109701]
> Update Access Control naming to match CCv2

- src/pages/docs/octopus-rest-api/cli/octopus-task-wait.mdx
Updating flag descriptions to align with the latest changes in https://github.com/OctopusDeploy/cli/pull/519
> Update task wait command options for octopus cli

- dictionary-octopus.txt
- src/pages/docs/deployments/custom-scripts/passing-parameters-to-scripts.mdx
- src/pages/docs/deprecations/index.md
- src/pages/docs/projects/variables/output-variables.mdx
- src/shared-content/deprecated-items/scriptcs-deprecated.include.md
> Add deprecation warnings for scriptcs on pages referring to it

- src/pages/docs/administration/managing-infrastructure/diagnostics.md
- src/pages/docs/administration/upgrading/guide/index.md
Swapped some pictures around so they matched their titles and added the integrity check to one upgrade doc I missed.
> Updates to some prior docs I changed

- src/pages/docs/octopus-cloud/uptime-slo.md
> Updated Uptime SLO stats for May 2025

- src/pages/docs/infrastructure/workers/index.mdx
> removed out of place character

- .octopus/deployment_process.ocl
Updates the Slack notification message after deployment.
> Deployment process update

- cspell.json
- package.json
Configuration for cspell to catch common problem phrases and suggest alternatives.
Fixes for existing content to align with this configuration.
> Updated cspell config

- src/pages/docs/octopus-cloud/uptime-slo.md
Add Octopus Cloud uptime statistics for July 2025.
> Add July 2025 uptime stats

- src/pages/docs/octopus-cloud/maintenance-window.md
Updated maintenance window content to clarify, highlight benefits and be more focused on the information customers need.
> Refresh maintenance window content

- src/pages/docs/infrastructure/accounts/azure/index.md
- src/pages/docs/packaging-applications/package-repositories/guides/container-registries/azure-container-services.md
Updating some links to Microsoft federated credentials docs.
> Updating azure oidc docs links

- src/pages/docs/platform-hub/policies/index.md
Fixed wording on Policies docs about Alpha status
> Fixed warning about alpha status

- src/pages/docs/approvals/jira-service-management/index.md
- src/pages/docs/approvals/servicenow/index.md
[sc-121889]
Relates to https://github.com/OctopusDeploy/OctopusDeploy/pull/36877
Fixes https://github.com/OctopusDeploy/Issues/issues/9634
> added a list of manifest variables

- src/pages/docs/platform-hub/policies/examples.md
The Policy examples do not currently contain the following examples.
- Process Templates
- Relative step position checking 
This PR adds those examples.
> Add new process template and relative positioning examples

- src/pages/docs/platform-hub/installation-guide.md
[sc-123554]
Applying docs changes from here https://whimsical.com/installation-guide-for-public-preview-J4csHUKbHYrTaa2RHH2YtE
> Updating Platform Hub Public Preview installation docs with installer links and Docker commands
